### ISSUE TITLE
Custom headers absent for monorepo continuous deployment

### ISSUE THREAD

**Issue by okaluhina** [aws-amplify/amplify-console#1014]
** Please describe which feature you have a question about? **
I am trying to add custom security headers. And adding customHeaders in amplify.yml works for traditional repo, but fails to add headers during monorepo deployment.

** Provide additional details**
This is my amplify.yml file:
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - cd ../..
            - npm ci
            - npx lerna bootstrap --no-ci
            - cd packages/backend
        build:
          commands:
            - envCache --set stackInfo ""
            - amplifyPush --simple
            - cd ../..
            - cd $AWS_MONOREPO_APPROOT
            - npm run build
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      customHeaders:
       - pattern: '**/*'
         headers:
         - key: 'Content-Security-Policy'
           value: 'default-src self'
    appRoot: packages/backoffice
```
