### ISSUE TITLE
No more File Storage information displayed any longer

### ISSUE THREAD

**Issue by pchevallier** [aws-amplify/amplify-console#1026]
**Issue Description**
Although it is properly listed on the CLI (see below), the File storage view does not display the details 
All the other tabs (Overview, Authentification,...) work just fine. 
![Screen Shot 2020-09-04 at 10 18 01 AM](https://user-images.githubusercontent.com/20049529/92249364-f7051800-ee97-11ea-8921-1df3dbe5b105.png)

 **Detailed Steps To Reproduce**
I have no idea how to reproduce this bug. It just appeared on the console one day. 

 **Expected behavior**
Get the Storage information for my backend server. 

**Application Details**
arn:aws:amplify:us-east-1:942621100382:apps/d2kcfe1b6g54ul
    
```
Current Environment: devb

| Category | Resource name                     | Operation | Provider plugin   |
| -------- | --------------------------------- | --------- | ----------------- |
| Auth     | cognitocf0c6096                   | No Change | awscloudformation |
| Function | S3Trigger2cc272e8                 | No Change | awscloudformation |
| Function | createreactappauthamplifyd6a143b7 | No Change | awscloudformation |
| Storage  | s39db80ac8                        | No Change | awscloudformation |
| Api      | suvey                             | No Change | awscloudformation |

```
        
(https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) (Be sure to remove any sensitive data)
version: 1
```
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - export BASE_PATH=$(pwd)
        - yum install -y gcc openssl-devel bzip2-devel libffi-devel python3.8-pip
        - cd /opt && wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz
        - cd /opt && tar xzf Python-3.8.2.tgz 
        - cd /opt/Python-3.8.2 && ./configure --enable-optimizations
        - cd /opt/Python-3.8.2 && make altinstall
        - pip3.8 install --user pipenv
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - cd $BASE_PATH
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - ls -l ./src
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```
