### ISSUE TITLE
Amplify Monorepo + Cloudformation - Error: V2 amplify.yml found with multiple appRoots and no target appRoot set

### ISSUE THREAD

**Issue by divyavanmahajan** [aws-amplify/amplify-console#1029]
To reproduce

1. Create a monorepo setup with a single folder webapp. The webapp folder has a build.sh - which creates a simple webpage.
2. Amplify.yml at the root - with a single appRoot entry for webapp
3. Use Cloudformation to create an Amplify App and branch for this.
4. Build the branch. In the build phase, Cloning step - you get an error. 

> [ERROR]: !!! Error: V2 amplify.yml found with multiple appRoots and no target appRoot set

```
version: 1
applications: 
  - appRoot: webapp
    frontend:
      phases:
        build:
          commands:
            - ./build.sh
      artifacts:
        baseDirectory: build
        files:
          - "**/*"
```

```
#!/bin/sh
mkdir build
echo Hello > build/index.html
```

```
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: MyAmplifyApp
      AccessToken: "GITHUBTOKEN"
      CustomRules:
        - Source: </^([^.]+$)|^(?!\/(ssoproxy.html|ssologout.html|ssologin.html|ssoerror.html)).*\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>
          Status: 200
          Target: "/index.html"
      Description:
        Fn::Sub: ${AWS::StackName}-amplifyapp
      EnvironmentVariables:
        - Name: REACT_APP_REGION
          Value:
            Fn::Sub: ${AWS::Region}
      #   OauthToken: String
      Repository: "GitHub/repo"
  AmplifyMainBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId:
        Fn::GetAtt: [AmplifyApp, AppId]
      BranchName: master
      EnableAutoBuild: true
      EnablePullRequestPreview: false
```
