### ISSUE TITLE
Amplify monoRepo + AWS CLI - no support for appRoot when creating a branch.

### ISSUE THREAD

**Issue by divyavanmahajan** [aws-amplify/amplify-console#1030]
AWS CLI does not support setting the appRoot when creating an Amplify Branch.
Version:
> aws-cli/2.0.46 Python/3.7.4 Darwin/19.6.0 exe/x86_64

```
  create-branch
          --app-id <value>
          --branch-name <value>
          [--description <value>]
          [--stage <value>]
          [--framework <value>]
          [--enable-notification | --no-enable-notification]
          [--enable-auto-build | --no-enable-auto-build]
          [--environment-variables <value>]
          [--basic-auth-credentials <value>]
          [--enable-basic-auth | --no-enable-basic-auth]
          [--tags <value>]
          [--build-spec <value>]
          [--ttl <value>]
          [--display-name <value>]
          [--enable-pull-request-preview | --no-enable-pull-request-preview]
          [--pull-request-environment-name <value>]
          [--backend-environment-arn <value>]
          [--cli-input-json | --cli-input-yaml]
          [--generate-cli-skeleton <value>]
          [--cli-auto-prompt <value>]
```

**Comment by nimacks** [comment]
Hi, @divyavanmahajan the amplify console defines how to build your app via the build spec. It looks something like this. This is where we define the appRoot. 

```
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: react-amplify
```
You can view the build spec via this CLI command `aws amplify get-app --app-id [APP-ID] --region [REGION]`

To update you can run something like this `aws amplify update-app`.

See here for syntax details : https://docs.aws.amazon.com/amplify/latest/APIReference/API_UpdateApp.html
References : https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/
