### ISSUE TITLE
Set build time in environment variable

### ISSUE THREAD

**Issue by mansiva** [aws-amplify/amplify-console#1118]
** Please describe which feature you have a question about? **
Amplify Console build settings

** Provide additional details**
Using an Amplify project setup with continuous deployments, I would like to know if there is a way to set an environment variable that contains the datetime or timestamp of when the build was made.

We currently have an environment variable in the console `REACT_APP_VERSION` that we display in our app, but it needs to be manually changed and in between there may be commits so it's hard to keep track of what version issues are reported. I know how to add env variables to the build settings, but not sure if there's a way to grab the current time.

This is what we have in our build settings `env` section.

```
version: 1
env:
  variables:
    REACT_APP_ENV: $USER_BRANCH
```

**Comment by ganipcanot** [comment]
You could probably use `AWS_COMMIT_ID` for this.  Ref: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html

**Comment by mansiva** [comment]
Thanks, good idea. I saw that there's also a `AWS_JOB_ID` which works even better. Still would have been nice to have a datetime value though.
```
env:
  variables:
    REACT_APP_ENV: $USER_BRANCH
    REACT_APP_BUILD: $AWS_JOB_ID
```
