### ISSUE TITLE
Building a VueJs app takes forever for the first time with no details

### ISSUE THREAD

**Issue by amersaw** [aws-amplify/amplify-console#1143]
**App Id**:d2y71mdaufgd7e
**Region**:eu-west-1
**Step**: First deployment (build)
**Status**: Unknown

**Issue/question**
When connecting a new branch the build process takes forever without any additional information.
The connected branch is for simple vuejs app (below is the `amplify.yml` file content).
Locally I can build and serve the app

**Error message**
No Error Message

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

The only thing that I can see is the gray bars without any aditional information
![image](https://user-images.githubusercontent.com/5200779/96189043-792d3580-0f48-11eb-8d5b-0886bbca0a13.png)

Here is what the build page looks like:
![image](https://user-images.githubusercontent.com/5200779/96189175-b1347880-0f48-11eb-8315-0f56181ec009.png)

Below is how the public amplifyapp page looks like:
![image](https://user-images.githubusercontent.com/5200779/96189757-c6f66d80-0f49-11eb-9f79-059e37c34693.png)

I can cancell the build process, restarting the build will lead to the same result.

Here is the `amplify.yml` file content:
```yml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```

**Comment by amersaw** [comment]
The issue was related to the `apmlify.yml` where the `frontend` node ought to be in the root not inside the `applications` node, like the following:

```yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

But it would be very useful to have an indication about the current application deployment status, AWS amplify isn't even show any progress nor logs nor error message, which is very confusing.
