### ISSUE TITLE
Custom Cache-Control header does not work

### ISSUE THREAD

**Issue by MrHertal** [aws-amplify/amplify-console#1170]
Hi,

I followed [instructions](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html) to add a custom `Cache-Control` header for every HTTP response. Here is my `amplify.yml`:

```yaml
version: 1
frontend:
  phases:
    build:
      commands: []
  artifacts:
    baseDirectory: /assets
    files:
      - '**/*'
  cache:
    paths: []
  customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'Cache-Control'
          value: 'max-age=86400'
    - pattern: '**/*'
      headers:
        - key: 'custom-header'
          value: 'my-value'
```

After redeploying I do a HTTP request and successfully get `custom-header` in the response. But `Cache-Control` has this value: `public, max-age=0, s-maxage=2`.

Am I missing something?

Thanks for your help.

**Comment by gwryssekk** [comment]
Hi.  We were able to recreate this issue and have identified a fix.  Will update when we have an ETA.

**Comment by MrHertal** [comment]
Hi, do you have an ETA?

**Comment by MrHertal** [comment]
I have migrated custom headers following the new [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html) 

<img width="730" alt="snap" src="https://user-images.githubusercontent.com/11944221/100877492-27fde480-34a9-11eb-82f9-c09bcdb02289.png">

Without success.

I get `cache-control: max-age=0` and also a miss from CloudFront.

**Comment by kahdojay** [comment]
Hi, we are actively working on rolling out a fix for Cache-Control customer headers unable to be set which should be in all regions within the next few weeks.

**Comment by satyadeepk** [comment]
@kahdojay Is there any workaround for setting cache control header? 
Is there any default cache behaviour we can enforce in the meanwhile?

We are seeing max-age=0 in all requests which means Amplify is pretty much useless as caching and instant cache-invalidation is the main usecase for many of us.

**Comment by kahdojay** [comment]
@satyadeepk Bear in mind that Amplify-hosted apps will honor and reuse any Cache-Control request headers sent by clients, so if your request includes max-age=0, that will get returned.

https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html

If that's not the case here feel free to share your appId and region and we can take a closer look

**Comment by MrHertal** [comment]
I tested again this morning and it's now working.

**Comment by kahdojay** [comment]
We've deployed a fix to all regions. Closing this issue for now, @MrHertal @satyadeepk please let reopen and let us know if you're still seeing this issue.

**Comment by azheng003** [comment]
@kahdojay When I add a pattern, it removes the single quotes from the pattern.

I add:
```
  - pattern: '/static/**/*'
    headers:
      - key: Cache-Control
        value: 'public,max-age=31536000,immutable'
```

and it becomes:

```
  - pattern: /static/**/*
    headers:
      - key: Cache-Control
        value: 'public,max-age=31536000,immutable'
```
