### ISSUE TITLE
Amplify CI logs are incomplete or command failed without proper error reporting

### ISSUE THREAD

**Issue by ayeganyan** [aws-amplify/amplify-console#1205]
** Please describe which feature you have a question about? **
Amplify CI

** Provide additional details**
I have the following build script for Amplify CI
```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: src
  phases:
    preTest:
      commands:
        - yum install -y gcc-c++ make ;
        - curl -sL https://rpm.nodesource.com/setup_12.x | bash - ;
        - yum install -y nodejs ;
        - node ./src/api/tests/initialize.js
    test:
      commands:
        - npm test
```

I have added the test part, and like to install nodejs 12 package first, then run my initialize script to create automation user (which will be later to test APIs ).
this scripts are working just fine in amazon linux 2 docker container, however logs seem incomplete in console:
here the latest lines of logs (Note it shows test stage completed):
![Screenshot from 2020-11-07 17-01-22](https://user-images.githubusercontent.com/22121843/98441935-0401ea00-211b-11eb-9e12-512188e79629.png)
:
