### ISSUE TITLE
(Monorepo App) Unable to set custom headers

### ISSUE THREAD

**Issue by AshwaniChoudhary** [aws-amplify/amplify-console#1207]
Hi, I am trying to set the custom security and cache header, as mentioned [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-headers.html#setting-custom-headers).

But after doing that my build is failing.

Steps to replicate:
1. create a new project by linking bitbucket repo.

** After successfully build and deployment.

2. Set custom headers for an app in the AWS Management Console.
 Paste below configuration in the console's customHeader.yml popup

```yml
  - pattern: '**/*'
    headers:
      - key: 'Strict-Transport-Security'
        value: 'max-age=31536000; includeSubDomains'
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'Content-Security-Policy'
        value: 'default-src self'
```
3. Push a new commit to your branch.

And your build will fail.

**Comment by kahdojay** [comment]
@AshwaniChoudhary just making sure, are you entering the config into the custom headers settings GUI? Or are you deploying it as a `customHttp.yml` file? (if the latter note the filename must be customHttp.yml)

Once potential issue is that your config must be nested inside a top level customHeaders field, i.e.:

```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'Strict-Transport-Security'
        value: 'max-age=31536000; includeSubDomains'
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'Content-Security-Policy'
        value: 'default-src self'
```
(you may have done that already but I don't see it in your example, so just making sure)

If none of the above addresses your issue, feel free to provide your region, appId, and example job number so we can take a closer look.

**Comment by nimacks** [comment]
@AshwaniChoudhary any updates?

**Comment by AshwaniChoudhary** [comment]
Hi @kahdojay and @nimacks 

Here you can see my build history
![image](https://user-images.githubusercontent.com/4927229/99143376-d79e1e80-2682-11eb-9b8c-67f6eccb36ba.png)

After updating custom header like below, my build is failing 
<img width="1373" alt="Screenshot 2020-11-14 at 2 04 53 PM" src="https://user-images.githubusercontent.com/4927229/99143323-855cfd80-2682-11eb-9402-476381c88c0f.png">

App ARN:
arn:aws:amplify:ap-southeast-1:254528787632:apps/d2nt8uwtpkgm9r

Please let me know if you need anything else

Thanks
Ashwani Kumar

**Comment by AshwaniChoudhary** [comment]
Attaching the build log
[log (2).txt](https://github.com/aws-amplify/amplify-console/files/5540404/log.2.txt)

**Comment by GunnarSturla** [comment]
I'm having the same problem, initially using a custom header configuration, but also using @AshwaniChoudhary's configuration. 


Here's the tail of my build logs, it's not showing any errors but does terminating earlier than a successful build
```
2020-11-17T14:29:14.187Z [INFO]: The project was built assuming it is hosted at /.
                                 You can control this with the homepage field in your package.json.
2020-11-17T14:29:14.187Z [INFO]: The build folder is ready to be deployed.
                                 You may serve it with a static server:
                                 npm install -g serve
                                 serve -s build
2020-11-17T14:29:14.187Z [INFO]: Find out more about deployment here:
                                 https://cra.link/deployment
2020-11-17T14:29:14.324Z [INFO]: # Completed phase: build
2020-11-17T14:29:14.325Z [INFO]: ## Build completed successfully
2020-11-17T14:29:14.328Z [INFO]: # Starting caching...
2020-11-17T14:29:14.491Z [INFO]: Creating cache artifact...
2020-11-17T14:29:14.495Z [INFO]: # Cache artifact is: 0MB
2020-11-17T14:29:14.495Z [INFO]: # Uploading cache artifact...
2020-11-17T14:29:14.614Z [INFO]: # Caching completed
2020-11-17T14:29:14.616Z [INFO]: # Starting environment caching...
2020-11-17T14:29:14.616Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by AshwaniChoudhary** [comment]
Hello Guys, Any update??

**Comment by DaveOrDead** [comment]
I have the exact same issue. Build fails, but logs show it being successful. 

Removing custom headers allows build to work again.

**Comment by kahdojay** [comment]
@AshwaniChoudhary it appears you have a monorepo app - can you set your custom header spec settings as follows:

```
applications:
  - appRoot: <replace_with_approot>
    customHeaders:
      - pattern: '**/*'
        headers:
          - key: 'Strict-Transport-Security'
            value: 'max-age=31536000; includeSubDomains'
          - key: 'X-Frame-Options'
            value: 'SAMEORIGIN'
          - key: 'X-XSS-Protection'
            value: '1; mode=block'
          - key: 'X-Content-Type-Options'
            value: 'nosniff'
          - key: 'Content-Security-Policy'
            value: 'default-src self'
```

And let me know if this fixes it. We will be updating the docs to include this instruction for monorepo apps as well.

**Comment by AshwaniChoudhary** [comment]
@kahdojay is still not working.
1. I updated the configuration like below.
![Screenshot 2020-11-21 at 12 57 35 PM](https://user-images.githubusercontent.com/4927229/99882867-73162d00-2c49-11eb-9eb7-346330af5c35.png)

2. It shows that the configuration is saved.
![Screenshot 2020-11-21 at 12 57 51 PM](https://user-images.githubusercontent.com/4927229/99882881-8f19ce80-2c49-11eb-86f2-f4bd32751fc1.png)

3. Refresh the page and all gone.
![Screenshot 2020-11-21 at 10 32 07 PM](https://user-images.githubusercontent.com/4927229/99882899-afe22400-2c49-11eb-9a0f-7e1810eb01d5.png)

Please suggest the needful.

**Comment by GunnarSturla** [comment]
@kahdojay Yes, my app is also in a monorepo. My region is us-east-1 and the appId is `dgps1ni1lzrz9`

I tried the custom header spec as you recommended, both where the `appRoot` had a trailing slash, and also without one.  Unfortunately, I had the same problem as @AshwaniChoudhary , where the spec disappeared after reloading the configuration page. The build did succeed, but the headers did not get applied.

Thanks for your help and let us know if there's anything else we can try

**Comment by DaveOrDead** [comment]
@kahdojay hey mate, yep also a monorepo, had the exact same experience as both @GunnarSturla and @AshwaniChoudhary on reload.

AppId: d3o3z3a0jc9olh
Region: ap-southeast

thanks for your help so far!

**Comment by kahdojay** [comment]
Thanks for confirming. This is a bug on our end - in the meantime, you can deploy `customHttp.yml` file in your project root as described in the docs using the monorepo format to configure the custom headers. Once the format is fixed in the gui we'll update here at which point you'll be able to switch back.

**Comment by DaveOrDead** [comment]
@kahdojay hey mate, I've deployed `customHttp.yml` in a few different formats but none seem to apply the headers.

Initially I tried in the root of my wider project - but this didn't take hold, which makes sense as it isn't part of the build / deployment.

I then tried putting it in the root of my monorepo directory (`client`) the following combinations: 

```
applications:
  - appRoot: 'client'
    customHeaders:
      - pattern: '**/*'
        headers:
          - key: 'Strict-Transport-Security'
            value: 'max-age=31536000; includeSubDomains'
```

with a trailing slash: 

```
applications:
  - appRoot: 'client/'
    customHeaders:
      - pattern: '**/*'
        headers:
          - key: 'Strict-Transport-Security'
            value: 'max-age=31536000; includeSubDomains'
```

and also without the `applications/appRoot` wrapper:

```
customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'Strict-Transport-Security'
          value: 'max-age=31536000; includeSubDomains'
```

but on checking the headers, they haven't been applied

**Comment by DaveOrDead** [comment]
Update! Managed to get it working.

I added the following `customHttp.yml` in the root of the wider app - not the monorepo that gets deployed. (note no trailing slash on the `appRoot` value - I tried this it broke the build.)

```
applications:
  - appRoot: 'client'
    customHeaders:
      - pattern: '**/*'
        headers:
          - key: 'Strict-Transport-Security'
            value: 'max-age=31536000; includeSubDomains'
          - key: 'X-Frame-Options'
            value: 'SAMEORIGIN'
          - key: 'X-XSS-Protection'
            value: '1; mode=block'
          - key: 'X-Content-Type-Options'
            value: 'nosniff'
          - key: 'Content-Security-Policy'
            value: 'default-src self'
```

Amplify then cancelled the build saying no changes detected - which technically there weren't within the monorepo.

Headers not displaying.

I then pushed some arbitrary text change in the monorepo to kick off a build, once that had completed, the headers started showing successfully!

Thanks for all your help :)
