### ISSUE TITLE
Integrating an automated test runner into the Amplify Build process.

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-console#121]
**Is your feature request related to a problem? Please describe.**
I would like to run my automated jest tests as part of the Amplify Console build process.

**Describe the solution you'd like**
A phase in the Build Settings like:
```
    preBuild:
      commands:
        - npm install
    test:
      commands:
        - npm test --watchAll=false
    build:
      commands:
        - npm run build
```

**Describe alternatives you've considered**
Coupling Amplify Console with TravisCI or similar, but since I don't need the Build features from Travis CI, seems like a waste.

**Additional context**
I have been using the Amplify Console as a CI tool and it works really well. I would really like to utilize our test runner to catch failed tests automatically and abort a build. 

Additionally, I would really like to be able to integrate the Amplify Console with the Github Checks API, so that we can catch failures at the PR review step in our process.
