### ISSUE TITLE
AWS Build Failed: error @ava/babel@1.0.1: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by arximughal** [aws-amplify/amplify-console#1215]
All AWS Amplify Builds suddenly started failing due to this error. 
```
2020-11-10T18:25:42.251Z [WARNING]: error @ava/babel@1.0.1: The engine "node" is incompatible with this module. Expected version ">=10.18.0 <11 || >=12.14.0 <13 || >=13.5.0". Got "10.16.0"
2020-11-10T18:25:42.264Z [WARNING]: error Found incompatible module.
2020-11-10T18:25:42.264Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2020-11-10T18:25:42.292Z [ERROR]: !!! Build failed
2020-11-10T18:25:42.293Z [ERROR]: !!! Non-Zero Exit Code detected
```

I am not sure if it's safe to share my complete provision and/or build logs here. Please let me know if you need anything more. 

Here are the node versions and other variables defined at the top of Provision Logs:

```
# Framework Versions
ENV VERSION_NODE_8=8.12.0
ENV VERSION_NODE_10=10.16.0
ENV VERSION_NODE_12=12
ENV VERSION_NODE_DEFAULT=$VERSION_NODE_10
ENV VERSION_RUBY_2_4=2.4.6
ENV VERSION_RUBY_2_6=2.6.3
ENV VERSION_BUNDLER=2.0.1
ENV VERSION_RUBY_DEFAULT=$VERSION_RUBY_2_4
ENV VERSION_HUGO=0.55.6
ENV VERSION_YARN=1.16.0
ENV VERSION_AMPLIFY=1.12.0
```

**Comment by nimacks** [comment]
Can you try using something like this in your build spec.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12

    build:
      commands:
        - nvm use $VERSION_NODE_12

```

**Comment by arximughal** [comment]
THanks @nimacks , this worked. I had to do some package updates later on but this is what I needed to fix the error mentioned.

**Comment by microtitle-io** [comment]
Thanks @nimacks, this saved a lot of head-scratching for me, too! 

More generally, if you are getting the wrong version, and it's not installed, you can do something like this:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install lts/gallium
        - nvm use lts/gallium

    build:
        - nvm install lts/gallium
        - nvm use lts/gallium
```

That got me from likely deprecated Node v12.x.x to v16.13.0, which I had been using on my desktop. Cheers :)
