### ISSUE TITLE
Application with micro frontend architecture in a mono-repo

### ISSUE THREAD

**Issue by nkashyap** [aws-amplify/amplify-console#1262]
Amplify currently support monorepo setup by creating multiple `connect app` for the same repo but with `appRoot`
(NOTE: this functionality is currently broken through https://github.com/aws-amplify/amplify-console/issues/1248). This means you have to switch between apps to see progress and also, build is triggered on all the apps even when the code is not changed for the related micro-app.

##### directory structure
```
repo
   - amplify
   - amplify.yml
   - package.json 
   - packages
           - components
           - assets
           - auth            # create react app hosted on https://auth.example.com
           - web             # create react app hosted on https://www.example.com
           - dashboard       # create react app hosted on https://dashboard.example.com
```

##### amplify.yml
```
version: 1
applications:
  - appRoot: /packages/auth
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install --ignore-engines
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
  - appRoot: /packages/web
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install --ignore-engines
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
  - appRoot: /packages/dashboard
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install --ignore-engines
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```

It would be really nice if all the mico-app can be displayed in one place under one app and build to be triggered based on `appRoot`
