### ISSUE TITLE
[QUESTION] Access preview URL via environment variable?

### ISSUE THREAD

**Issue by boxcee** [aws-amplify/amplify-console#1310]
** Please describe which feature you have a question about? **
When using the preview feature for pull requests, is there a way to get access to the preview URL during build time?

E.g.
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - REDIRECT_URI=$AWS_PREVIEW_URL npm run build
```
