### ISSUE TITLE
Custom headers not applied

### ISSUE THREAD

**Issue by xavierraffin** [aws-amplify/amplify-console#1317]
**Describe the bug**

According to [this documentation](https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html) I should be able to define a _Cache-Control_ header from a file _customHttp.yml_ at the root of my project.
I tried and it fails

**To Reproduce**
1. At the root of an Amplify project add a file _customHttp.yml_ with that content:

```
customHeaders:
  - pattern: /assets/*
    headers:
      - key: Cache-Control
        value: s-maxage=3000000
```

2. Push the code

3. There is no cache headers on query like https://dev.visualping.io/assets/img/icon-linkedin.svg which should have match the pattern

**Expected behavior**

I should have a Cache-Control header with a value of maxage 3000000 when request the assets

**Screenshots**

After the deployment have been done, the Custom Header section in the console was empty:

<img width="830" alt="Screen Shot 2020-11-30 at 12 19 52 PM" src="https://user-images.githubusercontent.com/1170030/100660083-60b18880-3306-11eb-915d-9b435fd0dfc8.png">

I tried to upload one manually but that change nothing, the http header are not sent anyway.

<img width="767" alt="Screen Shot 2020-11-30 at 12 19 38 PM" src="https://user-images.githubusercontent.com/1170030/100660099-67400000-3306-11eb-9966-33dd6603f866.png">

**Additional context**

I run Amplify console in Oregon

**Comment by mybNa** [comment]
We have noticed the same issue. How do we apply the custom headers to deployed application?

**Comment by spilist** [comment]
What we experienced were similar. We used the following setting:
```yml
customHeaders:
  - pattern: '/static/js/*'
    headers:
      - key: 'Cache-Control'
        value: 's-maxage=31536000'
  - pattern: '/static/css/*'
    headers:
      - key: 'Cache-Control'
        value: 's-maxage=31536000'
  - pattern: '/static/media/*'
    headers:
      - key: 'Cache-Control'
        value: 's-maxage=31536000'
  - pattern: '**/*'
    headers:
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'Strict-Transport-Security'
        value: 'max-age=31536000; includeSubDomains'
```

1. Placing `customHttp.yml` with the above contents in the root directory: nothing happened.
2. Manually set custom headers in aws console: security related headers (e.g., X-Frame-Options) are set, but cache-control is not set.

cache-control problem is definitely a bug (https://github.com/aws-amplify/amplify-console/issues/1170) but I'm not sure why `customHttp.yml` in the root directory didn't work.

**Comment by mybNa** [comment]
@spilist you mentioned security related headers worked for you and you set them manually in AWS console. After setting them did you have to deploy the app? We did set them in console but no luck. This is what we have in the console.

<img width="1249" alt="Screen Shot 2020-12-01 at 9 40 57 PM" src="https://user-images.githubusercontent.com/11697860/100834570-00fbd000-3421-11eb-96a7-408809060d66.png">

**Comment by spilist** [comment]
As far as I know, if you manually set "rewrite/redirect" and "custom headers" settings in Amplify console, they are immediately applied to the deployed frontend. You don't need to re-deploy. 

Changing environment variables is needed to be re-deploy to be applied.

**Comment by kahdojay** [comment]
There are a couple issues going on here.

@xavierraffin I believe your pattern may need to be /assets/**/*.svg or /assets/**/*

As for others, we are actively working on rolling out a fix for Cache-Control customer headers unable to be set which should be in all regions within the next few weeks. Please note however that for apps with performance mode disabled, apps will re-use cache-control headers sent in the request regardless of the custom header setting. We will update the performance mode documentation to clarify this.

**Comment by kahdojay** [comment]
@spilist @mybNa  can you provide your appId, region, and job number of the job you deployed customHttp.yml in repo root?

**Comment by xavierraffin** [comment]
@kahdojay I confirm this fix the problem on my side.
Thanks
Feel free to close from what I am concerned of

**Comment by spilist** [comment]
@kahdojay Missed the notification from github. :( 

- appId: `d241v514fg7chg`
- region: `ap-northeast-2`
- job number: The most recent one is `5`. You may refer to the [history](https://ap-northeast-2.console.aws.amazon.com/amplify/home?region=ap-northeast-2#/d241v514fg7chg/production/history).

FYI, we're using manual deployment(after build from jenkins), and customHttp is setup by amplify console like following:
```
customHeaders:
  - pattern: /static/js/*
    headers:
      - key: Cache-Control
        value: s-maxage=31536000
  - pattern: /static/css/*
    headers:
      - key: Cache-Control
        value: s-maxage=31536000
  - pattern: /static/media/*
    headers:
      - key: Cache-Control
        value: s-maxage=31536000
  - pattern: '**/*'
    headers:
      - key: X-Frame-Options
        value: SAMEORIGIN
      - key: X-Content-Type-Options
        value: nosniff
      - key: X-XSS-Protection
        value: 1; mode=block
      - key: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
```

And our `customHttp.yml` in the root directoy is like this:
```
customHeaders:
  - pattern: '/static/js/*'
    headers:
      - key: 'Cache-Control'
        value: 's-maxage=31536000'
  - pattern: '/static/css/*'
    headers:
      - key: 'Cache-Control'
        value: 's-maxage=31536000'
  - pattern: '/static/media/*'
    headers:
      - key: 'Cache-Control'
        value: 's-maxage=31536000'
  - pattern: '**/*'
    headers:
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'X-XSS-Protection'
        value: '1; mode=block'
      - key: 'Strict-Transport-Security'
        value: 'max-age=31536000; includeSubDomains'
      - key: 'Content-Security-Policy'
        value: 'default-src self'
```

Unlike console, `customHttp.yml` has `Content-Security-Policy` key, but not applied in the deployed website.

**Comment by kahdojay** [comment]
@spilist no worries! I actually don't see any `customHttp.yml` file in the zip file you uploaded. Can you double check to confirm that the zip your jenkins job is sending to Amplify does in fact have the file?

In any event, you should be able to make the change in the Amplify console for your app if that works, no need to do it in both places. That being said, once you successfully deploy a `customHttp.yml` in your project root, that will override any console setting and you will need to use that method to update your custom headers going forward.

**Comment by spilist** [comment]
I knew `customHttp.yml` will override the setting from console. I did set in console because my `customHttp.yml` didn't work. 

Anyway, I didn't know `customHttp.yml` was not included in the uploaded zip. 😱  I'll check that out. Thx.

**Comment by spilist** [comment]
@kahdojay Would you let me know how to check the contents of deployed zip file? I'm having some trials & errors.

**Comment by kahdojay** [comment]
@spilist good to hear you were able to get the customHttp.yml included in your zip. I'm going to go ahead and close out this issue.

Please track the fix for Cache-Control header in #1170

Users with Monorepo app can track the fix for updating custom headers in the console in #1207

**Comment by juliedavila** [comment]
I have this issue and tried @spilist's method of copying customHttp.yml to the build dir and no luck

```
customHeaders:
  - pattern: '**/*'
    headers:
    - key: 'Strict-Transport-Security'
      value: 'max-age=63072000; includeSubdomains; preload'
    - key: 'Content-Security-Policy'
      value: |
        default-src 'self'; img-src 'self'; script-src '"self" https://cdn.graph.office.net'; style-src '"self" https://cdn.graph.office.net https://static2.sharepointonline.com'; object-src 'none'
    - key: 'X-Frame-Options'
      value: 'DENY'
    - key: 'X-XSS-Protection'
      value: '1; mode=block'
    - key: 'Referrer-Policy'
      value: 'same-origin'
```

Arn is `arn:aws:amplify:us-east-1:742946075871:apps/d2shabhtahcul9`

**Comment by gabrielmicko** [comment]
We have the same issue.

**Comment by arledesma** [comment]
> I have this issue and tried @spilist's method of copying customHttp.yml to the build dir and no luck
> 
> ```
> customHeaders:
>   - pattern: '**/*'
>     headers:
>     - key: 'Strict-Transport-Security'
>       value: 'max-age=63072000; includeSubdomains; preload'
>     - key: 'Content-Security-Policy'
>       value: |
>         default-src 'self'; img-src 'self'; script-src '"self" https://cdn.graph.office.net'; style-src '"self" https://cdn.graph.office.net https://static2.sharepointonline.com'; object-src 'none'
>     - key: 'X-Frame-Options'
>       value: 'DENY'
>     - key: 'X-XSS-Protection'
>       value: '1; mode=block'
>     - key: 'Referrer-Policy'
>       value: 'same-origin'
> ```

I ran into similar issues, attempting to use multi-line yaml.  In my case I was specifying [folded `>`](https://yaml.org/spec/1.2/spec.html#id2796251) not [literal `|`](https://yaml.org/spec/1.2/spec.html#id2795688):

```yaml
applications:
  - appRoot: '$appRoot'
    customHeaders:
    - pattern: '**/*'
      headers:
        - key: Expect-CT
          value: enforce, max-age=30
        - key: Referrer-Policy
          value: strict-origin-when-cross-origin
        - key: Permissions-Policy
          value: fullscreen=(self)
        - key: X-Frame-Options
          value: DENY
        - key: X-Content-Type-Options
          value: nosniff
        - key: X-XSS-Protection
          value: 1; mode=block
        - key: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload
        - key: Content-Security-Policy
          value: >
            block-all-mixed-content;
            upgrade-insecure-requests;
            default-src 'self' blob:
...
```
   
And the deploy returned the following:
```log
    502 ERROR
    The request could not be satisfied.
    ---
    The Lambda function result failed validation. The header contains invalid characters. We can't
    connect to the server for this app or website at this time. There might be too much traffic or a
    configuration error. Try again later, or contact the app or website owner.
    If you provide content to customers through CloudFront, you can find steps to troubleshoot and
    help prevent this error by reviewing the CloudFront documentation.
    ---
    Generated by cloudfront (CloudFront)
    Request ID: FoDKwoABaYp-hTyFuH2oolvZleIWu_p2paBdVY477iPPFjqlTd4MFg==
```

So I ended up replacing the folded line with a single long line and it was successful.

**Comment by OscarJVD** [comment]
I've an authorization header but it doesn't works. In my nestjs ssr app
![image](https://user-images.githubusercontent.com/57403552/140617208-88bc3603-8417-47ca-9968-53b58cf2904c.png)

**Comment by davetroy** [comment]
Hi. I'm having a problem with custom headers also. My `customHttp.yml` is as follows:

```
customHeaders:
  - pattern: '/data/data.csv'
    headers:
      - key: Content-type
        value: text/csv
      - key: Content-disposition
        value: attachment;filename=data_data.csv
  - pattern: '/data/data.json'
    headers:
      - key: Content-type
        value: text/csv
      - key: Content-disposition
        value: attachment;filename=data_data.json
  ```
  
  These headers are simply not applied to the content.
