### ISSUE TITLE
Troubles escaping bash commands in amplify.yml

### ISSUE THREAD

**Issue by mattk-ce** [aws-amplify/amplify-console#1337]
**Describe the bug**
When using bash commands that require escaping, getting various errors...

**To Reproduce**
I have this `amplify.yml` configuration:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - bundle install
    build:
      commands:
        - bundle exec jekyll b
    postBuild:
      commands:
        - cd _site
        - "find $PWD -name \"*.html\" | while read line; do sed -Ei 's/href=\"([^\"]+)([^/]{1})\"/href=\"\\1\\2\\/\"/gI' $line; done"
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```

Running the build results in this message appearing in the console (and build failing):

```
/codebuild/output/src671305599/src/bulkdataapi-docs/amplify.sh: line 17: syntax error near unexpected token `('
/codebuild/output/src671305599/src/bulkdataapi-docs/amplify.sh: line 17: `echo "# Executing command: find $PWD -name "*.html" | while read line; do sed -Ei 's/href="([^"]+)([^/]{1})"/href="\1\2\/"/gI' $line; done"'
```
It almost looks like it's erroring on the `echo` that amplify added rather than the command itself...

**Additional context**
I'm wondering If I'm misunderstanding the appropriate way to escape things. I found zero documentation on what escape rules there are for amplify.yml, so I went ahead and assumed it was the same as [CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html) (surround entire command with double quotes, escape any internal double quotes).
