### ISSUE TITLE
Failed to compile with admin ui generated backend, unable to reproduce locally

### ISSUE THREAD

**Issue by lebull** [aws-amplify/amplify-console#1365]
```
# Starting phase: build
# Executing command: GA_MEASUREMENT_ID=UA-180292992
# Executing command: npm run build
2020-12-11T20:24:16.323Z [INFO]: > phasmophobiaquickgrid@0.1.0 build /codebuild/output/src991927049/src/PhasmophobiaQuickGrid
                                 > react-scripts build
2020-12-11T20:24:17.337Z [INFO]: Creating an optimized production build...
2020-12-11T20:24:21.580Z [INFO]: Failed to compile.
```

Build yml

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - GA_MEASUREMENT_ID=$GA_MEASUREMENT_ID
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

I am unable to reproduce this behavior locally (checked on multiple windows machines).  Works locally.

```
graphQL schema compiled successfully.

Edit your schema at C:\Users\bulld\Projects\PhasmophobiaQuickGrid\amplify\backend\api\EmfFive\schema.graphql or place .graphql files in a directory at C:\Users\bulld\Projects\PhasmophobiaQuickGrid\amplify\backend\api\EmfFive\schema
Successfully generated models. Generated models can be found in C:\Users\bulld\Projects\PhasmophobiaQuickGrid\src
? Do you plan on modifying this backend? Yes
√ Successfully pulled backend environment dev from the cloud.


Successfully pulled backend environment dev from the cloud.
Run 'amplify pull' to sync upstream changes.

PS C:\Users\bulld\Projects\PhasmophobiaQuickGrid> npm run build --prod

> phasmophobiaquickgrid@0.1.0 build C:\Users\bulld\Projects\PhasmophobiaQuickGrid
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  371.7 KB  build\static\js\2.551a64c8.chunk.js
  26.52 KB  build\static\css\main.d318a454.chunk.css
  7.06 KB   build\static\js\main.f9afd119.chunk.js
  782 B     build\static\js\runtime-main.15d6615a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

```

The same project builds and deploys fine without referencing the backend that I am trying to manage with the admin ui.  Here is the addition in my source, all pulled from the admin ui and untouched from there.

https://github.com/lebull/PhasmophobiaQuickGrid/compare/dev3...dev2?diff=unified

**Comment by swaminator** [comment]
@lebull: What's in your build settings?

**Comment by lebull** [comment]
> @lebull: What's in your build settings?

Sorry, added that to the original comment.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - GA_MEASUREMENT_ID=$GA_MEASUREMENT_ID
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by swaminator** [comment]
Update hthe build settings to add: https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#frontend-with-backend

**Comment by lebull** [comment]
That resolved it, thanks for your time.

**Comment by timalive** [comment]
I am getting a very similar issue, but adding the backend build to the amplify.yml file does not help.  I ampligy.yml file is as follows:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - REACT_APP_USER_POOL_ID=$REACT_APP_USER_POOL_ID
        - npm run build --verbose
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple

```

The last few lines of output in the build are:
```
2022-08-29T19:43:54.997Z [INFO]: Creating an optimized production build...
2022-08-29T19:44:04.327Z [INFO]: Failed to compile.
```

Any help would be appreciated!
