### ISSUE TITLE
Deploy gets stuck issue

### ISSUE THREAD

**Issue by Santhosh222** [aws-amplify/amplify-console#1380]
I am trying to deploy the strapi application using AWS Amplify. The deploy is getting struck after the command "npm start". In logs after this line "/bin/sh: hostname: command not found", the deploy is getting struck.

**App Details**:
**App Id**: arn:aws:amplify:us-east-1:190647250537:apps/dt801vbzq7wqs
PFA the build settings YML file and log file in zip file.

[Archive.zip](https://github.com/aws-amplify/amplify-console/files/5697328/Archive.zip)

**Comment by extheory** [comment]
Deploys are hanging for me too

**Comment by Santhosh222** [comment]
Just want to know, what is causing this error "/bin/sh: hostname: command not found". Anyone experienced this before in Amplify console?

**Comment by garyleefight** [comment]
What's the script for npm run start.  Can you share more info on your app? From the yml file you sent, the backend is not an amplify backend

**Comment by Santhosh222** [comment]
Thanks for the reply @garyleefight 

I am trying to deploy Strapi app which is an CMS app. For "npm run start", "strapi start" command runs and starts Strapi app at port 1337. The backend is not an amplify backend. I am just trying to start Strapi app. 

I also tried YML like this (keeping all commands in frontend) but it didn't work too.
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
    postBuild:
      commands:
        - npm start
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
