### ISSUE TITLE
Publish nextjs failed

### ISSUE THREAD

**Issue by jieliu218** [aws-amplify/amplify-console#1388]
**Describe the bug**
➜  nextjs git:(master) ✗ amplify publish
✔ Successfully pulled backend environment staging from the cloud.

Current Environment: staging

| Category | Resource name  | Operation | Provider plugin   |
| -------- | -------------- | --------- | ----------------- |
| Auth     | amplifytestjie | No Change | awscloudformation |
| Api      | amplifytestjie | No Change | awscloudformation |
| Hosting  | amplifyhosting | No Change | awscloudformation |

No changes detected
Publish started for amplifyhosting

> nextjs@0.1.0 build /Users/j.e.liu/Desktop/project/jie/amplify-jie/nextjs
> next build

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
info  - Generating static pages (2/2)
info  - Finalizing page optimization  

Page                                                           Size     First Load JS
┌ ○ /                                                          3.44 kB        65.8 kB
├   └ css/c39b4881d3c06665c5d4.css                             760 B
├   /_app                                                      0 B            62.4 kB
└ ○ /404                                                       3.44 kB        65.8 kB
+ First Load JS shared by all                                  62.4 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.7cd962.js  12.8 kB
  ├ chunks/framework.9116e7.js                                 41.8 kB
  ├ chunks/main.38b51b.js                                      6.54 kB
  ├ chunks/pages/_app.0536e9.js                                529 B
  ├ chunks/webpack.e06743.js                                   751 B
  └ css/2f26bb9842d84a608fa3.css                               202 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

✔ Zipping artifacts completed.
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Athena96** [comment]
Hi @jieliu218 currently, Amplify does not natively support deploying NextJS Apps, however it is on our roadmap for this year. 

In the meantime, here is a workaround for you (we will be updating our docs with this as well, but I wanted to provide it here to unblock you. Thanks!

-----


## Steps

1. Create a NextJS app (if you don't have one already)

2. Add an `amplify.yml` file to the top level of your apps directory, and add the following code. (replacing `<bucket-name>` with a unique bucket name)
```yml
version: 1

backend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - amplifyPush --simple
        - npm run build
        - aws s3 mb s3://<bucket-name>
        - aws s3 sync "s3://<bucket-name>/${USER_BRANCH}/.serverless" .serverless   # pull previous state
        - npx serverless                                                                  # generate new & deploy!
        - aws s3 sync .serverless "s3://<bucket-name>/${USER_BRANCH}/.serverless"   # push state to bucket
frontend:
  phases:
    build:
      commands:
        - echo "nextjs app, skipping"
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
3. Add a `serverless.yml` file with the following contents to the top level of your directory:
```yml
mynextjsapp:
  component: "@sls-next/serverless-component@1.17.0"
```
4. Initialize your Amplify app. In the top level of your app directory directory run the following (you need the [Amplify CLI to be installed](https://docs.amplify.aws/cli/start/install)): 
```shell
amplify init
# enter a name
# enter an environment name
# enter default editor
# enter `javascript`
# enter `react`
# enter `src`
# enter `build`
# enter `npm run-script build`
# *enter `npm run dev`
```
Now, select your AWS profile to deploy to and wait for the app to be created.

5. Commit your project to a repository.

6. Open your app in the AWS Amplify Console.
    - Select the "Front End" tab
    - Select the Repo provider you're useing and then "Connect Branch"
    - Continue throught the steps (ensure you attach a Backend Service role when configuring the backend env). Select 'Next'
    - Review the settings then click "Save and Deploy"
7. After your deploy completes
    - open the Backend build logs for your app.
    - scroll to the bottom and find the CloudFront distribution id that Serverless deployed and save it.
    

8. The final step is to add a Rewrite Rule to this Serverless CloudFront Distribution.
    - select your app in the Console
    - on the lefthand menu, select "Rewrites and Redirects"
    - click "Add rewrites and redirects"
    - setup a rewrite rule from your Amplify distro to the Serverless distro like so:
    ```
    Source Address: /<*>
    Target address: https://<distroID-of-serverless-distro>.cloudfront.net/<*>
    Type: 200 (Rewrite)
    Country Code:
    ```
9. And that's it! Now you can visit your Amplify App Distro and it will take you to your newly deployed NextJS App!
