### ISSUE TITLE
Source Repo value changes and deployments get stuck

### ISSUE THREAD

**Issue by SilverLinings89** [aws-amplify/amplify-console#1395]
**Describe the bug**
I'm not 100% sure these 2 are related, but I will describe them together. 
If I navigate to My App -> Frontend Environments -> Choose one 
I have 2 Issues: 
1. The repo does not seem to be detected correctly. It is hosted on Bitbucket and was properly configured during the app configuration some days ago. When I open the view, the URL shows correctly as https://bitbucket.org/projectname/reponame/src/dev (for example). Then I wait some seconds and it switches to https://bitbucket.org/undefined/src/dev and then, at some random time, it switches back.
2. The deployment basically always gets stuck - sometimes in weird states: 
![image](https://user-images.githubusercontent.com/35356122/102782872-567d2a00-439a-11eb-8ef2-55fc1629a6ee.png)
Sometimes it is stuck while provisioning. This morning I cancelled a run that had been stuck at "provisioning" (default AWS image) for 10 hours. Sometimes it gets stuck during deployment (Similar to what others wrote, the last log entry is "[INFO]: Updating Edge config").
The reason I mention this is, that it might be that there is some instability in the connection of the source code repo which might lead to failures down the line during the build.

**To Reproduce**
1. Go to 'App -> Frontend Environments -> Choose one'
2. Watch the value of source repository
3. If you see the value changing, check if the build follows the stages properly.

**Expected behavior**
The value of the source repo should always be the same. The stages should be performed in order. The build should not get stuck.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: project uses amplify 4.40. Angular App.

**Additional context**
We had basically the same build pipeline as a bitbucket pipeline and it worked.

**Comment by SilverLinings89** [comment]
This is our pipeline script: 
```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm || true
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist/Website
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yarn global add @lhci/cli@0.6.x
        - yarn global add puppeteer
    test:
      commands: 
        - yarn run utest
        - yarn run citest
    postTest:
      commands:
        - cd lighthouse
        - export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=$AWS_BRANCH
        - ./run_lighthouse.sh || true
        - cd ..
  artifacts:
    baseDirectory: ./test-results
    files:
      - junit.xml
```
