### ISSUE TITLE
Error when deploying through aws amplify console CI

### ISSUE THREAD

**Issue by incr3m** [aws-amplify/amplify-console#144]
We're currently getting the error below when deploying changes on amplify console ci:
![image](https://user-images.githubusercontent.com/3125784/65403889-9dcbe200-de08-11e9-9fa1-916fdf242371.png)
Current version we use is 3.8.0. We did not change any config on amplify ci console. It was working before,

**Comment by RossWilliams** [comment]
Hi, I've made a workaround for myself after guessing at the issue. It looks like the [amplifyPush.sh](https://gist.github.com/swaminator/7408de774e24ecf031d0d9928f1fbae5) command is failing because envCache has  "stackInfo" set to garbage. envCache is normally updated after running amplify commands, but the script fails before it can be updated to a good value, getting "stackInfo" stuck in the bad state, which won't be fixed by updated amplify-cli.

I've gotten around this by modifying my amplify.yml build steps to include
```yaml
backend:
  phases:
    build:
      commands:
        - envCache --set stackInfo ${STACKINFO}
        - amplifyPush --simple
```
where STACKINFO is a single-line json object set as an environment variable in the console. There used to be a button to press in the console to download this information, but I couldn't find it and needed to extract it from Cloudformation outputs.

I am still seeing the deploy issue as described in #143

**Comment by garyleefight** [comment]
@incr3m Can you give me your AppId. So that we can do more research on the bug. Thanks for @RossWilliams 's workaround. The STACK_INFO is messed up due to CLI bug. Anyone who meets this error can reset the stackInfo with the following setting
```yaml
backend:
  phases:
    build:
      commands:
        - envCache --set stackInfo ""
        - amplifyPush --simple
```
