### ISSUE TITLE
Custom headers are not applied to my app

### ISSUE THREAD

**Issue by vn425282** [aws-amplify/amplify-console#1454]
**Describe the bug**
I can not make the custom header applied to my app

**To Reproduce**
1. Go to 'AWS Amplify Console
2. Click on My App => App Settings: Custom headers

```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - key: X-Frame-Options
        value: SAMEORIGIN
      - key: X-XSS-Protection
        value: 1; mode=block
      - key: X-Content-Type-Options
        value: nosniff
      - key: Content-Security-Policy
        value: >-`
           default-src 'self'; worker-src 'self' blob:;
```
3. Nothing happen in my front-end :(

**Expected behavior**
Custom headers can applied to my app
