### ISSUE TITLE
$npm_package_version no longer works?

### ISSUE THREAD

**Issue by CodySwannGT** [aws-amplify/amplify-console#1472]
Hi there.

We have a number of Amplify apps and all of them set an environment variable called "REACT_APP_VERSION" to "$npm_package_version"

In all our previous apps, it works as intended in our code:

````
Version {process.env.REACT_APP_VERSION}
````

produces "Version 1.0.1" (or whatever)

However, on a newly deployed app, we're getting

"Version $npm_package_version"

**Comment by hsspain** [comment]
@CodySwannGT I am sorry you are having issues. Has anything changed in your build specification between the times it worked and when it didn't? Can you share that build spec?

**Comment by CodySwannGT** [comment]
Exact same build settings
````
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - cd react-client
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: /react-client/build
    discardPaths: true
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - react-client/node_modules/**/*
````

**Comment by CodySwannGT** [comment]
Any word on this?

**Comment by nbyodai** [comment]
I am also seeing this for my application. Please help address.

**Comment by r-moore** [comment]
Any news? This seems to be a regression?

**Comment by CodySwannGT** [comment]
Just started happening on another application. Any help is greatly appreciated

**Comment by CodyMoore240** [comment]
Any word on this. Just experienced this issue.

**Comment by r-moore** [comment]
I am going to open a support case via AWS console as there just seems to be tumbleweed here....

**Comment by kahdojay** [comment]
@CodySwannGT @r-moore @CodyMoore240 @nbyodai This looks to be related to the version of npm we're using:

https://github.com/npm/cli/issues/2731

We'll need to update the version we use in the default build container. As a workaround in the meantime, can you try updating npm as part of your build commands, for example:

```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm install npm@latest -g
...
```

Let us know if this doesn't work
