### ISSUE TITLE
`customHttp.yml` regex to avoid caching select objects

### ISSUE THREAD

**Issue by bryantbiggs** [aws-amplify/amplify-console#1511]
**Describe the bug**
- I am trying to exclude all JSON files from having the `Cache-Control` header be set to cache the files, but so far I have been unable to find the right combination of a `pattern` to do so

Ideally I would like to do this:
```yml
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'Strict-Transport-Security'
        value: 'max-age=63072000; includeSubDomains; preload'
      - key: 'X-Frame-Options'
        value: 'DENY'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'Cache-Control'
        value: 'public, max-age=86400, s-maxage=86400, immutable'
      - key: 'Referrer-Policy'
        value: 'same-origin'
  - pattern: '*.json'
    headers:
      - key: 'Cache-Control'
        value: 'max-age=0, s-maxage=0, no-store, no-cache'
```

I have tried numerous approaches with no luck, such as:
```yml
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'Strict-Transport-Security'
        value: 'max-age=63072000; includeSubDomains; preload'
      - key: 'X-Frame-Options'
        value: 'SAMEORIGIN'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'Referrer-Policy'
        value: 'same-origin'
  - pattern: '**/*.(js|css|.html|ico|gif|jpg|png|webp|svg|txt|woff|woff2|ttf|map|xml)$'
    headers:
      - key: 'Cache-Control'
        value: 'public, max-age=3600, s-maxage=3600, immutable'
  - pattern: '**/*.json$'
    headers:
      - key: 'Cache-Control'
        value: 'max-age=0, s-maxage=0, no-store, no-cache'
```

**Expected behavior**
- I would like to be able to set specific headers based on the `pattern` attribute; ideally adding a set of `default` headers to all assets, and then override where the pattern is more specific. However, I can also live with duplication - I just need to know how to be able to use the pattern because it does not follow normal regex (or so it appears)

**Comment by behrooziAWS** [comment]
Can you try this pattern for everything other than the json:

`'!**/*.json'`

and this pattern for the json:

`'**/*.json'`

**Comment by behrooziAWS** [comment]
Also your first example may work if you use **/*.json instead of *.json if your json files aren't all at your root.

```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'Strict-Transport-Security'
        value: 'max-age=63072000; includeSubDomains; preload'
      - key: 'X-Frame-Options'
        value: 'DENY'
      - key: 'X-Content-Type-Options'
        value: 'nosniff'
      - key: 'Cache-Control'
        value: 'public, max-age=86400, s-maxage=86400, immutable'
      - key: 'Referrer-Policy'
        value: 'same-origin'
  - pattern: '**/*.json'
    headers:
      - key: 'Cache-Control'
        value: 'max-age=0, s-maxage=0, no-store, no-cache'
```
