### ISSUE TITLE
Custom Access-Control-Allow Headers are not showing up

### ISSUE THREAD

**Issue by jachin** [aws-amplify/amplify-console#1563]
**Describe the bug**
I can not get my custom headers to show up.

I have tried several different things after my initial attempt failed:
 - In the build log I saw that having `customHeaders` in `amplify.yml` is deprecated so I moved them to `customHttp.yml` (the build found them and looks happy)
 - I thought maybe the order of the rules mattered, I tried putting the most "permissive" pattern at the bottom, that did not seem to help either.
 - I tried putting my `customHeaders.yml` in the web ui management console thing-y for Amplify too, no luck there either.

**To Reproduce**
1. Added customHeaders.yml
2. It looks something like:
    ```
    customHeaders:
    - pattern: '*.woff'
      headers:
        - key: 'Access-Control-Allow-Origin'
          value: 'https://www.mydomain.name'
        - key: 'Access-Control-Allow-Credentials'
          value: 'true'
        - key: 'Access-Control-Allow-Methods'
          value: 'GET, HEAD'
    - pattern: '*.woff2'
      headers:
        - key: 'Access-Control-Allow-Origin'
          value: 'https://www.mydomain.name'
        - key: 'Access-Control-Allow-Credentials'
          value: 'true'
        - key: 'Access-Control-Allow-Methods'
          value: 'GET, HEAD'
    - pattern: '**/*'
      headers:
        - key: 'X-Robots-Tag'
          value: 'noindex'
    ```

**Expected behavior**

For the woff and woff2 (font files) _have_ the custom headers, something like:

```
HTTP/2 200 OK
content-type: font/woff
content-length: 45516
last-modified: Fri, 12 Feb 2021 15:51:09 GMT
x-amz-server-side-encryption: AES256
accept-ranges: bytes
server: AmazonS3
x-robots-tag: noindex
Access-Control-Allow-Origin: https://www.mydomain.name
Access-Control-Allow-Methods: GET, HEAD
Access-Control-Allow-Credentials: true
date: Fri, 12 Feb 2021 20:06:13 GMT
etag: "82a9683860460a3aa1eadfc2e0180bc4"
x-cache: RefreshHit from cloudfront
via: 1.1 ac8301cb52f27894048b5f9019631931.cloudfront.net (CloudFront)
x-amz-cf-pop: MSP50-C2
x-amz-cf-id: YaST35fgSvBxnMXkARbJerHC1qPElCpDg75h349jGTYigWEiOG4vWw==
X-Firefox-Spdy: h2
```

But the responses are missing all the `Access-Control-Allow-*` headers
