### ISSUE TITLE
How do you install a different .NET SDK version

### ISSUE THREAD

**Issue by Swimburger** [aws-amplify/amplify-console#1571]
I'm using .NET 5 to develop a Blazor WebAssembly application and I want to deploy this to AWS Amplify.
I struggled to figure out how to do this but eventually ended up with these build steps:
```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
        - chmod +x *.sh
        - ./dotnet-install.sh -c 5.0 -InstallDir ./dotnet5
        - ./dotnet5/dotnet --version
    build:
      commands:
        - ./dotnet5/dotnet publish -c Release -o release
  artifacts:
    baseDirectory: /release/wwwroot
    files:
      - '**/*'
  cache:
    paths: []
```

I ended up installing the .NET 5 SDK in a subfolder and run the publish command using the dotnet CLI in that subfolder instead of using the dotnet SDK and CLI pre-installed on the build image. I had to do this because installing it without the -InstallDir argument would not work.
The dotnet SDK and CLI would remain the pre-installed version and publishing my Blazor WASM app requiring .NET 5 would not work.

My question is: how do I properly install a different version of the .NET SDK on the Amplify build machines?

FYI, this was my first attempt based on what I saw other people try in GitHub issues, but did not work:
```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
        - chmod +x *.sh
        - ./dotnet-install.sh -c 5.0
        - export PATH=$PATH:/root/.dotnet:/root/.dotnet/tools
        - export DOTNET_ROOT="/root/.dotnet"
        - dotnet --version
    build:
      commands:
        - dotnet publish -c Release -o release
  artifacts:
    baseDirectory: /release/wwwroot
    files:
      - '**/*'
  cache:
    paths: [] 
```
