### ISSUE TITLE
Bug in amplifyPush makes social login all-or-nothing

### ISSUE THREAD

**Issue by davad** [aws-amplify/amplify-console#1573]
From [the documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#creating-a-new-backend-environment-with-authentication-parameters), I expect to be able to set env variables to drive one or more of the social login options.

I ran into a bug with a site where I'm using Google and Facebook auth, but not Amazon. Amplify Console gave this error:
```
auth headless is missing the following inputParams googleClientId, facebookAppId
```

From [this line](https://github.com/aws-amplify/amplify-console/blob/0ddee82988d7702fd343f39249495ff811ba955f/scripts/amplifyPush.sh#L101) it looks like you have to have ClientIds set for all three to fix the problem. However, when I set a bogus `AMPLIFY_AMAZON_CLIENT_ID`, that didn't fix my problem.

This is what my amplify.yml looks like (pushing only a backend with this app):
```
version: 1
backend:
    phases:
        build:
            commands:
                - "# Execute Amplify CLI with the helper script"
                - amplifyPush --simple
```

Using a [this custom build image](https://github.com/davad/amplify-yarn-latest/blob/master/Dockerfile) as a workaround for a problem we had using the latest Yarn. Note that even though the Dockerfile installs Amplify ^4.41.2, at build-time Amplify Console is updating it to 4.43.0.

Is there a way I can get this to work with `amplifyPush --simple`? Is this a bug with the `amplifyPush` script?

**Comment by vic-blt** [comment]
> From [the documentation](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#creating-a-new-backend-environment-with-authentication-parameters), I expect to be able to set env variables to drive one or more of the social login options.
> 
> I ran into a bug with a site where I'm using Google and Facebook auth, but not Amazon. Amplify Console gave this error:
> ```
> auth headless is missing the following inputParams googleClientId, facebookAppId
> ```
> 
> From [this line](https://github.com/aws-amplify/amplify-console/blob/0ddee82988d7702fd343f39249495ff811ba955f/scripts/amplifyPush.sh#L101) it looks like you have to have ClientIds set for all three to fix the problem. However, when I set a bogus `AMPLIFY_AMAZON_CLIENT_ID`, that didn't fix my problem.

Setting `AMPLIFY_AMAZON_CLIENT_ID` is not mandatory.
Which env variables did you define ?
I can tell from the error log that `AMPLIFY_GOOGLE_CLIENT_ID` and `AMPLIFY_FACEBOOK_CLIENT_ID` are missing.

> This is what my amplify.yml looks like (pushing only a backend with this app):
> ```
> version: 1
> backend:
>     phases:
>         build:
>             commands:
>                 - "# Execute Amplify CLI with the helper script"
>                 - amplifyPush --simple
> ```
> 
> Using a [this custom build image](https://github.com/davad/amplify-yarn-latest/blob/master/Dockerfile) as a workaround for a problem we had using the latest Yarn. Note that even though the Dockerfile installs Amplify ^4.41.2, at build-time Amplify Console is updating it to 4.43.0.
> 
> Is there a way I can get this to work with `amplifyPush --simple`? Is this a bug with the `amplifyPush` script?

If you encounter problems with amplify-cli, try to set the version to "latest" in the amplify build tab.

**Comment by davad** [comment]
@vic-blt 
Here's what my environmental variables are right now. `AMPLIFY_AMAZON_CLIENT_ID` is a bogus value, but the other aren't.

![Screenshot from 2021-02-16 9-39-30](https://user-images.githubusercontent.com/190387/108077956-1bfed900-703b-11eb-93be-da51efb3f5d8.png)

And amplify-cli is already set to latest. That's why it was updated to 4.43 at build-time.

**Comment by vic-blt** [comment]
Here's my env variables

![env_vars](https://user-images.githubusercontent.com/48869999/108085005-26d65f80-7075-11eb-9703-20869a1a4c68.png)

Try to add variables related to Cognito, it should work.

**Comment by davad** [comment]
Weird. I'll try that. I wouldn't think I _should_ have to specify the Cognito variables, since that's being defined in code by this Amplify Console application.

**Comment by vic-blt** [comment]
FYI, I just succeeded deploying an amplify app with framework set to "React - Amplify".
It means that it's detected as a fullstack app, so you don't have to specify facebook or google env variables.
It also enables to select a default backend for **branches autodetection** and **previews**.
See my comment https://github.com/aws-amplify/amplify-console/issues/448#issuecomment-781233282

**Comment by davad** [comment]
@vic-blt I had to set this aside for a bit, but I just tried adding those four variables, and I'm still getting my original error message.

**Comment by davad** [comment]
For anyone getting here via Google, @amplify/cli v4.46.0 solved this problem. With that build, I had errors like this before adjusting my amplify.yml.

The log below is from an amplify.yml without a `frontend` key at all.

```
2021-03-23T00:05:18.156Z [INFO]: # Completed phase: build
2021-03-23T00:05:18.157Z [INFO]: ## Build completed successfully
2021-03-23T00:05:18.158Z [INFO]: # Starting caching...
2021-03-23T00:05:18.158Z [WARNING]: !TypeError: Cannot read property 'cache' of undefined
2021-03-23T00:05:18.165Z [INFO]: No custom headers found.
2021-03-23T00:05:18.167Z [ERROR]: !!! TypeError: Cannot read property 'artifacts' of undefined
2021-03-23T00:05:18.167Z [INFO]: # Starting environment caching...
2021-03-23T00:05:18.169Z [INFO]: # Environment caching completed
```

I fixed this by changing my `amplify.yml` from this:
```
version: 1
backend:
    phases:
        build:
            commands:
                - "# Execute Amplify CLI with the helper script"
                - amplifyPush --simple
 ```

To this:

```
version: 1
backend:
    phases:
        build:
            commands:
                - "# Execute Amplify CLI with the helper script"
                - amplifyPush --simple
    artifacts:
    cache:
frontend:
    phases:
      commands:
        build:
          - amplify -v
    artifacts:
      baseDirectory: public
    cache:
      paths:
```
