### ISSUE TITLE
ENV VERSION_AMPLIFY=1.7.2

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-console#159]
When I look at the Provision log I see 

`ENV VERSION_AMPLIFY=1.7.2`

Is that really the version of amplify the build is using?

I'm currently using amplify.yml with the following:
```
backend:
  phases:
    preBuild:
      commands:
        - npm i -g @aws-amplify/cli@3.0.0
[...]
```

and I'd like to remove it and just use the latest version of amplify cli.
