### ISSUE TITLE
Missing resources when deploying using CDK

### ISSUE THREAD

**Issue by cornelcroi** [aws-amplify/amplify-console#1600]
**Describe the bug**
When deploying with CDK  (using the buildspec described here https://docs.aws.amazon.com/cdk/api/latest/docs/aws-amplify-readme.html) the deployment package does not have all the static files (some js files are missing).
There is no error on the build console.

**To Reproduce**
Deploy an app using CDK: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-amplify-readme.html

**Expected behavior**
Able to see the static application deployed 

**Screenshots**
The verify screenshots are not rendering the app like expected due to the missing resources.

**Additional context**
After deployment, if I go and replace manually the buildspec generated by CDK by pasting it the one generated by AmplifyConsole (if I try to to deploy the same app using the AWS Console), after a new deployment, it works.

Here below the generated buildspec by CDK:
```
{
  "version": "1.0",
  "frontend": {
    "phases": {
      "preBuild": {
        "commands": [
          "yarn install"
        ]
      },
      "build": {
        "commands": [
          "yarn run build"
        ]
      }
    },
    "artifacts": {
      "baseDirectory": "build",
      "files": "**/*"
    },
    "cache": {
      "paths": "node_modules/**/*"
    }
  }
}
```

Here below the generated buildspec by Amplify Console

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
