### ISSUE TITLE
Amplify console stuck with any information

### ISSUE THREAD

**Issue by mauriciorj** [aws-amplify/amplify-console#1618]
After I have connected my bitbucket `develop` branch and push around 5 commits, it's not working anymore and not showing any information.

I already tried:
 - Disconnect and connect the branch again;
 - Push a new commit;
 - Cancel and redeploy;

my ARN -> arn:aws:amplify:us-east-2:016534437021:apps/d21yu3e858rc9b

My build settings:
```version: 1
applications:
    backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: out
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: client
```

![Screen Shot 2021-03-01 at 8 21 50 PM](https://user-images.githubusercontent.com/2256264/109582575-63ba4180-7acc-11eb-9480-1ef7eede2369.png)

**Comment by nimacks** [comment]
It looks like you have Pull request previews enabled which triggered 8 consecutive builds.  Currently we only support 5 concurrent builds per our documentation https://docs.aws.amazon.com/general/latest/gr/amplify.html. However , this should not have affected your build. 

Can you turn make a commit directly to the develop branch to trigger a new build while we investigate this further on our end?

**Comment by mauriciorj** [comment]
Sure!
Commit `cdeb9aa` pushed directly to `development` branch!

**Comment by nimacks** [comment]
Per this documentation https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration

There needs to be a `-` in front of `frontend` and `backend`.  Also check to make sure you have the right indentations.

```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    test:
      artifacts:
        baseDirectory: cypress
        configFilePath: '**/mochawesome.json'
        files:
          - '**/*.png'
          - '**/*.mp4'
      phases:
        preTest:
          commands:
            - npm ci
            - npm install wait-on
            - npm install pm2
            - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
            - npx pm2 start npm -- start
            - 'npx wait-on http://localhost:3000'
        test:
          commands:
            - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
        postTest:
          commands:
            - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
            - npx pm2 kill
    appRoot: rea

```

**Comment by mauriciorj** [comment]
Worked! I updated the `Building Settings` to:

```
version: 1
applications:
  - appRoot: client
    backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn build
      artifacts:
        baseDirectory: out
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
 ```
