### ISSUE TITLE
amplify.yml can't eval ssh-agent to add ssh key

### ISSUE THREAD

**Issue by chartspanBuild** [aws-amplify/amplify-console#1639]
**Describe the bug**
I am attempting to add an ssh key so that other git repos can be cloned in my Amplify build process. The very fist command in my build process is `eval "$(ssh-agent -s)"` and once this command is run the whole build process hangs and no other output is ever output in the the build phase that can be viewed in Amplify console. The build hangs and eventually times out. The only output in the Backend build is:
```
                                 # Starting phase: build
```
Is the 'eval' command no longer able to be run on the build containers?

My amplify.yml looks like:
```
version: 1
backend:
  phases:
    build:
      commands:
        - eval "$(ssh-agent -s)"
        - ssh-add <(echo "$DEPLOYMENT_KEY" | base64 -d)
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands: []
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

This is something that it looks like others widely use and rely on as see here:

- https://github.com/aws-amplify/amplify-console/issues/150#issuecomment-545982853
- https://forums.aws.amazon.com/message.jspa?messageID=924092#924092
- https://sapanbodiwala.com/blog/deploying-to-aws-amplify

**To Reproduce**
Set the value of an Amplify Console env variable named "DEPLOYMENT_KEY" to the value of a base64 encoded private ssh key.
Kick of an Amplify Console deployment / build using the above amplify.yml build settings.

**Expected behavior**
Build does not hang and can clone other github repos as part of the build

**Additional context**
Amplify CLI version being used by Amplify Console:
```
2021-03-10T18:05:40.945Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-03-10T18:05:46.970Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.45.0...
2021-03-10T18:06:43.431Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
```
