### ISSUE TITLE
Exclude Root from Cloud Formation

### ISSUE THREAD

**Issue by oakstreetrec** [aws-amplify/amplify-console#169]
**Please describe which feature you have a question about?** 

I'm trying to write the correct CF YAML to use only a subdomain of a root domain that will not be part of my project. I would like to do it from CF if possible, but I don't see how to set 'exclude root' as is possible in the Add Domain UI. Won't the following set up both example.com and mySub.example.com (and possibly www.example.com as well)? I just want to grab mySub.example.com.

 **Provide additional details**

```
  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: example.com
      SubDomainSettings:
        - Prefix: mySub
          BranchName: master

```

**Comment by garyleefight** [comment]
Hi, your template is the right template that excludes root domain. If you want to include root domain,
your template should be like :
```yaml
AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      DomainName: example.com
      SubDomainSettings:
        - Prefix: ''
          BranchName: master
        - Prefix: mySub
           BranchName: master
```
