### ISSUE TITLE
Successful build never proceeds to test/deploy phase

### ISSUE THREAD

**Issue by iba-1** [aws-amplify/amplify-console#1698]
**Describe the bug**
Gatsby build phase is successful as seen from logs but it never proceed to test or deploy phase

**To Reproduce**
1. Push an empty commit or manually trigger a new build on our repo: github.com/disabiliabili/disabiliabili-blog

**Expected behavior**
A successful build phase should proceed to test phase and deploy phase

**Screenshots**
![image](https://user-images.githubusercontent.com/16140797/112508558-f2e70c00-8d8f-11eb-85bb-07199b5f76c8.png)

**Additional context**
I'm attaching every configuration that may help you:
Build log output:
[log_build_output.txt](https://github.com/aws-amplify/amplify-console/files/6206340/log_build_output.txt)

Build configuration:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14
        - nvm use 14
        - yarn install
    build:
      commands:
        - nvm use 14
        - yarn run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Our app id: d9xmy2a8vj50s
Our ARN: arn:aws:amplify:eu-central-1:941766984611:apps/d9xmy2a8vj50s

We already increased max timeout to 45m thinking it was that that made the build fail, turns out the build seems to end successfully but amplify just hangs until timeout limit is reached.
Plus, o errors are shown in the logs at this time.

A side note: we've used Gatsby Cloud in the past, with this very same repo, and it is and was building successfully in about 25min, this makes me think it shouldn't be a code related issue.
