### ISSUE TITLE
Can not deploy new app that points to backend of different app

### ISSUE THREAD

**Issue by ACI-joe** [aws-amplify/amplify-console#1707]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

When attempting to deploy a new app through the Amplify Console, using CI/CD, and a repository that was manually deployed previously through the Amplify CLI, the backend build fails.  

### Expected behavior

The new app deployment should reference the existing backend environment of the previously deployed app. 

### Reproduction steps

1. Using Amplify Console, select 'New app' - then 'Host web app'
2. Select GitHub
3. Select Continue
4. Select repository
5. Select main branch
6. Select 'Next'
7. Update build settings
	1. baseDirectory: /dist
8. Select 'Next'

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /dist
    files:
      - '**/*'
```

Worked with Nikhil Swaminathan during this attempt.  We were advised to file this as a bug report as a result of this test.  Attached is the build log from attempt.  

The original application was deployed about a year ago through Amplify CLI.  We are looking to migrate the app to CI/CD, but that is not switchable post manual deploy.  This new app deployment was an attempt to work around that.

[build-log_20210329_2048.txt](https://github.com/aws-amplify/amplify-console/files/6224705/build-log_20210329_2048.txt)
