### ISSUE TITLE
Pushing a hotfix to master, resulted in no diff detected, and no build released

### ISSUE THREAD

**Issue by axtonpitt** [aws-amplify/amplify-console#1708]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

After merging a hot fix branch into the master branch, there was no diff detected (even though there was).

### Expected behavior

Pushing a hot fix to the main branch would trigger a deployment

### Reproduction steps

Push a change to master.

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - yarn
        build:
          commands:
            - if [ "${AWS_BRANCH}" = "master" ]; then yarn build:prod; fi
            - if ! [ "${AWS_BRANCH}" = "master" ]; then yarn build:dev; fi
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: client
```

<img width="1440" alt="Screen Shot 2021-03-29 at 8 21 42 AM" src="https://user-images.githubusercontent.com/8604082/112924546-d0c50380-916c-11eb-803b-5d7ef51ecc93.png">
