### ISSUE TITLE
Deploy fails with "[ERROR]: Failed to deploy

### ISSUE THREAD

**Issue by StevieV1903** [aws-amplify/amplify-console#1726]
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

2021-04-06T14:52:45 [INFO]: Starting Deployment
2021-04-06T14:52:45 [ERROR]: Failed to deploy

I was working through the aws amplify (react app) tutorial (https://aws.amazon.com/getting-started/hands-on/build-react-app-amplify-graphql/module-three/?e=gs2020&p=build-a-react-app-two)
The app works as expected locally, with the authentication element added to the application.
When I tried to deploy the changes to the live environment I started to encounter a number of problems. Firstly I had an issue with the build process and manually updated the Amplify CLI version. Then I had an issue with no service role, so I created a new role and added this to my app. Now the build process completes, however the app fails with the above error, without any explanation as to what is causing it to break. I am quite new to this, so any help to resolve this would be much appreciated. Let me know if you need any more information? 

### Expected behavior

I feel that the application should now deploy to the live environment, but not sure why this is not working?

### Reproduction steps

The bug is triggered with I try to deploy changes to the live environment. After the build process is successful, it proceeds into deployment and shows the error.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by siegerts** [comment]
Hi @StevieV1903 , thanks for raising. Unfortunately, I'm not able to reproduce with your above build settings.

I went through the tutorial up to the deploy auth.

- Created the service role and associated it with the new backend
- Adjusted the build settings by adding:
  - **Build Settings** -> **Build image settings** -> **Live package updates** -> **Amplify CLI** -> **latest**

Tested with your settings above and the config below - 

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'

```

Both deployed successfully but that is not to say that something isn't behaving as expected on your end.  Are there any other changes that you may have made?
