### ISSUE TITLE
Build failed with "Could not find a schema at[..]"

### ISSUE THREAD

**Issue by andre-scheffer** [aws-amplify/amplify-console#1744]
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

- I created a complete new app via the amplify cli
- I pushed everything successfully
- I connected a GitHub-Repository to deploy all my changes incl. the backend

During the build I run into an error:

![image](https://user-images.githubusercontent.com/48789566/114617895-fd1e6b00-9ca8-11eb-8d77-63f89c72a5d5.png)

This is the log:

2021-04-13T19:42:12.968Z [INFO]: [0mError: Could not find a schema at /codebuild/output/srcXXXXXX/src/XXXXXX/amplify/backend/api/XXXXXXX/schema.graphql[0m
                                 [0m    at readSchema (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/transformConfig.ts:268:11)[0m
                                 [0m    at Object.loadProject (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/graphql-transformer-core/src/util/transformConfig.ts:165:18)[0m
                                 [0m    at Object.transformGraphQLSchema (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/transform-graphql-schema.ts:460:19)[0m
                                 [0m    at Object.run (/root/.nvm/versions/node/v12.21.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/push-resources.ts:109:5)[0m
2021-04-13T19:42:13.006Z [ERROR]: !!! Build failed
2021-04-13T19:42:13.006Z [ERROR]: !!! Non-Zero Exit Code detected
2021-04-13T19:42:13.007Z [INFO]: # Starting environment caching...
2021-04-13T19:42:13.007Z [INFO]: # Environment caching completed
Terminating logging...

### Expected behavior

The build should work because the amplify push operation does.

### Reproduction steps

Pls, see the section "Describe the bug"

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

It's not related to #1489 because my schema is commited to GitHub.

It's not related to #1186 because I don't have multiple schema files:
![image](https://user-images.githubusercontent.com/48789566/114618693-f04e4700-9ca9-11eb-993b-1259b5aac7e1.png)
