### ISSUE TITLE
Can't enable PR previews in a monorepo

### ISSUE THREAD

**Issue by halimb** [aws-amplify/amplify-console#1755]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

I'm moving two separate SPAs to a monorepo.

I followed the steps listed in [the monorepo setting tutorial](https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/)

Then tried enabling PR previews by following these steps in [the branch preview tutorial](https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html)
However, after enabling the previews in Github for my private monorepo, then going back to the previews config page in one of the apps, it still shows that previews are disabled.

### Expected behavior

Previews should be enabled after Installing the github app and enabling the preview for the monorepo github repository 

### Reproduction steps

1. follow the steps in [the monorepo setting tutorial](https://aws.amazon.com/blogs/mobile/set-up-continuous-deployment-and-hosting-for-a-monorepo-with-aws-amplify-console/)
2. Try enabling the previews on one of the apps, by following the steps in [the branch preview tutorial](https://docs.aws.amazon.com/amplify/latest/userguide/pr-previews.html)

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --ignore-engines
    build:
      commands:
        - yarn generate --ignore-engines
  artifacts:
    baseDirectory: /dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - "**/*.png"
      - "**/*.mp4"
  phases:
    preTest:
      commands:
        - if [ "${AWS_BRANCH}" != "master" ]; then exit 0; fi
        - function run_test_command { if [ "${CYPRESS_ENABLED}" == 1 ]; then $@; else true; fi; };
        - run_test_command 'yarn install'
        - run_test_command 'yarn add cypress'
        - run_test_command 'yarn global add wait-on http-server pm2'
        - run_test_command 'pm2 start "http-server dist/ -p 3000"'
        - run_test_command 'npx wait-on http://localhost:3000'
    test:
      commands:
        - if [ "${AWS_BRANCH}" != "master" ]; then exit 0; fi
        - run_test_command "npx cypress run --record --key $CYPRESS_RECORD_KEY --spec 'cypress/integration/auth/*'"
```
