### ISSUE TITLE
Amplify Console: How to skip checking back-end environments were changed?

### ISSUE THREAD

**Issue by Kunie-dev** [aws-amplify/amplify-console#177]
Amplify Console: How to skip checking back-end environments were changed?

It was spent a lots of times that deployment pipelines.
We want to skip that manually when we knew what back-end environments were not changed.
+ Does It have only the option '--simple'  from the command 'amplifyPush' of amplify.yml?

**Comment by swaminator** [comment]
@Kunie-dev if your backend env hasn't changed, the amplifyPush --simple script should not be spending more than 5 seconds on it. Are you seeing longer times?

**Comment by Kunie-dev** [comment]
It took 1m 15s while processing the step 'backend' only on build stage.

**Comment by swaminator** [comment]
Can you please share your appid? Found in App settings > general

**Comment by Kunie-dev** [comment]
App ARN
arn:aws:amplify:ap-northeast-2:929259052518:apps/d3ulhf1lq0mnhv

**Comment by thedgbrt** [comment]
@swaminator I've used the console extensively for months, and I always have a minimum of 2min backend build times, even though I almost never make changes to it. Any idea why?

**Comment by mansiva** [comment]
+1

**Comment by michaelbrewer** [comment]
+1 some issue

**Comment by ganeshp0001** [comment]
I managed to ignored Backend check & push by adding following setting to build: Amplify.yml

```
version: 1
backend:
  phases:
    build:
      commands:
        - echo "********* IGNORE BACKEND CHECK/PUSH **********"
frontend:
  phases:
    preBuild:
    ..........
    ..........
    ..........
```
