### ISSUE TITLE
Cannot read property 'paths' of undefined changing to compile typescript in CI

### ISSUE THREAD

**Issue by arealmaas** [aws-amplify/amplify-console#1773]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

We use Typescript for our lambda functions which we until now have compiled in pre-push hooks before pushing to origin. All our builds/deployments are handled on the Amplify CI so we wanted to move the compilation of Typescript to the CI as well so we don't have to keep compiled js-files in the repo. 

Our amplify.yml looked like this: 

```yaml
version: 1
backend:
    phases:
        build:
            commands:
                - amplifyPush --simple
frontend:
    artifacts:
        baseDirectory: ./
        files:
            - "index.html"

```

For Amplify to be able to push we need to compile typescript before we run `amplifyPush` so we changed it to:

```yaml
version: 1
backend:
    phases:
        preBuild:
            commands:
                - npm ci
                - npm run compile-typescript
        build:
            commands:
                - amplifyPush --simple
frontend:
    artifacts:
        baseDirectory: ./
        files:
            - "index.html"
test:
    phases:
        preTest:
            commands:
                - npm ci
        test:
            commands:
                - npm test
```
The build seems to go through but it fails when starting the caching step with the following error:
```
2021-04-26T16:27:07.507Z [INFO]: # Completed phase: build 2021-04-26T16:27:07.507Z [INFO]: ## Build completed successfully 2021-04-26T16:27:07.509Z [INFO]: # Starting caching... 2021-04-26T16:27:07.510Z [WARNING]: !TypeError: Cannot read property 'paths' of undefined

```

We have a package.json on root with typescript and use that to compile the TS in the functions. Any idea about what the issue could be?

### Expected behavior

To successfully build

### Reproduction steps

1. Install typescript in the root of the repo
2. Add the amplify.yml shown in the description above. 
3. Connect the branch and see the build fail
