### ISSUE TITLE
Monorepo project with several Hugo sites 

### ISSUE THREAD

**Issue by nsollecito** [aws-amplify/amplify-console#1779]
**Please describe which feature you have a question about?**

We're trying to configure Amplify to deploy an existing monorepo with multiple Hugo websites defined in folders by year. In the root of the project folder, I have `amplify.yml` defined and within the same folder, there are folders for each year such as 2019, 2020, 2021, etc. 

Within the build stage, after the repo is checked out for the appRoot of 2021, we are getting the following error:

```
2021-04-27T19:56:19.763Z [INFO]: # Extraction completed
2021-04-27T19:56:19.763Z [INFO]: # Retrieving environment cache...
2021-04-27T19:56:19.802Z [INFO]: # Retrieved environment cache
2021-04-27T19:56:19.858Z [ERROR]: !!! TypeError: undefined is not a function
2021-04-27T19:56:19.859Z [INFO]: # Starting environment caching...
2021-04-27T19:56:19.859Z [INFO]: # Environment caching completed
```
We've paired down the yaml as much as possible to isolate the issue here and haven't been able to make much progress. This error isn't particularly helpful. 

**Provide additional details**

ProjectId is d259rcaqqq7tw2

**What AWS Services are you utilizing?**

Amplify Console

**Provide additional details e.g. code snippets**

Current amplify.yml file looks like this:

```
version: 1
applications:
  - appRoot: 2021
    frontend:
      phases:
        preBuild:
          commands:
            - cd 2021
            - curl -OL https://golang.org/dl/go1.15.7.linux-amd64.tar.gz
            - tar -C /usr/local -xzf ./go1.15.7.linux-amd64.tar.gz
            - yarn install --freeze-lockfile
        build:
          commands:
            - PATH=$PATH:/usr/local/go/bin
            - yarn build:amplify
      artifacts:
        baseDirectory: dist
        files:
            - '**/*'
      cache:
        paths:
          - node_modules/**/*
```
