### ISSUE TITLE
Storage headless is missing the following inputParams tables, region

### ISSUE THREAD

**Issue by samgates3** [aws-amplify/amplify-console#1782]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

2021-04-28T13:44:54.867Z [WARNING]: ✖ There was an error initializing your environment.
2021-04-28T13:44:54.870Z [INFO]: [31mFailed to pull the backend.[39m
2021-04-28T13:44:54.871Z [INFO]: [31mstorage headless is missing the following inputParams tables, region[39m
2021-04-28T13:44:54.875Z [INFO]: [0mError: storage headless is missing the following inputParams tables, region[0m

I have tried playing with environment variables as seen in other posts, however that doesn't change anything.

### Expected behavior

Expected build to occur successfully.

### Reproduction steps

1. amplify add storage
2. amplify add api
3. amplify push
4. Commit project to repo for Automatic build
5. build fails

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
