### ISSUE TITLE
Deployments failing with no error message

### ISSUE THREAD

**Issue by amirhajimirsadeghi** [aws-amplify/amplify-console#1784]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

This is the only message I see in my deployment step:

```
2021-04-28T23:05:35 [INFO]: Starting Deployment
2021-04-28T23:05:35 [ERROR]: Failed to deploy
```

This is happening for my qa and prod environments. I tried disconnecting the branch and reconnecting, deploying old version, redploying. It just keeps getting to the deployment stage and not giving me any info. Just failinh

### Expected behavior

To either deploy the app successfully or give a more descriptive message

### Reproduction steps

1. Go to my amplify application
2. Click redeploy this version

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build:$USER_BRANCH
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
```
