### ISSUE TITLE
Add private key asks for passphrase when it shouldn't

### ISSUE THREAD

**Issue by kalinchuk** [aws-amplify/amplify-console#182]
**Describe the bug**
In the build steps, I run a command to add a private key (`ssh-add KEY`) to pull a private repo but it asks for a passphrase which stops the build process. The key does not have a passphrase so it shouldn't be asking for me.

**To Reproduce**

1. Set the private key as an environment variable.
2. Configure the build with the following:

```
frontend:
  phases:
    preBuild:
      commands:
        - eval "$(ssh-agent -s)"
        - ssh-add - <<< "${SSH_PRIVATE_KEY}"
```

**Expected behavior**
It should add the key to the SSH agent.

**Additional context**
The key is needed to pull a private Github package. Is there any other way to do this?
