### ISSUE TITLE
Failing tests don't prevent deploy

### ISSUE THREAD

**Issue by mattraibert** [aws-amplify/amplify-console#1821]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d30vzhpnevtahx

### Region

us-east-1

### Amplify Console feature

E2E tests

### Describe the bug

Failing tests don't prevent deploy. The pipeline indicator also does not display a failed test.

The so-called cypress results table registers the failing test, but the pipeline does not and the app deploys.

<img width="1120" alt="Screen Shot 2021-05-10 at 4 51 34 PM" src="https://user-images.githubusercontent.com/279628/117723226-2353ff80-b1b0-11eb-953d-f87f917a28b7.png">

See this PR for a fix: https://github.com/positiondev/amplify-test-issues/pull/1

### Expected behavior

We expect the failing tests to show a big red X and prevent the workflow from continuing to the "Deploy" phase.

### Reproduction steps

1. Push a broken test to github.
2. Check the pipeline and see that it deploys.

### Build Settings

```yaml
We provided the following test config in our `amplify.yml`

test:
  artifacts:
    baseDirectory: test-results
    configFilePath: "**/mochawesome.json"
  phases:
    preTest:
      commands:
        - yarn install
    test:
      commands:
        - 'yarn run mocha --reporter mochawesome --reporter-options "reportDir=test-results/report,overwrite=true,html=false,json=true"'
```

### Additional information

Adding the dummy `postTest` section below fixes the issue:

```yaml
test:
  artifacts:
    baseDirectory: test-results
    configFilePath: "**/mochawesome.json"
  phases:
    preTest:
      commands:
        - yarn install
    test:
      commands:
        - 'yarn run mocha --reporter mochawesome --reporter-options "reportDir=test-results/report,overwrite=true,html=false,json=true"'
    postTest:
      commands:
        - echo "force amplify to check for test failures"
```

**Comment by nimacks** [comment]
@mattraibert, the standard auto-generated build spec includes the following commands 
```
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:3000'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill
```

and the postTest section is required in order for tests to run correctly and properly stop a build when failed tests are encountered. 
https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html
