### ISSUE TITLE
App intermittently returning 429 error

### ISSUE THREAD

**Issue by GooBall** [aws-amplify/amplify-console#1823]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

eu-west-1

### Amplify Console feature

Logging, Performance

### Describe the bug

Recently a staging environment I run that simply builds and serves a `create-react-app` has been intermittently returning a `429` code and I'm very confused as to what might be going wrong. It will be fine and then out of nowhere on a page load, the browser will return a `429` error.

The 429s returned that my colleges and I see will show up in the access log with a `cs-uri-stem` of `/` and a `cs\(Referer)` of `-`.

But then things get even odder when I look at the 4xx errors via the monitoring console. It seems that there is a continuous stream of errors coming in (an average of 100 every data point) but none of these show in the access log.
![image](https://user-images.githubusercontent.com/5050301/117879114-7ad09900-b29e-11eb-94f0-3fd805369046.png)

The final thing confusing me is that we have access protection enabled for all builds in this app so I don't understand how something could even be accessing any of the builds. I have changed the access protection credentials just to be sure, it hasn't had an impact.

### Expected behavior

I don't expect to be seeing any `429` errors when accessing an amplify app. 
I also would expect to see all 4xx errors in the access log.

### Reproduction steps

1. Go to one of the URLs or preview URLs.
2. Sometimes see a 429 error returned by the browser.

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build:staging
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: ui
```
