### ISSUE TITLE
Build fails with "Starting SSR Build..."

### ISSUE THREAD

**Issue by tjto** [aws-amplify/amplify-console#1824]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3srkgpabkig16

### Region

eu-central-1

### Amplify Console feature

Build settings

### Describe the bug

Starting from 11 May 2021, with no changes in our code or build configuration, all of our builds have started failing with
```
Starting SSR Build...
AccessDenied
```

### Expected behavior

Build should be successful since no change 

### Reproduction steps

Just re-run the pipeline

### Build Settings

```yaml
BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - next build && next export
          artifacts:
            baseDirectory: out
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
```
