### ISSUE TITLE
Unable to enable Admin UI

### ISSUE THREAD

**Issue by ashleyoldershaw** [aws-amplify/amplify-console#1827]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2xxwcl6ly3wga

### Region

eu-west-2

### Amplify Console feature

Not applicable

### Describe the bug

I have a StackOverflow question open here:
https://stackoverflow.com/questions/67504106/unable-to-enable-aws-amplify-admin-ui

In short - I'm clicking the switch to enable Admin UI but it's not enabling it despite telling me that it is. It's happening in both of my Amplify projects leading me to think it's not a problem with my app's setup.

### Expected behavior

Click the enable switch -> wait a bit for it to enable -> console tells me it's enabled -> I can click to open the admin UI

### Reproduction steps

I don't know what triggered the bug - I just saw that my Admin UI wasn't enabled anymore.

1. On backend environments tab, hit "Set up admin UI" in the box
2. Observe it saying it's set up and then not continuing

### Build Settings

```yaml
Not sure it's relevant but it's not sensitive.


version: 1
backend:
  phases:
    build:
      commands:
        - amazon-linux-extras install python3.8
        - ln -fs /usr/bin/python3.8 /usr/bin/python3
        - pip3.8 install pipenv
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
```


### Additional information

https://stackoverflow.com/questions/67504106/unable-to-enable-aws-amplify-admin-ui
