### ISSUE TITLE
Slow build cache even without cache defined

### ISSUE THREAD

**Issue by mwarkentin** [aws-amplify/amplify-console#1833]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2ebo35xq239sq

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

We used to have a cache configuration in our amplify.yml, however we were running into issues w/ the cache size so we removed the cache: configuration a few months back.

I noticed that our Amplify builds still seem to be taking a couple of minutes fetching and extracting a cache - is this normal (eg. if we had a project configured without cache from scratch) or is there a way to bypass this entirely to help speed up our deployments?

Here's what I see in the logs:

```
2021-05-12T13:18:49.361Z [INFO]: # Retrieving cache...
2021-05-12T13:20:09.557Z [INFO]: # Extracting cache...
2021-05-12T13:21:34.226Z [INFO]: # Extraction completed
```

AWS support suggested trying to add `- envCache --set stackInfo ""`. I set this and deployed the project twice, however it didn't seem to provide any improvement.

### Expected behavior

Cache retrieval / extraction should either not happen or be very fast if we have removed our cache config from amplify.yml.

It would be nice if there was some visibility into the contents of the build cache, and a way to explicitly clear it out through the console.

### Reproduction steps

1. I'm not sure if it's a side effect of previously having a large cache, or simply having a large project that we're deploying (eg. are there any build artifacts that are cached by default without us explicitly defining them in amplify.yml?)

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install
        - npm install -g yarn
        - nvm use
    build:
      commands:
        - export RELEASE=$(git rev-parse --short=10 HEAD)
        - nvm use
        - yarn install --production
        - yarn run build
        - sed -i -e "s/%SENTRY_RELEASE_ID%/${RELEASE}/" ./dist/index.html
        - export SENTRY_AUTH_TOKEN=$(aws ssm get-parameter --with-decryption --name=/next-wave/sentry_token --query=Parameter.Value --output=text)
        - |
          if [ -n \"${SENTRY_ENV}\" ] && [ \"${SENTRY_ENV}\" != \"NONE\" ]; then
            sentry-cli releases --org wavehq --project ${SENTRY_ENV}-next-wave files $RELEASE upload-sourcemaps ./dist || true
          fi
        - tar -czf prod.tar.gz -C dist .
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'X-Backend'
          value: 'amplify'

    # Enable browser caching of static assets
    - pattern: '**/*.js'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=2678400'
    - pattern: '**/*.css'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=2678400'
    - pattern: '**/*.svg'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=2678400'
    - pattern: '**/*.png'
      headers:
        - key: 'Cache-Control'
          value: 'public, max-age=2678400'
```
```


### Additional information

* AWS Support Case ID: 8331441271
* Our TAM is aware of the case / issue as well
