### ISSUE TITLE
Recently pushed commit is not reflected in the latest automated build

### ISSUE THREAD

**Issue by jericopulvera** [aws-amplify/amplify-console#1847]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dptgqyo1az3e7

### Region

ap-southeast-1

### Amplify Console feature

Not applicable

### Describe the bug

I made some visible changes to our project and pushed it into our bitbucket repo's main branch.

The AWS Amplify Console triggers a new build but the cloned repo is not the latest one.

### Expected behavior

The latest pushed commit should be reflected in the latest build.

### Reproduction steps

1. git add .
2. git commit -m "commit message"
3. git push

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build:$AWS_BRANCH
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
     - pattern: '**/*.json'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.js'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.css'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.gif'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.ico'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.jpg'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.png'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.svg'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.mp4'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*.webm'
       headers: 
        - key: 'Cache-Control' 
          value: 'public,max-age=31536000,immutable'
     - pattern: '**/*'
       headers:
        - key: 'Strict-Transport-Security'
          value: 'max-age=31536000; includeSubDomains'
        - key: 'X-Frame-Options'
          value: 'SAMEORIGIN'
        - key: 'X-XSS-Protection'
          value: '1; mode=block'
        - key: 'X-Content-Type-Options'
          value: 'nosniff'
```

### Additional information

Connecting a new branch that came from the main branch build is also outdated.

I suspect that the automated build keeps cloning a specific commit from the past.
