### ISSUE TITLE
SSR Nextjs build fails

### ISSUE THREAD

**Issue by andrewbtp** [aws-amplify/amplify-console#1853]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3jqvjy8buadl5

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

I'm working to transfer an SSG Next.js web application to the new hybrid SSG+SSR system released by Amplify today. While building the updated dev environment, the build log spits out:
```
2021-05-18T20:31:24.839Z [INFO]: Starting SSR Build...
2021-05-18T20:33:15.440Z [INFO]: Error
```

### Expected behavior

I expected the SSR to build correctly.

### Reproduction steps

1. Took my existing SSG application, updated the build settings to target `baseDirectory: .next`
2. Updated package.json "scripts":"build" to `next build` in place of `next build && next export`
3. Renamed my "public" directory to "publick"
4. Pushed to Github which triggered the Amplify build for the dev environment

### Build Settings

```yaml
backend:
  phases:
    build:
      commands:
        # - amplifyPush --simple
...  
artifacts:
    baseDirectory: .next
    files:
      - '**/*'

Amplify CLI
4.27.3
```

### Additional information

Current Nextjs: 10.0.6 (but not using any 10.0 features!)
Current Amplify version locally AND for the build: 4.27.3

**Comment by Athena96** [comment]
Hi @andrewbtp I took a look at your build and it looks like you are hitting the 
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Comment by andrewbtp** [comment]
This was solved by adding `        - export NODE_OPTIONS="--max-old-space-size=5120"` to my build settings before `npm ci`.

However, I'm now running into
```
2021-05-18T21:38:26.731Z [INFO]: Starting SSR Build...
2021-05-18T21:40:30.770Z [INFO]: Access Denied: please make sure you have added an IAM Service Role to your Amplify App.
```
The Amplify app has a service role with AdministratorAccess attached.

**Comment by Athena96** [comment]
I see you are assuming a role in your buildSpec during the preBuild phase, I think that might be related as I'm not sure how that will interact with the App Role that you have for you app (which is also Assumed at build time).
I will continue looking into this.

**Comment by andrewbtp** [comment]
Gotcha, I am assuming a role during the prebuild, but it's also the same role assigned to the app. I'll try removing my custom build settings in a bit and see if it works.

Appreciate the help!

**Comment by andrewbtp** [comment]
Removing the assumed role in the prebuild phase worked, and it seems that y'all updated Amplify since I did that custom build phase so I no longer need it.

Thanks again for the help!

**Comment by andrewbtp** [comment]
```

**Comment by pads** [comment]
Hi there, I'm also experiencing this problem (build error), even with the `NODE_OPTIONS` set:
```
2021-05-21T09:33:41.574Z [INFO]: Starting SSR Build...
2021-05-21T09:38:49.717Z [INFO]: Error
Terminating logging...
```

My app ID: `d27e62p95s23q5` and region: `us-east-1`

Contents of `amplify.yml`:
```yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install
        - nvm use
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - npm ci
        - export NODE_OPTIONS="--max-old-space-size=5120"
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

Please let me know if you need any more details.
