### ISSUE TITLE
Build fails with " SyntaxError: Unexpected token A in JSON at position"

### ISSUE THREAD

**Issue by liamsir** [aws-amplify/amplify-console#1875]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-east-2:521970183983:apps/d2275y6ume6enf

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

I'm getting " !!! SyntaxError: Unexpected token A in JSON at position 0" error on the build step and a message box on top of the Cloning Repository accordion that says "There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again."
I tried to reconnect the repository, deleted the web hooks and deployments keys from GitHub, but still getting the same error.

### Expected behavior

Build should succeed.

### Reproduction steps

Trigger the build with a webhook or a commit to the dev branch and wait for the build step to start.

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - npm ci
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: app
```

**Comment by nimacks** [comment]
Hi @liamsir , your build spec indicates that you're creating an app based on a monorepo. Ensure that the build spec matches the format specified in this document https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration

For example 
```
version: 1
applications:
  - appRoot: /react-app
    env:
    variables:
        key: value
    backend:
      phases:
        preBuild:
          commands:
            - *enter command*
        build:
          commands:
            - *enter command*
        postBuild:
            commands:
            - *enter command*
    frontend:
      phases:
        preBuild:
          commands:
            - *enter command*
            - *enter command*
        build:
          commands:
            - *enter command*
      artifacts:
        files:
            - location
            - location
        discard-paths: yes
        baseDirectory: location
      cache:
        paths:
            - path
            - path
      artifacts:
        files:
            - location
            - location
        configFilePath: *location*
        baseDirectory: *location*
    
```

**Comment by liamsir** [comment]
I updated my build settings file to the following (even though the initial one was auto-generated with the "appRoot" set to "app" which is correct for the frontend phase and there's no need to specify it for the backend phase because the [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) for appRoot says
"The root, within the repository, that the application starts in. This key must exist, but may have no value if the application can be automatically discovered."), but is not working, the build tab is showing the same error "There was an issue connecting to your repo provider, click "Reconnect repository" in General Settings, and then try your build again.":
```
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    build:
      commands:
        - npm cache clean
        - npm install
        - npm run build
  artifacts:
    baseDirectory: build
    files:
        - '**/*'
  cache:
    paths:
        - node_modules/**/*
  appRoot: app
```

I think the error is related to this issue https://github.com/aws-amplify/amplify-console/issues/106 but I can't see any detailed log that explains what's wrong with the amplify.yml configuration

**Comment by behrooziAWS** [comment]
Your buildspec is still incorrect with the last build on 6/12/2021.  If this is not a monorepo app, you need to:

1. remove the appRoot portion or your buildspec 
2. unset the AMPLIFY_MONOREPO_APP_ROOT [environment variable](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#setting-env-vars).

i.e. for #1
```
version: 1
backend:
  phases:
    build:
      commands:
        - amplifyPush --simple
frontend:
  phases:
    build:
      commands:
        - npm cache clean
        - npm install
        - npm run build
  artifacts:
    baseDirectory: build
    files:
        - '**/*'
  cache:
    paths:
        - node_modules/**/*
```

If it is a monorepo app, you need to put `applications` in it:

```
version: 1
applications:
  backend:
    phases:
      build:
        commands:
          - amplifyPush --simple
  frontend:
    phases:
      build:
        commands:
          - npm cache clean
          - npm install
          - npm run build
    artifacts:
      baseDirectory: build
      files:
          - '**/*'
    cache:
      paths:
          - node_modules/**/*
    appRoot: app
```

If there are additional issues, please provide them, it looks like the original issue this was cut for regarding parsing is no longer occurring.
