### ISSUE TITLE
Build fails with "Starting SSR Build..."

### ISSUE THREAD

**Issue by heikkikurkela** [aws-amplify/amplify-console#1877]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3bpolj3ju560p

### Region

eu-central-1

### Describe the bug

2021-05-25T19:30:14.299Z [INFO]: Starting SSR Build...
2021-05-25T19:31:43.625Z [INFO]: Error

### Expected behavior

Build should be successful since no change

### Reproduction steps

Just re-run the pipeline

### Build Settings

```yaml
BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - next build && next export
          artifacts:
            baseDirectory: out
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
```

### Additional information

Again... same SSR Build Error than our other App Id has earlier, https://github.com/aws-amplify/amplify-console/issues/1824.
This same problem is in our App id (d3bpolj3ju560p) now.

#1824 

@Athena96 or someone else: please fix this also asap, thanks!
