### ISSUE TITLE
Monorepo build for pull-request will cause error if main branch has no-monorepo amplify.yaml

### ISSUE THREAD

**Issue by xhiroga** [aws-amplify/amplify-console#1880]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-norhteast-1

### Amplify Console feature

Build settings

### Describe the bug

If the main branch does not have a monolipo-aware amplify.yaml, the build will fail even if the pull-request amplify.yaml is monolipo-aware.

### Expected behavior

The build will success.

### Reproduction steps

1. Prepare a non-monolipo repository and commit amplify.yaml.
2. make it a monolipo
3. configure Amplify App for monolipo, and modify amplify.yaml to support monolipo with pull-request
4. preview build for pull-request fails.

### Build Settings

```yaml
version: 1
applications:
  - appRoot: workspaces/app1
    frontend:
      phases:
        preBuild:
          commands:
          - nvm install
          - nvm use
          - yarn install --immutable --immutable-cache --check-cache
        build:
          commands:
          - nvm use
          - yarn build --no-devtool
      artifacts:
        baseDirectory: dist
        files:
        - '**/*'
```
