### ISSUE TITLE
Next.js SSR Build failed

### ISSUE THREAD

**Issue by vcnc-hex** [aws-amplify/amplify-console#1882]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3dailwtota4uk

### Region

ap-northeast-2

### Amplify Console feature

Custom builds

### Describe the bug

The build supported of SSR mode was failed.

### Expected behavior

The bulid should be worked.

### Reproduction steps

Deploy with Next.js SSR project.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - export NODE_OPTIONS="--max-old-space-size=5120"
        - yarn build:dev
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

```
2021-05-27T06:18:36.707Z [INFO]: Starting SSR Build...
2021-05-27T06:20:34.966Z [INFO]: Error
```

Similar issue:
https://github.com/aws-amplify/amplify-console/issues/1853
https://github.com/aws-amplify/amplify-console/issues/1874
