### ISSUE TITLE
Artifact Directory Not Found (Closes Issues provide no fix)

### ISSUE THREAD

**Issue by tcoz** [aws-amplify/amplify-console#1885]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

ds06hddc00ipa

### Region

us-east-1

### Amplify Console feature

Build settings, Monorepo

### Describe the bug

Note that this build uses the nx monorepo extensions. 

Previously, the build settings worked as expected (so there were no issues with nx). 

Running the command "nx run fretboard-framework:build --prod" resulted in a top-level directory (dist/apps/fretboard-framework) which is the configured artifact directory in the build settings. Everything worked fine. 

I updated Angular 11 to Angular 12, which resulted in some package.json changes, but no code changes. Overall this wouldn't seem to have anything to do with it, but full disclosure etc.

Builds now fail. The issue is that the artifact directory could not be found:

 2021-05-26T16:29:21.182Z [INFO]: ———————————————————————————————————————————————
                                 >  NX   SUCCESS  Running target "build" succeeded
2021-05-26T16:29:21.186Z [INFO]: >  NX   CLOUD  See run details at https://nx.app/runs/0bukATjFpaH
2021-05-26T16:29:21.199Z [INFO]: # Completed phase: build
2021-05-26T16:29:21.200Z [INFO]: ## Build completed successfully
2021-05-26T16:29:21.203Z [INFO]: # Starting caching...
2021-05-26T16:29:21.244Z [INFO]: Nothing to cache
2021-05-26T16:29:21.244Z [INFO]: # Caching completed
2021-05-26T16:29:21.249Z [INFO]: No custom headers found.
2021-05-26T16:29:21.297Z [ERROR]: !!! Error: Artifact directory doesn't exist: ./dist
2021-05-26T16:29:21.297Z [INFO]: # Starting environment caching...
2021-05-26T16:29:21.298Z [INFO]: # Uploading environment cache artifact...
2021-05-26T16:29:21.364Z [INFO]: # Environment caching completed

I've tried everything I can think of; setting the path to be relative to the approot (which would be ../../dist/apps/fretboard-framework), setting up the build directory to be within the approot, even committing the build directory with the assets in it (so if the process is putting it somewhere else, it should still find the committed directory). Nothing works. 

That artifact directory is not found. Note that the configured directory you see here is one of many (many) attempts with different paths.                                                      

I've seen a few closed threads on this, but they tend to end with, "Has anybody solved this problem?" No definitive guidance on the issue seems to be available. The suggestions I did find, none of them work. 

This has me at a total dead end. I have changes to deploy but am completely blocked by this. 

### Expected behavior

- Configure artifact directory in build settings
- Run build
- Artifact directory should be discovered and deployed predictably. 

### Reproduction steps

Run a build of my project. 

See the failure. 

### Build Settings

```yaml
  version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install -g @nrwl/cli
            - npm install
        build:
          commands: 
            - nx run fretboard-framework:build --prod
      artifacts:
        discardPaths: yes
        baseDirectory: dist/apps/fretboard-framework
        files:
          - '**/*'
      cache:
        paths: []                
    appRoot: apps/fretboard-framework
```

### Additional information

Note that the attached build config is the one that always worked previously. I have altered the paths every way I can think of:

./dist
../../dist

And so on. Nothing works.
