### ISSUE TITLE
[NEXTJS] Starting SSR Build...Error

### ISSUE THREAD

**Issue by andrewgadziksonos** [aws-amplify/amplify-console#1889]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1i7qtt97aq61n

### Region

us-east-2

### Amplify Console feature

Logging

### Describe the bug

My NextJS application fails to build without any additional information.  The build logs contain the following,

```
2021-05-28T12:39:53.668Z [INFO]: Starting SSR Build...
2021-05-28T12:40:49.064Z [INFO]: Error
```

### Expected behavior

I would expect to see detailed error messaging around why the build is failing

### Reproduction steps

1. Launched Amplify console
2. Created a new project based on my Github repository
3. Selected defaults
4. Finished creating project, CICD kicked off - Build failed

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I tried using `NODE_OPTIONS=--max-old-space-size=5120` but this didnt resolve the issue

I followed along here as well

#1853
#1874
#1882
