### ISSUE TITLE
Can you use bash subshells with build commands?

### ISSUE THREAD

**Issue by cam8001** [aws-amplify/amplify-console#189]
**Please describe which feature you have a question about?**

I am trying to generate a timestamp variable as part of my build, so I can add it to output. I have tried several different permuations - inline commands, backticks, `$()` syntax, and they all seem to fail with:

```/codebuild/output/src645567583/src/wa-immersion-site/amplify.sh: line 17: unexpected EOF while looking for matching `"'```

**Provide additional details**

Here's the current iteration of my `amplify.yml`:

```yaml
version: 0.2
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - npm rebuild node-sass
        - npm run css-build
    build: 
      commands:
        # Add the build time to output so you can easily see last build time.
        - TIMESTAMP=$(TZ=Pacific/Auckland date); sed -i "s,|DEPLOYTIME|,$TIMESTAMP," index.html
  artifacts:
    baseDirectory: /
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
