### ISSUE TITLE
Build settings and amplifyPush --simple questions

### ISSUE THREAD

**Issue by connected-mdeluco** [aws-amplify/amplify-console#1919]
**Please describe which feature you have a question about?**
* Build settings (amplify.yml)
* amplifyPush script
* environments

**Provide additional details**
There are example build commands that use the `amplifyPush` command - what is that? Is it documented somewhere? The [source code](https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh) refers to another script for simple mode - `envCache --get stackInfo`. What is `stackInfo` and the "environment cache" and how is it configured?

Why does `amplifyPush --simple` create a new environment rather than using my "dev" environment? How can I change what environment is used as the basis for new environments? (I.e. so new environments are based off of my "dev" environment.)

Lastly, the example I've copy/pasted into `amplify.yml` looks like shell scripting:
```
backend:
  phases:
    build:
      commands:
        - if [ "${USER_BRANCH}" = "master" ]; then amplifyPush -e prod -s; else amplifyPush -e dev -s; fi
```
What kind of shell would the last line be executed in - I'd like to know so I can write similar lines myself and know that I'm using correct syntax, etc.

**What AWS Services are you utilizing?**
* Amplify

**Provide additional details e.g. code snippets**
