### ISSUE TITLE
Deployment fails when test section included in amplify.yml

### ISSUE THREAD

**Issue by wyatt-troia** [aws-amplify/amplify-console#1923]
**Region:** us-east-1
**App ID:** diz6udlgf5b4p

The below build config results in a build that fails during the "deploy" stage with the following logs:
```
2021-06-04T04:19:06 [INFO]: Starting Deployment
2021-06-04T04:19:06 [ERROR]: Failed to deploy
```

When I remove the testing section entirely, deployment succeeds. Deployment also fails when I include the test section but omit the "files" part.

Is there anything I can do? I'd like to be able to integrate testing into my deployment process. The repo is structured as a monorepo

**amplify.yml:**
```
version: 1
applications:
  - appRoot: packages/my-app
    frontend:
      phases:
        preBuild:
          commands:
            - echo "REACT_APP_API_GATEWAY_URL=$REACT_APP_API_GATEWAY_URL" > .env
            - yarn install --frozen-lockfile
        build:
          commands:
            - npm run build
      artifacts:
        files:
            - "**/*"
        baseDirectory: build
      cache:
        paths:
          - node_modules/**/*
    test:
      phases:
        test:
          commands:
            - cd ../.. # go up to monorepo root
            - npm run test:run-all
      **artifacts:
        baseDirectory: ./ # arbitrary existing path bc amplify test phase will fail without one
        files:
          - "**/*.mp4"**

```

**Comment by kahdojay** [comment]
@wyatt-troia can you confirm for me the branch and job number for the deploy failure? The only deploy for `diz6udlgf5b4p` that I see around that time doesn't show any error on our end.

**Comment by kahdojay** [comment]
@wyatt-troia can you also double check your yaml syntax (in particular `**artifacts` looks off) and see if this also helps: https://github.com/aws-amplify/amplify-console/issues/1167#issuecomment-725862271

**Comment by saachitech** [comment]
I am having a similar issue with this. My Amplify.yml looks like following and my app id is **dnpfuqj1l8nkg**. I also tried to modify yml as per suggestions/examples I found on the internet but nothing works. It always stuck at the build phase or sometimes at the test phase but it never starts my tests. 

**amplify.yml:**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    test:
      commands:
        - yarn test
  artifacts:
    baseDirectory: ./
    files:
      - '**/*.mp4'    
```

**Comment by saachitech** [comment]
Updates:

I modify my yml to this

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
test:
  phases:
    test:
      commands:
        - 'yarn test'
  artifacts:
    baseDirectory: ./
    files:
      - '**/*.mp4'
```

Now all my tests passed and worked correctly but now it fails on deploy with the following logs
```
2021-06-14T06:43:35 [INFO]: Starting Deployment
2021-06-14T06:43:35 [ERROR]: Failed to deploy
```

**Comment by saachitech** [comment]
It worked now. I tested with a fresh new app and all good, so I think CI=true in package.json and **configFilePath: '**/mochawesome.json'** did the trick. Not sure why configFilePath is required, but [this](https://github.com/aws-amplify/amplify-console/issues/1167#issuecomment-725862271) helped me

**package.json**
```
...
"test": "CI=true react-scripts test",
...
```
**amplify.yml**
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    test:
      commands:
        - 'yarn test'
  artifacts:
    baseDirectory: ./
    **configFilePath: '**/mochawesome.json'**
    files:
      - '**/*.mp4'
```

**Comment by wyatt-troia** [comment]
@saachitech @kahdojay  Thank you! I also just had to provide an arbitrary value for `configFilePath`. Definitely tough to figure this one out with the error message given

Here was my final test section of my config:

```
    test:
      phases:
        test:
          commands:
            - cd ../.. # go up to monorepo root
            - npm run test:run-all
      artifacts: # arbitrary values (other than baseDirectory) bc amplify test phase will fail without them
        baseDirectory: ./ 
        configFilePath: '**/mochawesome.json'
        files:
          - '**/*.png'
          - '**/*.mp4'
 ```
