### ISSUE TITLE
[ERROR] Amplify Stuck at Deploy Step (Updating edge config)

### ISSUE THREAD

**Issue by alexgorb2016** [aws-amplify/amplify-console#1924]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:670221575720:apps/d2s56zwf3itwsi

### Region

eu-west-1

### Amplify Console feature

Build settings, Manual deploys

### Describe the bug

Hi, my deployment stuck on this step with no progress at all.
2021-06-04T05:57:28 [INFO]: Starting Deployment
2021-06-04T05:57:28 [INFO]: Updating Edge config
buildId 0000000003

Framework
Next.js - SSR

### Expected behavior

It should be deployed.

### Reproduction steps

Try to rebuild, same result

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
