### ISSUE TITLE
Access Control option is no longer available for NextJS apps

### ISSUE THREAD

**Issue by mahcr** [aws-amplify/amplify-console#1925]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id
-

### Region

us-east-1

### Amplify Console feature

Access control

### Describe the bug

The access control option in the Amplify console is no longer visible when creating a NextJS application. Older existent application the access control option in the menu is available.

### Expected behavior

There should be a way to set a username and password to restrict the access

### Reproduction steps

1. Create a NextJS app 
2. Push it to a repo
3. Connect to amplify 
4. Deploy it
5. Try to restrict the access using the access control option on the left panel

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run export
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

The `export` task just runs `yarn build && next export`

I also tried

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
```


### Additional information

My app is using only SSG, I don't need SSR, I coudn't find a way to disable the SSR, I'm not sure if using SSR disable the access control option
