### ISSUE TITLE
[NextJS] Build Failing (Starting SSR Build... Terminating logging...)

### ISSUE THREAD

**Issue by QB3L** [aws-amplify/amplify-console#1928]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dnuxde5s48b4y

### Region

us-east-2

### Amplify Console feature

Logging

### Describe the bug

My NextJS application fails to build but logging doesn't show any specifics.

2021-06-04T20:16:21.299Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-06-04T20:16:21.421Z [INFO]: Starting SSR Build...
2021-06-04T20:17:20.776Z [INFO]: Error
Terminating logging...

### Expected behavior

Build output to show me the error that is causing it to fail deployment

### Reproduction steps

Committed the code changes to the gitlab branch connected to amplify.
CI/CD kicked off
Front-end build failed.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - export NODE_OPTIONS="--max-old-space-size=5120"
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I added the NODE_OPTIONS export just to test if it would fix an issue as I saw it on related tickets.
