### ISSUE TITLE
GitHub Feed and Build Pipeline Stuck

### ISSUE THREAD

**Issue by ks440** [aws-amplify/amplify-console#1951]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2e1ocj8tevu7r

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

The frontend build pipeline from GitHub push's is stuck/broken for no obvious reason.

Even attempting to redeploy an old version hangs.

The Amplify Console just shows these gray "loading" bars.

![AWS_Amplify_Console](https://user-images.githubusercontent.com/66495991/121831189-dc689680-cc94-11eb-8c23-16b2c1ecdf52.jpg)

I tried to reconnect the branch, removing the webhook, etc.  This seems to be some broken state in the Amplify workflow.

### Expected behavior

GitHub pushes generate new builds.

### Reproduction steps

I am unaware of any specific step that may have caused this.

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot:
```

### Additional information

I had a bad build where I had specified an appRoot that was not correct, other than that, there is really nothing else interesting about what led to this case.
