### ISSUE TITLE
Uable to deploy the amplify app

### ISSUE THREAD

**Issue by abinayakumaran** [aws-amplify/amplify-console#1952]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-east-2

### Amplify Console feature

Manual deploys

### Describe the bug

My amplify is  successfully build  but deployment is failed but its works previous. I just change my production branch in amplify app settings. How i get the detailed logs for this failure without using cloud trail.

### Expected behavior

How i resolve the deploy issue or how i get detailed logs.

### Reproduction steps

1. Trigger by push code to the specific branch.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
