### ISSUE TITLE
Amplify build stuck in "Provision" step

### ISSUE THREAD

**Issue by SwapnilPatil07** [aws-amplify/amplify-console#1953]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d138awnc9k6dje

### Region

us-east-1

### Describe the bug

Amplify build stuck in "Provision" step. Cancelled 5 times and restarted but still not working. Latest build is running since 1 hour. Please help. 

![image](https://user-images.githubusercontent.com/5751045/121908548-f7adc300-cce1-11eb-953e-04a42279fd1c.png)

### Expected behavior

Build should be completed in less than 10 minutes. 

### Reproduction steps

1. Start build manually or using webhook.
2. Build is stuck in "Provision" step 

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
        - TEMP=$TEMP
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
