### ISSUE TITLE
Build always failing on frontend (Happening after today's Increased Latency for Build Operations issue)

### ISSUE THREAD

**Issue by luiskcs89** [aws-amplify/amplify-console#1957]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1pynf4s98mcr3

### Region

us-east-1

### Amplify Console feature

Build settings, Custom builds, Logging, Manual deploys

### Describe the bug

Build was getting stuck in Provision step, after you identified the issue it was solved.
Now it is always failing in the Font end build or just after that. There were no changes on our side and the logs don't show any errors that we can check.

### Expected behavior

Build should succeed and app should be deployed, as it was working before.

### Reproduction steps

1. Just try Redeploy this version on any recent build.

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - "# Execute Amplify CLI with the helper script"
        - chmod u+x ./vertrun-amplifypush.sh
        - ./vertrun-amplifypush.sh
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 12
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```
