### ISSUE TITLE
Nextjs SSR build error

### ISSUE THREAD

**Issue by ddangdol** [aws-amplify/amplify-console#1959]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2qi06tpamqiic

### Region

ap-northeast-2

### Amplify Console feature

Logging

### Describe the bug

My NextJS application fails to build but logging doesn't show any specifics.
`2021-06-15T00:02:09.232Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
2021-06-15T00:02:09.472Z [INFO]: Done in 178.05s.
2021-06-15T00:02:09.477Z [INFO]: Starting SSR Build...
2021-06-15T00:10:56.455Z [INFO]: Error
Terminating logging...`

### Expected behavior

Build output to show me the error that is causing it to fail deployment

### Reproduction steps

1. connected github project
2. save and deploy
3. frontend build failed

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        install:
          runtime-versions:
            nodejs: 12
        preBuild:
          commands:
            - node -v
            - yarn install
        build:
          commands:
            - yarn build:dev
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```

### Additional information

Used node v12

**Comment by Athena96** [comment]
Hi @ddangdol it looks like your build is hitting the HEAP memory limit, can you please add
`- export NODE_OPTIONS="--max-old-space-size=5120"` to your buildSpec like so 

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
        - export NODE_OPTIONS="--max-old-space-size=5120"
....
```
