### ISSUE TITLE
Amplify stuck at deploy step

### ISSUE THREAD

**Issue by antoineandrieu** [aws-amplify/amplify-console#1961]
### App Id

d1j578lqqx5u9d

### Region

eu-central-1

### Describe the bug

My Next.js SSR app deployment is currently stuck at the Deploy Step with these logs:
`2021-06-15T12:52:00 [INFO]: Starting Deployment
2021-06-15T12:52:00 [INFO]: Updating Edge config
`
### Reproduction steps

The Deployment is triggered from Gitlab push event.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
