### ISSUE TITLE
Build fails 

### ISSUE THREAD

**Issue by davad** [aws-amplify/amplify-console#1969]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d21n9qcdejpu4j

### Region

us-east-1

### Amplify Console feature

Backend builds, Build settings

### Describe the bug

We have a single backend application consumed by multiple frontend applications. For the frontend applications, we've setup a pre-build step that pulls in the backend application to generate `src/aws-exports.js`. The write-up [here](https://dev.to/applification/multiple-frontends-with-amplify-console-3nnj) is essentially what we're doing.

This process last deployed successfully 6/15/2021, 6:52:17 AM. Today it fails with the following error:
```
# Executing command: ./amplify-pull.sh --access-key "REDACTED" --secret-key "REDACTED" --aws-env "stage" --app-id "d2ayhs0x4ln1ka"
2021-06-16T19:52:04.060Z [INFO]: [31mAmplify appId mismatch.[39m
2021-06-16T19:52:04.062Z [INFO]: [0mYou are currently working in the amplify project with Id d21n9qcdejpu4j[0m
2021-06-16T19:52:04.097Z [ERROR]: !!! Build failed
2021-06-16T19:52:04.097Z [ERROR]: !!! Non-Zero Exit Code detected
```

I noticed that yesterday, the CI/CD process didn't show a 'Backend' deployment phase. Today it does.

### Expected behavior

Since no backend is defined on this application, no backend build step should occur. The frontend should be allowed to pull in a different backend during the `preBuild` phase.

Alternatively, better documentation about how to implement multiple frontend applications that consume the same backend application.

### Reproduction steps

1. Create backend as a separate Amplify Console app
2. Create new Amplify Console app for frontend
3. During the preBuild phase for application #2, do an `amplify pull` to fetch metadata from application #1

### Additional information

Backend AppID: d2ayhs0x4ln1ka
Frontend AppID: d21n9qcdejpu4j

1.

**Comment by davad** [comment]
Here is what my `amplify.yml` looks like:

```
 % cat amplify.yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - node -v
        - yarn -v
        - yarn install
        - ./amplify-pull.sh --access-key "${ACCESS_KEY_ID}" --secret-key "${SECRET_ACCESS_KEY}" --aws-env "${BACKEND_AWS_BRANCH}" --app-id "${BACKEND_APP_ID}"
    build:
      commands:
        - yarn run clean
        - yarn run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .yarn/**/*
```

Moving the `amplify-pull.sh` call to the backend build phase seems to have fixed the problem:
```
 % cat amplify.yml
version: 1
backend:
    phases:
        build:
            commands:
                - ./amplify-pull.sh --access-key "${ACCESS_KEY_ID}" --secret-key "${SECRET_ACCESS_KEY}" --aws-env "${BACKEND_AWS_BRANCH}" --app-id "${BACKEND_APP_ID}"
frontend:
    phases:
        preBuild:
            commands:
                - node -v
                - yarn -v
                - yarn install
        build:
            commands:
                - yarn run clean
                - yarn run build
    artifacts:
        baseDirectory: public
        files:
            - '**/*'
    cache:
        paths:
            - node_modules/**/*
            - .yarn/**/*
```
