### ISSUE TITLE
Nextjs Build failed

### ISSUE THREAD

**Issue by guykogel** [aws-amplify/amplify-console#2000]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:988037547302:apps/d2150622pl2let

### Region

eu-west-1

### Amplify Console feature

Build settings

### Describe the bug

I am trying to deploy nextjs app. The build seems to work but fails here:
```
Starting SSR Build...
Terminating logging...
```

### Expected behavior

Finish the build.

### Reproduction steps

1.  push code to master
2. GitHub trigger amplify to create a build.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:

        - yarn install 
       
    build:
      commands:
        - yarn next build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I tried adding 
 - export NODE_OPTIONS="--max-old-space-size=9120"
 but it didn't help.
