### ISSUE TITLE
Deploying Next.js SSR with Nx doesn't render anything

### ISSUE THREAD

**Issue by aaronmcadam** [aws-amplify/amplify-console#2014]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ltktbih463f

### Region

eu-west-2

### Amplify Console feature

Build settings

### Describe the bug

My build completes successfully, but when I open the URL, I see a black document—it fails to serve valid HTML:
![CleanShot 2021-06-30 at 10 41 53](https://user-images.githubusercontent.com/37928/123939879-8849fb80-d990-11eb-8c98-8c9f5d62da1a.jpg)

### Expected behavior

I expect to see my app rendered.

### Reproduction steps

1. Schedule a new build
2. Wait for it to complete
3. Check the URL

### Build Settings

```yaml
version: 1
applications:
  - appRoot: apps/backstage
    frontend:
        phases:
          preBuild:
            commands:
              - yarn install
          build:
            commands:
              - yarn nx build backstage --prod
        artifacts:
          baseDirectory: ../../dist/apps/backstage/.next
          files:
            - '**/*'
        cache:
          paths:
            - node_modules/**/*
```

### Additional information

I've tried a lot of other things, but it's hard to see what the SSR process is doing.
