### ISSUE TITLE
Backend Environments tab not appearing

### ISSUE THREAD

**Issue by mbraha** [aws-amplify/amplify-console#2029]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-1:009611472941:apps/d94a0xc1cxak4

### Region

us-west-1

### Amplify Console feature

Backend builds

### Describe the bug

The tab called "Backend environments" on the main page of the Amplify console page is missing.

![amplify_bug](https://user-images.githubusercontent.com/11700503/124390172-2db9e380-dc9f-11eb-89a5-bf6df2da63dc.png)

### Expected behavior

The "Backend environments" tab should be present.

### Reproduction steps

1. Launch "Front-End Developer" course from the "Getting Started with AWS" page.
2. Follow course until Module 2 "Initialize a Local Amplify App".
3. Third step "Initialize the Amplify app" instructs to navigate to "Backend environments" tab in Amplify Console. But it's not there.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
