### ISSUE TITLE
Does Gatsby .cache work ?

### ISSUE THREAD

**Issue by talebbits** [aws-amplify/amplify-console#203]
** Please describe which feature you have a question about? **
Trying to cache gatsby .cache directory but does not seems like it working.

I have following Build settings

``` 
version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - cd gatsby
        - nvm use $VERSION_NODE_12
        - yarn install

    build:
      commands:
        - nvm use $VERSION_NODE_12
        - yarn build

  artifacts:
    baseDirectory: gatsby/public
    files:
      - '**/*'
  cache:
    paths:
      - gatsby/.cache/**/*
      - gatsby/node_modules/**/*
```

** Provide additional details**
