### ISSUE TITLE
Frontend stucked on Provision after deployment

### ISSUE THREAD

**Issue by nidalasw** [aws-amplify/amplify-console#2031]
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://console.aws.amazon.com/amplify/home?region=us-east-1#/d1huifw3ka4zgk

### Region

us-east-1

### Amplify Console feature

Webhooks

### Describe the bug

My apps is stucked on Provision after a build. 

### Expected behavior

the build used to take few minute only

### Reproduction steps

Triggered a build by webhook

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - npm run generate
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
