### ISSUE TITLE
NPM Run Build Killed without information on why

### ISSUE THREAD

**Issue by multibdoyle** [aws-amplify/amplify-console#2036]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2isqxxj9rr0jf

### Region

us-east-2

### Amplify Console feature

Backend builds, Build settings, Custom builds, Manual deploys

### Describe the bug

I have linked my AWS Amplify app to a new React Gatsby GitHub repo for continuous deployment. The app compiles fine locally, but I am getting an error in the 'Frontend' during the AWS build, saying that the amplify.sh file is 'killed' at the npm run build line, followed by 'Non-Zero Exit Code Detected' error. Below is a link to a screenshot of the error:

[AWS Amplify Error](https://i.stack.imgur.com/3IJLO.png)

Below is a link to the repo:
[MultiBDoyle Personal Blog](https://github.com/multibdoyle/personal-blog
)

Do I need to edit the amplify.yml file, or maybe add something to a package-lock or gatsby-node file?

### Expected behavior

Expecting to see site re-published with latest GitHub repo changes applied. 

### Reproduction steps

1. Push code updates (added new blog posts) from local to remote origin
2. App is set-up for continuous deployment, and is expect to refresh with latest updates from GitHub 
3. Amplify gives error 'Build failed...Non-Zero Exit Code Detected Error'

### Build Settings

```yaml
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
