### ISSUE TITLE
Change aws amplify application infrastructure ?

### ISSUE THREAD

**Issue by PierreBalazuc** [aws-amplify/amplify-console#2042]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2y4s18nsmd981

### Region

eu-central-1

### Amplify Console feature

Build settings

### Describe the bug

Hi,
I i'm unable to build my application since the 25 of june, I tried everything to solve my problem. My build got an error when this commande start : 

`2021-06-30T07:23:56.409Z [INFO]: Starting SSR Build...`

I check a succefull build log and i notice that this command is not used and the build work.

My application is a react.js build with 65k line of code, everything work good. Then i tried for 2 week to solve this SSR error. 
Finaly i noticed that the Infrastructure in the parameter is set to **Next.js - SSR**
That why i got "Starting SSR Build" ?

I check an other of my react app running , i'm able to build it and the infrastructure is set to "**REACT**" and not "**Next.js - SSR**"

Is there a way to change the infrastructure parameter to be "**REACT**" again and not **Next.js - SSR** ? Because i need to push my last build ASAP.

Thanks

### Expected behavior

Build successfull without SSR command 

### Reproduction steps

Push code to my git repo
Build the app as i do for a year.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - npm ci
    build:
      commands:
        - nvm use $VERSION_NODE_12
        - node -v
        - npm run-script build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

lasted issue post on this error : #2009
