### ISSUE TITLE
SSR (Next) hosting gives "ERR_TOO_MANY_REDIRECTS" errors

### ISSUE THREAD

**Issue by osnodegeoffrey** [aws-amplify/amplify-console#2060]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3reb1dtew5wgf

### Region

eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

After adding my branch, I'm going to my application URL and can see the front page. It also seems that static content is working fine on other pages.
However, going to any kind of other URLs (api/SSR pages) it goes in a redirect loop.

I see that the lambdas are created and configured in cloudfront but they do not seem to be called. In any cases, there are no logs nor "recent invocations" when I'm checking those.

I also noticed that path like /api/whatever are changed to /api%2Fwhatever in the redirects.

Also worth noting that the behaviour is the same using custom domain, amplifyapp.com domain or the cloudfront url.
One more thing is that the lambdas were created in a different region (us-east-1) than everything else.

The cloudfront and lambdas were generated by amplify and haven't been changed

### Expected behavior

CloudFront and Lambdas returning content.

### Reproduction steps

Not sure what my app has that differs from others that would be relevant here... You can probably clone Repo URL: https://github.com/osnodegeoffrey/next-amplify  to get it all done
Skipping git setup here
1. yarn create next-app --typescript
2. amplify init
3. yarn add aws-amplify @aws-amplify/ui-react
4. amplify add api
5. amplify add hosting
Need a git push to trigger build from here

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

The app is actually typescript (not sure if it is relevant).
I have `trailingSlash: true` in next.config.js

URL working: https://main.d3reb1dtew5wgf.amplifyapp.com/
URL error: https://main.d3reb1dtew5wgf.amplifyapp.com/api/hello/
Repo URL: https://github.com/osnodegeoffrey/next-amplify
