### ISSUE TITLE
Build Fails Immediately in Zero seconds without Provision Job

### ISSUE THREAD

**Issue by allanitis** [aws-amplify/amplify-console#2080]
### Before opening, please confirm:
[x]  I have checked to see if my question is addressed in the FAQ.
[x]  I have searched for duplicate or closed issues.
[x]  I have read the guide for submitting bug reports.
[x]  I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id
d6pipvn7vdfl1 // dqt29ku42h3ld

### Region
eu-west-1

### Amplify Feature
Provision/Build stages

### Describe the Bug
Whenever I build, the job fails immediately in zero or 1 seconds with no error. Not even the provision stage runs. 

![Screenshot 2021-07-22 at 15 49 44](https://user-images.githubusercontent.com/10580223/126595003-70931d6a-ac0d-4ee5-8396-1ae560581e29.png)

![image](https://user-images.githubusercontent.com/10580223/126595140-63e598df-17d2-46b8-916f-67da2c5e1ee5.png)

I have tried every 2 hours, and sometimes it just works, but there is no pattern to this behaviour. I have tried adjusting Amplify Build settings from 4.29.4, to 4.52.0 to 5.1.2 but nothing works 
![126595091-2411fa56-c779-48ec-8e3c-788eacdbce6f](https://user-images.githubusercontent.com/10580223/126595404-0c4c05b4-95f4-4803-8119-7e4792a34fb8.png)

There are no errors in the network except to https://aws-amplify-prod-eu-west-1-artifacts.s3.eu-west-1.amazonaws.com/ with error NoSuchKey
![Screenshot 2021-07-22 at 15 52 41](https://user-images.githubusercontent.com/10580223/126595204-25ea0ab7-865e-4278-abea-e1079b3fc617.png)

### Expected Behaviour
The build succeeds. 

### Reproduction Steps
Have no idea where to start. It has appeared on both sub-accounts (develop and production). 

### Build Settings
```
version: 0.2
  
frontend:
  phases:
    preBuild:
      commands:
        - eval `ssh-agent -s`
        - echo "$DEPLOY_KEY" | base64 -d | ssh-add - > /dev/null
        - npm ci
    build:
      commands: 
        - npm run lint
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'Strict-Transport-Security'
          value: 'max-age=31536000; includeSubDomains'
        - key: 'X-Frame-Options'
          value: 'SAMEORIGIN'
        - key: 'X-XSS-Protection'
          value: '1; mode=block'
        - key: 'X-Content-Type-Options'
          value: 'nosniff'
        - key: 'Content-Security-Policy'
          value: "default-src
            'self'
            https://OUR_CSP.com

```

### Additional information
This is our build steps 
```
"build": "vue-cli-service build",
```

- We use a multi-account AWS architecture. The Amplify Apps are running in a sub-account. These Apps have been migrated from the Root account. 
- We used to Run on Amplify Backend (with Cognito), but have recently migrated off Amplify Backend so only using the Frontend CI for builds. We have completely removed the amplify/ directory from the repo recently. 
- I have connected the app with no backend environment
- Have tried reconnecting the repository many times - no impact
- Currently blocking our deployments on develop and prod
