### ISSUE TITLE
Nextjs app doesn't register service worker using next-pwa

### ISSUE THREAD

**Issue by mhamendes** [aws-amplify/amplify-console#2110]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dt0016ajs5y61

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

I'm using next-pwa lib to register the service worker on my web-app.

When I deploy the same code when deployed through AWS Fargate, the service-worker is identified and registered automatically, but when I deploy it using Amplify, the service-worker is not registered, even though I can access the file when going to the url it's available at.

My withPWA config:

`withPWA({
    pwa: {
      dest: 'public',
      skipWaiting: true,
      disable: process.env.NODE_ENV === 'development',
      runtimeCaching,
      register: true,
    },
)`

Both deployments are successful, but only the fargate one is registering the service worker as it should.

### Expected behavior

The amplify deployment should automatically register a service worker when the webapp loads

### Reproduction steps

1. Create next app
2. Config next-pwa on next.config.js
3. Deploy the webapp using Amplify
4. Access deployment url

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - export BUILD_DIR=$PWD/$BUILD_DIR_NAME
        - yarn install
        - cat aws-exports.js
        - yarn lint --fix
        - export NODE_OPTIONS="--max-old-space-size=5120"
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

Fargate deployment is the production, it's using a custom domain and Amplify deployment is using the default amplify url. I don't think it should matter.
