### ISSUE TITLE
Nextjs webapp with next-i18next build fails

### ISSUE THREAD

**Issue by mhamendes** [aws-amplify/amplify-console#2111]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dt0016ajs5y61

### Region

us-east-1

### Describe the bug

I have a `next` webapp and I'm using the `next-i18next` module for internationalization of my app. The build is successful locally, but it fails with amplify.

The error I'm getting is the following:
`Unhandled error during request: Error: Cannot find module '/codebuild/output/src576564262/src/vertra-webapp/next-i18next.config.js'

                                  at webpackEmptyContext (/codebuild/output/src576564262/src/vertra-webapp/.next//pages/404.js:175060:10)

                                  at /codebuild/output/src576564262/src/vertra-webapp/.next//pages/404.js:8987:73 {

                                  code: 'MODULE_NOT_FOUND'

                                  }`

The next-i18next.config.js file:
`module.exports = {
  i18n: {
    defaultLocale: 'pt-br',
    locales: ['pt-br', 'pt'],
  },
  lowerCaseLng: true,
  react: {
    useSuspense: false,
  },
};`

The next.config.js file:
`const withImages = require('next-images');
const withPWA = require('next-pwa');
const runtimeCaching = require('next-pwa/cache');
const { i18n } = require('./next-i18next.config');

const moduleExports = withImages(
  withPWA({
    pwa: {
      dest: 'public',
      skipWaiting: true,
      disable: process.env.NODE_ENV === 'development',
      runtimeCaching,
    },
    images: {
      domains: [
        'prod-vertra-properties-images.s3.amazonaws.com',
        'main-vertra-properties-images.s3.amazonaws.com',
      ],
    },
    i18n,
  })
);`

### Expected behavior

The webapp should build successfully.

### Reproduction steps

1. Create nextjs app
2. Install and config next-i18next
3. Build app using amplify

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - export BUILD_DIR=$PWD/$BUILD_DIR_NAME
        - yarn install
        - cat aws-exports.js
        - yarn lint --fix
        - export NODE_OPTIONS="--max-old-space-size=5120"
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
