### ISSUE TITLE
Previews doesn't delete the stack on pull request closure

### ISSUE THREAD

**Issue by adi518** [aws-amplify/amplify-console#2123]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dazj4he0xk1lv

### Region

us-east-1

### Amplify Console feature

Previews

### Describe the bug

I enabled "Previews" and created a PR, which created a new environment. I closed the PR (Bitbucket) and it never triggered a deletion of the stack, which means I have to delete them manually. Also, buckets are not deleted when deleting a stack, since Amplify stores some files in there when it creates the environment. Therefore, even the buckets have to be manually deleted.

### Expected behavior

Delete stack entirely, including S3 buckets.

### Reproduction steps

1. Enable Previews
2. Open a PR (Bitbucket)
3. Close the PR
4. Check CloudFormation

### Build Settings

```yaml
# https://docs.amplify.aws/cli/usage/headless
# https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html
# https://github.com/aws-amplify/amplify-console/issues/176
# https://github.com/aws-amplify/amplify-console/issues/229
# https://github.com/aws-amplify/amplify-console/issues/1642
# https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-739493860
version: 1
backend:
  phases:
    preBuild:
      commands:
        - yum update --assumeyes
        - yum install --assumeyes jq
        - echo "JQ_VERSION="$(jq --version)
        - node ./scripts/update_amplify_config.js
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - chmod u+x ./scripts/amplifyPush.sh
        - ./scripts/amplifyPush.sh --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14
        - nvm use 14
        # https://stackoverflow.com/questions/58482655/what-is-the-closest-to-npm-ci-in-yarn
        - yarn global add ts-node
        - rm -rf node_modules && yarn install --frozen-lockfile # equivalent of `npm ci`
    build:
      commands:
        - yarn build

  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - ~/.cache
test:
  phases:
    preTest:
      commands:
        # https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html
        # https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/
        # https://github.com/aws-amplify/amplify-console/issues/583
        # https://github.com/aws-amplify/amplify-console/issues/240
        # https://github.com/cypress-io/cypress/issues/6960
        # - export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        # - fs.inotify.max_user_watches=524288
        - nvm use 14
        - yarn add wait-on
        - yarn add pm2
        - yarn add mocha mochawesome mochawesome-merge mochawesome-report-generator
        - yarn pm2 start 'yarn start:test'
        - yarn wait-on http://localhost:3000
    test:
      commands:
        # https://docs.cypress.io/guides/guides/command-line#cypress-run-config-lt-config-gt
        - yarn test:e2e:ci
    postTest:
      commands:
        - yarn mochawesome-merge cypress/report/mochawesome-report/*.json > cypress/report/mochawesome.json
        - yarn pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```
