### ISSUE TITLE
Very slow build time to a NextJS app with only 2 pages

### ISSUE THREAD

**Issue by willianjusten** [aws-amplify/amplify-console#2127]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ywuiyssz1l16

### Region

us-east-2

### Amplify Console feature

Build settings, Performance

### Describe the bug

If you can see in the following image:

![image](https://user-images.githubusercontent.com/3991845/127967483-f480c2f8-b49a-4dea-ba26-e27c01ca6d14.png)

My builds are taking almost 10 minutes, but it's a very small project (NextJS with 2 static pages for now). I even removed testing stuff to run inside my CI/CD on Gitlab to save some time, but it still too slow... =/

Another thing that I noticed is that initially Amplify identified my project as Web Cypress even when I defined nextjs stuff.

---

If you could take a look, maybe it's just a misconfiguration, but it looks really weird.

### Expected behavior

It shouldn't take more than 2-3min, follow bellow the same project on Netlify and it's very similar in Vercel as well.

![image](https://user-images.githubusercontent.com/3991845/127967717-27810725-fd66-4a41-a689-1c967fbad9fe.png)

### Reproduction steps

1) Init the project with `amplify init` and answer the questions (remember it's next ssr project, so the build folder is .next)
2) Add hosting with `amplify add hosting`
3) Connect with Gitlab
4) Wait and see the build

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
