### ISSUE TITLE
Simple static website deploy from github repo no longer working - now always gets stuck in Provision state

### ISSUE THREAD

**Issue by flivni** [aws-amplify/amplify-console#2138]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2z5cf3gntkddq

### Region

us-east-1

### Amplify Console feature

Frontent build

### Preamble
I set up a simple static website on Amplify. I left almost everything with default settings; connected to a github repo;  custom subdomain. Everything worked!

I committed some changes to the repo, which triggered a new deploy. Everything still worked!

Then, I committed another change (just updating some javascript), and it no longer worked. It got stuck in `Provision` step. (Up till then, the entire deploy was taking under 2 minutes. And the provision step was near instantaneous.)

After waiting 15-minutes, I cancelled the deploy in the UI and then restarted it in the UI. The build succeeded.
_NOTE: When I cancelled the deploy, the UI updated to say that the `Provision` step had now succeeded, but the build step had failed. No log output for the build step, just an error message "Build failed to complete successfully."._

### The bug: Deploy stuck
After the above, no subsequent deploy worked. Subsequent deploys got stuck in `Provision` step, and unlike earlier, cancelling and restarting would not unstick.

Cancelling all deploys and then triggering a new deploy via a git push, also failed in the same way.

If the deploy is not cancelled, it ultimately times out (after maybe 30-minutes or so) and fails. No error message apart from "Build failed to complete successfully." is shown.

### Expected behavior

I would expect deploy to complete successfully.

### Reproduction steps

1. Trigger build via deploy to git
2. Deploy gets stuck in `Provision` step and then ultimately times out and fails.

### Build Settings

```yaml
+version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - node ./node_modules/gulp/bin/gulp.js
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: /app/
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

This is what the "stuck" state looks like:
![image](https://user-images.githubusercontent.com/153073/128589816-95cde6dc-dfea-4a5d-a066-09a48b865300.png)

This is what a timed out failure looks like:
![image](https://user-images.githubusercontent.com/153073/128589783-9b6eaf1e-6f38-4e8e-ae99-fcf09d5f7ef6.png)
