### ISSUE TITLE
Next SSR deploy fails with module not found

### ISSUE THREAD

**Issue by mwiekens** [aws-amplify/amplify-console#2139]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3rmzs0e8of5du

### Region

eu-west-1

### Amplify Console feature

Build settings

### Describe the bug

NextJS SSR deploy fails with: `Error: Cannot find module 'sass'`

It looks like it doesn't use the right version of Next?
I have setup the build overrides.
![image](https://user-images.githubusercontent.com/14075611/128627457-63378341-116a-4645-9f6a-cc5568d5952b.png)

`2021-08-08T09:23:07.381Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2021-08-08T09:23:12.464Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 5.3.0...`
I see it patching Amplify in the log. But I don't see such a mention for next.

### Expected behavior

SSR build being able to deploy succesfully

### Reproduction steps

Deploy a version of NextJS 11 with SSR

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
