### ISSUE TITLE
configuring access-control-allow-origin header

### ISSUE THREAD

**Issue by mads79** [aws-amplify/amplify-console#216]
** Please describe which feature you have a question about? **
Amplify configuration custom headers not working for me.

** Provide additional details**
I'm trying to deploy a js bundle with AWS amplify.
I need to add a Access-Control-Allow-Origin:'*' header to all the deployed files so they can be loaded from wherever. I tried to achieve this by adding a custom header like this::
```yml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
  customHeaders:
    - pattern: '*.js'
      headers:
      - key: 'Access-Control-Allow-Origin'
        value: '*'
```
But no header is added :disappointed: 
Is there an easier way to achieve this, or is my yml wrong?
