### ISSUE TITLE
Unable to access Amplify App from multiple ISPs

### ISSUE THREAD

**Issue by Hans-ABC** [aws-amplify/amplify-console#2172]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dhp8pp3jdvcr8

### Region

us-west-2

### Amplify Console feature

Not applicable

### Describe the bug

Unable to access the Amplify app, both on *.amplifyapp.com domain and on custom domain that's registered on some ISPs in different locations.

Everything works fine in most places (including Singapore, India, US, etc.).

2 locations that do not work:
- Maldives
- Thailand (work on some ISP but not on other ISP)

I was told by Maldives ISP that AWS is blocking the access, but I don't have control over the CloudFront distribution of Amplify. `nslookup` properly resolves to CloudFront but it always have connection reset error.

### Expected behavior

AWS Amplify and/or CloudFront should be accessible in most places even under different ISPs, barring countries under embargo (which in this case Maldives and Thailand are not).

### Reproduction steps

1. Deploy a simple web app or React app on Amplify
2. Access the site from Maldives

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - REACT_APP_ON_SERVER=true REACT_APP_PROD=true npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
