### ISSUE TITLE
Amplify is not passing headers on custom domains

### ISSUE THREAD

**Issue by uspai** [aws-amplify/amplify-console#2173]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

demy2iltb613o

### Region

us-east-2

### Amplify Console feature

Custom headers

### Describe the bug

Hi,
I have a reverse proxy from /api/<*> to https://prod.linvo.io/<*>
For some reason, it's not passing my custom headers.
I have 3 custom domains registered:
beta.linvo.io
dashboard.linvo.io
managers.linvo.io

Trying to access https://*.linvo.io/api/managers/self

Now here is the funny thing,
If I am using the provided domain, it works!
https://master.demy2iltb613o.amplifyapp.com/api/managers/self

The reverse proxy worked for the last 2 months.
This morning I woke up and it's failing.
This is a production version and honestly, I am not sure what to do.

### Expected behavior

Proxy pass works like before without failing.

### Reproduction steps

Register here:
https://managers.linvo.io/register

Login, and you will see the error.
https://managers.linvo.io/login

You can copy the request, change the domain to 
https://master.demy2iltb613o.amplifyapp.com

And it will work.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run managers
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

It was working for the last 2 months!
