### ISSUE TITLE
customHttp.yml not passing headers to the cloudfront distribution

### ISSUE THREAD

**Issue by cmnstmntmn** [aws-amplify/amplify-console#2174]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Custom headers

### Describe the bug

I'm using Next 11, that has a missing header, so I'm trying to add it via `customHttp.yml`

```yml
customHeaders:
  - pattern: "_next/image*"
    headers:
      - key: "Accept"
        value: "*/*"
```

If I'm adding it from cloud front .. it gets reseted with every rebuild.

### Expected behavior

Either update next js to support `Accept` header,
either allow it to be passed via `customHttp.yml`

### Reproduction steps

1. create a next js app
2. overwrite the version to `latest`
3. create `customHttp.yml`

```yml
customHeaders:
  - pattern: "_next/image*"
    headers:
      - key: "Accept"
        value: "*/*"

```
