### ISSUE TITLE
Amplify Tries to Build Static React App with Next.js config.

### ISSUE THREAD

**Issue by king0120** [aws-amplify/amplify-console#2178]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2a2vhd02c1pv7

### Region

us-east-2

### Amplify Console feature

Deploy Step

### Describe the bug

Within the past 2 days all of my Amplify builds have begun failing on the Deploy step.  We are building just a Static React app through a Nx Monorepo (one application, many libraries), but amplify fails saying that it's looking for Next.js.  The specific error message is
```
2021-08-18T01:14:54 [INFO]: Beginning deployment for application d2a2vhd02c1pv7, branch:prod-duplicate, buildId 0000000025
2021-08-18T01:14:54 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2021-08-18T01:14:54 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

I cannot find any way to tell Amplify to treat my app just like a static application.  In the General App Settings under framework, the entry is completely blank and uneditable.

### Expected behavior

Amplify should be able to deploy a static react app and differentiate between that and a Next.js application.

### Reproduction steps

Not 100% sure since we haven't changed our deployment process.  We are using deploys on push to a branch on Gitlab with the build settings seen below.  This flow has worked up until a day ago.

### Build Settings

```yaml
version: 1.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build --prod
  artifacts:
    baseDirectory: dist/apps/flashtract-frontend
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
