### ISSUE TITLE
ISR Regeneration Lambda fails with "A header you provided implies functionality that is not implemented"

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2179]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3fdiq126p9gfo

### Region

us-east-1

### Amplify Console feature

SSR

### Describe the bug

Next.js ISR route fails with this error in the regeneration lambda:

```json
{
    "errorType": "NotImplemented",
    "errorMessage": "A header you provided implies functionality that is not implemented",
    "Code": "NotImplemented",
    "Header": "Transfer-Encoding",
    "RequestId": "EM1D6FXAQFQHHYN0",
    "HostId": "QqfYlkbVkXfogMy7LmWqUlrWdt4ci+MPJuHJ98l1dVicFtjJPZuQhcKt1eM7njCjAGtHUPN5EYs=",
    "name": "NotImplemented",
    "$fault": "client",
    "$metadata": {
        "httpStatusCode": 501,
        "extendedRequestId": "QqfYlkbVkXfogMy7LmWqUlrWdt4ci+MPJuHJ98l1dVicFtjJPZuQhcKt1eM7njCjAGtHUPN5EYs=",
        "attempts": 1,
        "totalRetryDelay": 0
    },
    "stack": [
        "NotImplemented: A header you provided implies functionality that is not implemented",
        "    at deserializeAws_restXmlPutObjectCommandError (/var/task/PutObjectCommand-75c64cca.js:2994:41)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}
```

I believe it is failing to upload the built file to S3. It might be that the upload is missing the `Content-Length` header, though I do not know.

### Expected behavior

Not to fail the Lambda

### Reproduction steps

Here's the `getStaticProps` (removed some identifying info):

```tsx
export const getStaticProps: GetStaticProps = async ({ params }) => {
  const queryClient = new QueryClient();
  if (!params) {
    throw new Error("Excepted params");
  }
  const { slug } = params;

  const { promises: fs } = await import("fs");

  if (!metadata) {
    metadata = await fs
      .readFile("./src/assets/metadata/metadata.json", "utf-8")
      .then((t) => JSON.parse(t) as Metadata)
      .catch(() => ({} as Metadata));
  }

  if (!cacheLoaded) {
    cache = await fs
      .readFile(FILE_PATH, "utf-8")
      .then((t) => JSON.parse(t) as Record<string, IRecord>)
      .catch(() => ({} as Record<string, IRecord>));
    cacheLoaded = true;
  }

  const getQuery: () => IMeta | Promise<IMeta | IApiError> = () =>
    cache[slug] ?? getMeta({ slug });

  await queryClient.prefetchQuery<IMeta | Promise<IMeta | IApiError>>(
    ["meta", slug],
    getQuery
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
      seo: {
        description: metadata?.description ?? null,
        title: metadata?.title ?? null,
        keywords: metadata?.keywords ?? null,
      },
    },

    revalidate: 60 * 2, // in seconds
  };
};
```

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        # The scripting library zx requires Node 14.
        - nvm install 14
        - nvm use 14
        - yarn install
    build:
      commands:
        - yarn build
    postBuild:
      commands:
        - cd ./scripts && node ./on-post-amplify-build.mjs
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

### Additional information

Lambda ID: `xrpzjukr-uurw6df`
