### ISSUE TITLE
Web previews suddenly stop registering (incorrect number of active branches)

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2180]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3fdiq126p9gfo

### Region

us-east-1

### Amplify Console feature

Previews

### Describe the bug

I have two apps that point to the same GitHub repository. Both use web previews, each pointing to different branches. I have confirmed that GitHub is sending the correct events from the webhooks log. The GitHub Amplify App is installed corectly.

Eventually, with no clear trigger or reasoning, Amplify Web Previews suddenly stop being created for pull requests. I have not found a workaround, we are without PR previews.

I have experienced this with my current Next.js SSR application as well as a separate `create-react-app` project in the past.

> I chose to use two apps because of limitations in access controls settings. However, I can revert to using one app at this time if that's what's required.

### Expected behavior

Web Previews consistently get created.

### Reproduction steps

It's unclear how to reproduce this issue as there is no clear trigger. I have attached the `appId` for investigation.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        # The scripting library zx requires Node 14.
        - nvm install 14
        - nvm use 14
        - yarn install
    build:
      commands:
        - yarn build
    postBuild:
      commands:
        - cd ./scripts && node ./on-post-amplify-build.mjs
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

### Additional information

I can send the other `appId` in an email to support if necessary.
