### ISSUE TITLE
Default build setup deploys Lambda functions to a different region than the one the app was created in

### ISSUE THREAD

**Issue by achadee** [aws-amplify/amplify-console#2199]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1svuqkghnpgxw

### Region

ap-southeast-2

### Amplify Console feature

Build settings

### Describe the bug

I deployed my app via the amplify console (Nextjs) on ap-southeast-2 - however the lambda functions generated in us-east-1. This is resulting in the site being slow, and sometimes timing out.

### Expected behavior

the lambda functions should deploy to the same region as the app

### Reproduction steps

Followed this tutorial
https://aws.amazon.com/blogs/mobile/host-a-next-js-ssr-app-with-real-time-data-on-aws-amplify/

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 16
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
