### ISSUE TITLE
Not Showing Pull Request in Amplify Web Preview

### ISSUE THREAD

**Issue by hiroki225** [aws-amplify/amplify-console#2201]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2mz4rw6tq9ofg

### Region

ap-northeast-1

### Amplify Console feature

Previews

### Describe the bug

I have just started using Amplify to build my web app, and set Web Preview by connecting with Github (followed [here](https://docs.aws.amazon.com/ja_jp/amplify/latest/userguide/pr-previews.html)). Even though Amplify App is integrated into my Github organization/repository, Web Preview does not get triggered and no pull requests are shown.

Could you tell me what causes this and how to solve the problem? (e.g., Need to use Github Team/Enterprise plan?)

### Expected behavior

In github, Amplify Console check should be triggered whenever a new pull request is opened.

### Reproduction steps

1. Create a branch and push changes to remote branch
2. Open a Pull Request

![210824-Github](https://user-images.githubusercontent.com/4658666/130735110-833f6201-45ae-4eae-8694-3f3eef52fbd3.jpg)

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - chmod u+x ./myamplifyPush.sh
        - ./myamplifyPush.sh
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
