### ISSUE TITLE
Use an `AWS::CodeStarConnections::Connection` for connecting an `AWS::Amplify::App` to an external repository

### ISSUE THREAD

**Issue by mbarneyjr** [aws-amplify/amplify-console#2215]
I'd like to be able to connect my Amplify Apps to GitHub via a CodeStarConnection resource, rather than passing a GitHub token secret through CloudFormation.

So when provisioning an Amplify App via CloudFormation, it could look like this:

```yml
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      ...
      ConnectionArn: arn:aws:codestar-connections:us-east-1:012012012012:connection/abc123
      # AccessToken: abc123
      # OauthToken: abc123
```

Or via the API

```sh
$ aws amplify create-app ... --connection-arn arn:aws:codestar-connections:us-east-1:012012012012:connection/abc123
```
