### ISSUE TITLE
Failure to detect Next SSR with CDK

### ISSUE THREAD

**Issue by jtmthf** [aws-amplify/amplify-console#2223]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d264wi3eh8cpbj

### Region

us-east-1

### Amplify Console feature

Build settings, Monorepo

### Describe the bug

This is similar to #2168 which was closed by the author after reformatting their repo to no longer need appRoot.

I am creating an amplify app using cdk using the below code. Although the app successfully builds, the app is not detected to be next SSR and only a zip is uploaded. The issue does not occur when the app is created from the console.

```ts
this.role = new iam.Role(this, 'AmplifyServiceRole', {
      assumedBy: new iam.ServicePrincipal('amplify.amazonaws.com'),
    });

const amplifyApp = new amplify.App(this, 'AmplifyApp', {
      appName: 'next-app',
      sourceCodeProvider: new amplify.GitHubSourceCodeProvider({
        owner: '<OWNER>',
        repository: '<REPO>',
        oauthToken: cdk.SecretValue.secretsManager('<TOKEN_NAME>'),
      }),
      role: this.role,
      environmentVariables: {
        AMPLIFY_MONOREPO_APP_ROOT: 'path/to/app',
      },
      buildSpec: codebuild.BuildSpec.fromObjectToYaml({
        version: '1.0',
        applications: [
          {
            appRoot: 'path/to/app',
            frontend: {
              phases: {
                preBuild: {
                  commands: ['cd ../..', 'npm ci'],
                },
                build: {
                  commands: ['npm run build', 'cd path/to/app'],
                },
              },
              artifacts: {
                baseDirectory: '.next',
                files: ['**/*'],
              },
              cache: {
                paths: ['node_modules/**/*'],
              },
            },
          },
        ],
      }),
    });

amplifyApp.addBranch('master');
```

The scripts for package.json for the app looks as below. The actual invoked build command seen in the buildspec exists in the root package.json and is responsible for building all local dependencies in addition to the app itself.

```json
"scripts": {
    "dev": "next dev --port 4000",
    "build": "next build",
    "start": "next start --port 4000",
    "lint": "next lint",
  },
```

### Expected behavior

I am expecting for the app to be deployed as next SSR and to run an SSR build.

### Reproduction steps

1. Create CDK stack using the above example code
2. Deploy
3. Trigger amplify build

### Build Settings

```yaml
version: "1.0"
applications:
  - appRoot: path/to/app
    frontend:
      phases:
        preBuild:
          commands:
            - cd ../..
            - npm ci
        build:
          commands:
            - npm run build
            - cd path/to/app
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
```

### Additional information

Using the amplify console to deploy the app has been the most consistent method to ensure the app is deployed as Next SSR
