### ISSUE TITLE
Build fails with "Starting SSR Build..." - No Error

### ISSUE THREAD

**Issue by VidorX** [aws-amplify/amplify-console#2224]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dfe2ftjgq6fqw

### Region

ap-southeast-1

### Amplify Console feature

Build settings, Logging

### Describe the bug

NextJS application fails to build without any additional logging. The build logs contain the following:

> 2021-09-02T10:23:40.537Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-09-02T10:23:40.779Z [INFO]: Starting SSR Build...
Terminating logging...

### Expected behavior

Build to be successful or error about why the build fails...

### Reproduction steps

1. New project from Github repository
2. Default image
3. amplify.yml as below
4. Redeploy this version

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 16
        - npm ci
        - npx npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL -r $NPM_REG -s $NPM_SCOPE
        - npm config set always-auth true
        - npm config set registry=$NPM_REG
        - npm install @<REMOVED>/<REMOVED>
        - "cp node_modules/@<REMOVED>/<REMOVED>/abi/* lib/contracts/"
        - npm run generate-types
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
