### ISSUE TITLE
[ERROR]: Failed to deploy for Vuejs

### ISSUE THREAD

**Issue by ziw** [aws-amplify/amplify-console#2233]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

df3mtkcbrprbr

### Region

us-west-2

### Amplify Console feature

Build settings

### Describe the bug

Deploy step fails silently with no error of log
```
2021-09-04T05:24:09 [INFO]: Starting Deployment
2021-09-04T05:24:09 [ERROR]: Failed to deploy
```

### Expected behavior

deploy should  be successful or show proper error message

### Reproduction steps

Go to Amplify console, `redeploy this version`.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 14
        - nvm use 14
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: tests
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    test:
      commands:
        - echo "not supported"

```

### Additional information

Tested changing the build setting with/without `nvm use` but all failed. Checked https://github.com/aws-amplify/amplify-console/issues/115 also not super helpful for my case. Please help! thank you
