### ISSUE TITLE
Amplify is not uploading all nextjs SSR build files to Lambda @edge 

### ISSUE THREAD

**Issue by mounika-avantgarde** [aws-amplify/amplify-console#2236]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2je83nc4so1nm

### Region

eu-central-1

### Amplify Console feature

Not applicable

### Describe the bug

I have a nextjs app built and deployed using amplify . After build the zip uploaded to lambda has chunks folder missing , due to which it throws below error

`Cannot find module '../chunks/11.js'\nRequire stack:\n- /var/task/pages/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js`

This issue is interimittent and it gets resolved If I destroy and recreate the stack .

### Expected behavior

After successful build amplify should upload zip file with chunks folder.

### Reproduction steps

It is mostly Intermittent issue

### Build Settings

```yaml
version: "1.0"
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files: "**/*"
  caches:
    paths: node_modules/**/*
```
