### ISSUE TITLE
Amplify Hosting - React app (CRA) builds but will no longer deploy due to erroneous detection of Next.js

### ISSUE THREAD

**Issue by r-moore** [aws-amplify/amplify-console#2238]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d31dmiryyxaax4

### Region

eu-west-1

### Amplify Console feature

Build settings, Custom builds, Manual deploys

### Describe the bug

We don't use Next.js, however we have a CRA-based React app (SPA) that builds fine but has recently started to fail **deploying** via Amplify.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/366280/132352693-8a98f53f-f0b1-4aca-b8d3-c083f0a2911a.png">

_Deploy failed to complete successfully._

The deploy step has the following output:
```
2021-09-07T13:26:40 [INFO]: Beginning deployment for application d31dmiryyxaax4, branch:staging, buildId 0000000116
2021-09-07T13:26:40 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2021-09-07T13:26:40 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
```

Refering to the docs, I'm still unsure what you need to do to convince Amplify that this is not an SSR/Next.js app. It's frustrating that there is some sort of Next.js auto-detection that can't be overridden by a config value or console setting.

Our Package.json does not contain any references to Next.js packages in any of the dependencies sections.

The app in Amplify Console is set as a React framework app correctly:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/366280/132353097-7101aa63-c6e1-490e-a7c8-e0128627769d.png">
N.B. I have tried manually changing the framework to 'Next.js - SSG' using [this procedure](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md#convert-an-ssr-app-to-ssg) but the deploy still failed so I changed it back to 'React'.

The service role for the app has Administrator role assigned.

Build image settings:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/366280/132353582-3d12c8df-db5d-4a22-aa63-8a7088e80c00.png">

### Expected behavior

A successful deploy of our React app (static SPA), which always used to work until Amplify added support for Next.js

### Reproduction steps

Push a commit to github repo that Amplify is watching.

I am testing on our staging branch (which has auto-build enabled, I do not want to auto build our master branch at this time).

### Build Settings

```yaml
version: 1
applications:
  - appRoot: *redacted-client-name*
    env:
      variables:
        SKIP_PREFLIGHT_CHECK: true
        VERSION_NODE_DEFAULT: $VERSION_NODE_12
    backend:
      phases:
        preBuild:
          commands:
            - yarn install --ignore-scripts
        build:
          commands:
            - amplifyPush --simple
    frontend:
      phases:
        build:
          commands:
            - yarn codegen
            - yarn craco build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
```

### Additional information

Note that our amplify.yml is currently setup with the monorepo support but we used to have it just `cd` in to the app directory and run the build which also used to work fine. All of the backend/frontend build steps work, it is just deploy which is failing.
