### ISSUE TITLE
Auto-deploy branches for Next.js – Cannot parse ".yml"

### ISSUE THREAD

**Issue by ericclemmons** [aws-amplify/amplify-console#2239]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3inl0muob87le

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

https://github.com/aws-amplify/amplify-ui/pull/324

Testing if creating/pushing branches that match `docs/**` will auto-deploy to Amplify Console:
> https://docs-test-console.d3inl0muob87le.amplifyapp.com/
> – https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/d3inl0muob87le

```
2021-09-01T18:06:54.417Z [ERROR]: Serverless Error ----------------------------------------
                                  
                                  Cannot parse ".yml": incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line in "/codebuild/output/src293475535/src/amplify-ui/docs/.yml" (6:6)
                                  
                                  3 |  inputs:
                                  4 |   build:
                                  5 |    env:
                                  6 |      : " "
                                  ----------^
                                  
                                  Get Support --------------------------------------------
                                  Docs:          docs..com
                                  Bugs:          github.com///issues
```

### Expected behavior

That `docs/**` will deploy just like `main`. PR previews (when the repo was private) worked just fine.

### Reproduction steps

![Screen Shot 2021-09-07 at 10 49 39 AM](https://user-images.githubusercontent.com/15182/132374460-46e9c545-39bb-4bc7-9e44-7b78e066c078.png)

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - nvm install
            - nvm use
            - node -v
            - (cd .. && yarn install)
        build:
          commands:
            - nvm install
            - nvm use
            - node -v
            - yarn build
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: docs
```

### Additional information

Duplicate of https://github.com/aws-amplify/amplify-console/issues/2235, which they fixed via:
> Fixed by explicitly set environment variable on selected branch.
