### ISSUE TITLE
CustomHeaders not applied to Web page

### ISSUE THREAD

**Issue by mijoel** [aws-amplify/amplify-console#2255]
**Please describe which feature you have a question about?**
AWS Amplify Custom Headers 
**Provide additional details**

Added CustomHeaders for webpage, but it is not updating for this certain app. 
![image](https://user-images.githubusercontent.com/73587933/133403937-5f08a382-2a62-4363-87a5-90f8bc1d9b4b.png)

**What AWS Services are you utilizing?**

Amplify, Cloudfront, Route53.

**Provide additional details e.g. code snippets**

**Comment by siegerts** [comment]
Hi @mijoel, thanks for raising. Do you mind providing more context on the app and steps to reproduce?  You can use this [form as a guide](https://github.com/aws-amplify/amplify-console/issues/new?assignees=&labels=&template=1.bug_report.yaml).  Mostly looking for the type of app and any explicit steps that you took (new app?, were the headers working before?, etc.) 

Thanks!

**Comment by mijoel** [comment]
I have checked to see if my question is addressed in the FAQ. *
 I have searched for duplicate or closed issues. *
 I have read the guide for submitting bug reports. *
 I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue. *

App ID: d1qks5y13jyp0e

Region: Europe (Frankfurt)

Amplify Console feature: CustomHeaders

Describe the bug:

Added CustomHeaders to webpage and it worked the first time, but when trying to change Headers couple days later it wouldn't change. 

Expected behavior:

When changing CustomHeaders it should update instantly for webpage. 

Build Settings:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run generate
  artifacts:
    baseDirectory: ./dist/
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

No steps to reproduce, can only provide the CustomHeaders:

`customHeaders:
  - pattern: '**/*'
    headers:
      - key: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - key: X-Frame-Options
        value: DENY
      - key: X-XSS-Protection
        value: 1; mode=block
      - key: X-Content-Type-Options
        value: nosniff
      - key: Content-Security-Policy
        value: default-src 'self';
        value: no-referrer`

Additional information:

App is not new, but added CustomHeaders are.
