### ISSUE TITLE
Amplify Console somehow caching the repository independently of how many pushes and breaking changes I push

### ISSUE THREAD

**Issue by superjose** [aws-amplify/amplify-console#2257]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2c48o68a0m4gs

### Region

us-east-2

### Amplify Console feature

Build settings, Custom builds, Environment variables, Monorepo

### Describe the bug

I honestly don't believe this is reproducible, but I'll do my best to show it off. I've been experiencing strange Webpack build issues. I'm under a monorepo that hosts an "app" (create-react-app) and "home" (create-react-app) base applications and a shared "components" (All 3 with TypeScript). 

After spending an ungodly 72 hours trying to figure out how to properly build the project and export environment variables that are branch-specific. After attempt 33, (Currently 38 - which last from 5 - 11 minutes to fail), I've come to realize that Amplify has been loading a cached version of my repository over and over again. 

How do I know? I've removed all the cache entries in the amplify.yml file and have intentionally corrupted my main files by pushing them to the main branch, which surely will not build... And yet, Amplify would load a previous version of the repository. 

I've tried manually overriding the amplify.yml file and pushing the changes directly to the root amplify.yml. 

Heck, I even manually changed the commands in the amplify.yml to force it to break and nada.

I think this should lie in the monorepo configuration...

### Expected behavior

Pull the latest changes from the repository

### Reproduction steps

Honestly I don't know how to reproduce it. I can only push changes and nothing will happen. 

### Build Settings

```yaml
version: 1
applications:
  - appRoot: home
    env:
    variables:
      SKIP_PREFLIGHT_CHECK: true
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install 12
            - npm install -g yarn
            - yarn global add gulp-cli
            - yarn add gulp-replace gulp-json-editor -D
            - gulp replace-with-local-package
            - yarn install
            - sh ./scripts/addArgs.sh # Run custom script to change react-snap options as it is throwing an error.
            - yarn lint
            # - yarn test
        build:
          commands:
            - REACT_APP_SNAP=${REACT_APP_SNAP}
            - REACT_APP_APPSYNC_URL=${REACT_APP_APPSYNC_URL}
            - REACT_APP_APPSYNC_WS_URL=${REACT_APP_APPSYNC_WS_URL}
            - REACT_APP_APPSYNC_API_ID=${REACT_APP_APPSYNC_API_ID}
            - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
            - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
            - REACT_APP_AUTH0_CALLBACK_URL=${REACT_APP_AUTH0_CALLBACK_URL}
            - REACT_APP_AUTH0_RETURN_TO_URL=${REACT_APP_AUTH0_RETURN_TO_URL}
            - REACT_APP_ROLE_ARN=${REACT_APP_ROLE_ARN}
            - REACT_APP_S3_UPLOAD_BUCKET=${REACT_APP_S3_UPLOAD_BUCKET}
            - yarn build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
  - appRoot: app
    env:
    variables:
      SKIP_PREFLIGHT_CHECK: true
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install 12
            - npm install -g yarn
            - yarn global add gulp-cli
            - yarn add gulp-replace gulp-json-editor -D
            - gulp replace-with-local-package
            - yarn install
            - yarn lint
            - yarn test
        build:
          commands:
            - REACT_APP_SNAP=${REACT_APP_SNAP}
            - REACT_APP_APPSYNC_URL=${REACT_APP_APPSYNC_URL}
            - REACT_APP_APPSYNC_WS_URL=${REACT_APP_APPSYNC_WS_URL}
            - REACT_APP_APPSYNC_API_ID=${REACT_APP_APPSYNC_API_ID}
            - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN}
            - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID}
            - REACT_APP_AUTH0_CALLBACK_URL=${REACT_APP_AUTH0_CALLBACK_URL}
            - REACT_APP_AUTH0_RETURN_TO_URL=${REACT_APP_AUTH0_RETURN_TO_URL}
            - REACT_APP_ROLE_ARN=${REACT_APP_ROLE_ARN}
            - REACT_APP_S3_UPLOAD_BUCKET=${REACT_APP_S3_UPLOAD_BUCKET}
            - yarn build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
```
