### ISSUE TITLE
[NextJS] ISR not triggered for paths returned back from getStaticPaths (prerendered pages)

### ISSUE THREAD

**Issue by andrewgadziksonos** [aws-amplify/amplify-console#2268]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dh2ndod2t9wbt

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

We have a few dynamic routes for various pages that utilize `getStaticPaths` to determine which pages we should prerender at build time.  Each page template is configured with a `60` second revalidation time.  We are noticing that if any prerendered page is requested after the 60 seconds has expired then there is no revalidation message sent to the SQS queue

### Expected behavior

Any request that contains an `uri` that is configured with `revalidate: N` should trigger revalidation

### Reproduction steps

1. create a dynamic routed page, something `pages/dynamic/[id].jsx`
2. implement getStaticPaths, and return a subset of all paths, set `fallback: blocking`
3. implement getStaticProps and return `revalidate: 60` 
4. build and deploy app
5. request prerendered page
6. wait over 60 seconds, hit refresh in the browser
7. verify that no messages were sent to SQS
8. verify that no log messages were generated by the ISR lambda

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

### Additional information

From what I can tell, this function looks like it starts everything
```
/**
 * Function called within an origin response as part of the Incremental Static
 * Regeneration logic. Returns required headers for the response, or false if
 * this response is not compatible with ISR.
 */
const getStaticRegenerationResponse = (options) => {
    ...
};
```

If ISR logic is truly invoked in a Origin Response function, then these functions are not triggered based on this info 
![image](https://user-images.githubusercontent.com/31038519/134409748-84af99da-1be3-4f85-a6db-d7242684a9a4.png)

My hunch is that we're hitting one of these conditions.  Maybe because of the way `if-none-match` and `etag` headers work?  (I am receiving a 304 response from CloudFront, but a `x-cache: Miss from cloudfront` header)
