### ISSUE TITLE
Hugo deploys correctly, but site gets ERR_TOO_MANY_REDIRECTS error

### ISSUE THREAD

**Issue by lionzan** [aws-amplify/amplify-console#227]
** Please describe which feature you have a question about? **
I am using Amplify with a Hugo site from a Code Commit repository sitting. The site deploys correctly to https://master.d3krcsf8wazcmd.amplifyapp.com/ but there I get the message 
```
This page isn’t working
master.d3krcsf8wazcmd.amplifyapp.com redirected you too many times.
```
What am I doing wrong? 

** Provide additional details**
I followed this [tutorial](https://gohugo.io/hosting-and-deployment/hosting-on-aws-amplify/)
See the `amplify.yml `file below, which is sitting in the root. The site is using the "hugo-now-ui" template, which works correctly on the local server.

```
version: 0.1 
frontend: 
  phases: 
    build: 
      commands: 
        - hugo -t hugo-now-ui 
  artifacts: 
    baseDirectory: public 
    files: 
      - '**/*' 
  cache: 
    paths: [] 
```
