### ISSUE TITLE
Next.js 11 SSR - Error: Component "@sls-next/-component@undefined" was not found on NPM nor could it be resolved locally

### ISSUE THREAD

**Issue by icy-meteor** [aws-amplify/amplify-console#2271]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dv41ziyrurpdc

### Region

ap-south-1

### Amplify Console feature

Not applicable

### Describe the bug

AWS Amplify project fails to start the SSR sever in the frontend build step of a Next.js 11 - SSR project and throws the following error:
![image](https://user-images.githubusercontent.com/22114682/134530313-39826dab-23c0-4f9b-b3c7-80f82aa8c1c5.png)

 

### Expected behavior

The build stage should be successful and SSR server should get started.

### Reproduction steps

1. Create a new Next.js 11 project using `npx create-next-app`
2. Create a new web app in AWS Amplify and deploy the Next.js app.
3. Go to Amplify Console > Build Settings > Live Package Updates and change the Next.js version to 11. (It defaults to 10)
4. Redeploy the Next.js app and you will notice it failing with the above error in Frontend build stage.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

Points to note: 
1. Next.js 11 uses **webpack 5 by default**
2.  I have tried installing the `@sls-next/serverless-component` both locally and globally but it doesn't help.
3. I've tried with different node versions starting from 12 to latest LTS 14.17.6 (at the time of creating this issue)
4. The same application deploys perfectly on Vercel and Netlify.
