### ISSUE TITLE
Nextjs deployment resources not updated after build

### ISSUE THREAD

**Issue by jtmthf** [aws-amplify/amplify-console#2276]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1b3v6taan5pst

### Region

us-east-1

### Amplify Console feature

Build settings

### Describe the bug

I have a Nextjs SSR app that doesn't seem to be deploying the latest version upon merging into master. From the console I can see that all stages of the build were successful but the production branch URL shows an older version of the app.

Upon checking the deployment bucket I can see that BUILD_ID points to a version of the app merged & deployed yesterday. Additionally within `_next/` the latest build artifacts are missing.

I also noticed that none of the lambdas (SSR, API, image) have been updated since yesterday.

### Expected behavior

Upon deploying a new version of the app, the latest version of resources should be deployed to S3 & Lambda.

### Reproduction steps

1. merge branch into master
2. check deployed artifacts

or

1. redeploy this version (from the console)
2. check deployed artifacts

### Build Settings

```yaml
version: "1.0"
applications:
  - appRoot: apps/renderer
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install
            - cd ../..
            - npm ci
        build:
          commands:
            - npm run build
            - cd apps/renderer
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
```
