### ISSUE TITLE
Preview deployment failed without details

### ISSUE THREAD

**Issue by scorring** [aws-amplify/amplify-console#2280]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1ig7ao87ld772

### Region

us-east-1

### Amplify Console feature

Logging, Previews

### Describe the bug

On the previews CI/CD, Amplify deployment failed without log details:

[INFO]: Starting Deployment
[ERROR]: Failed to deploy

![image](https://user-images.githubusercontent.com/1814344/135042008-2526f41d-3049-460e-9502-1a344443a202.png)

### Expected behavior

When failing during the **Deploy** step on the preview CI/CD, Amplify console logs should display error details.

### Reproduction steps

1. Create an application with a backend (Api, Auth and lambda function)
2. Enable pull requests previews and select "Create new backend environment for every Pull Request" in the settings for the master branch.
3. Create a pull request to master

### Build Settings

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
backend:
  phases:
    preBuild:
      commands:
        - cd amplify/backend/function/XXX
        - npm ci
        - npm run build
        - cd -
    build:
      commands:
        - amplifyPush --simple
test:
  artifacts:
    baseDirectory: coverage
    files:
      - "coverage-final.json"
  phases:
    preTest:
      commands:
        - npm ci
        - cd amplify/backend/function/XXX
        - npm ci
        - cd -
    test:
      commands:
        - "npm run test:unit"
        - "npm run test:back"
```

### Additional information

Our amplify.yml has build commands because of the code written in typescript and being transpilied.
This issue is happening since we added a lambda function to the backend and the backend configuration entry in the build settings. The previous steps are all green and the new backend environment (pria for example) is successfully created.
Please help, our CI is stucked since a few days and the lack of logs prevents us from investigating.
