### ISSUE TITLE
[Next.js ISR for < v11.1.1] - Falling back to using page's rendering function for html -> blank page

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2286]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3am3wm1pufv8b

### Region

us-east-1

### Describe the bug

When performing ISR, the CloudWatch logs show this INFO message:

```txt
2021-09-29T19:35:48.201Z 7bb932bc-a773-57c0-aa41-6b72654e1cb5 INFO Falling back to using page's rendering function for html
```

When that happens, the page regenerates as a completely blank page.

### Expected behavior

The page does not regenerate as a completely blank page.

### Reproduction steps

1. Next.js 11.1.0
2. Create an ISR page
3. Under _some unknown scenario_, the page does not regenerate successfully and generates a blank page

Sorry, terrible reproduction steps. There are no relevant logs to suggest why this is happening.

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        # The scripting library zx requires Node 14.
        - nvm install 14
        - nvm use 14
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```
