### ISSUE TITLE
Appsync Console Schema auto populates @aws_iam even though the default authentication is aws_cognito_user_pools

### ISSUE THREAD

**Issue by vineethbhargavan** [aws-amplify/amplify-console#2288]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:ap-southeast-2:888850479540:apps/d2efvo468a8rac

### Region

ap-southeast-2

### Amplify Console feature

Backend builds

### Describe the bug

Of late (last few days) its been observed that any change in schema.graphql , which gets auto built by the amplify backend -adds the directive @aws_iam and @aws_cognito_userpool to the schema  in Appsync (viewed in the appsync console).

**What we see now:**
`
type Activity @aws_iam
@aws_cognito_user_pools {
	id: ID!
	action: String!
`

**What was displayed a few days back:**
`
type Activity {
	id: ID!
	action: String!
`

**Note:** The above two are from the same schema.graphql. But the representation in Appsync console is different!!!
Also, I would like to mention that , while 95% of the entities in schema.graphql use the auth mode - cognito user pool, we have  a few entities and mutations using the @aws_iam e.g :
`
echoMutation(
    clientID: ID!
    entity: String!
    queryToCall: String!
    id: ID!
  ): Echo! @aws_iam
`

As a result of this change the default  cognito user pool authentication doesn't work  as  aws_iam auth mode takes precedence!- and all API calls fail!!!

So looking at the cloudformation templates, in the amplify backend folder, there is nothing suspicious.
- they all have default authentication as Cognito User Pool , with additional authentication as AWS_IAM
 e.g:
`
      "output": {
        "authConfig": {
          "defaultAuthentication": {
            "authenticationType": "AMAZON_COGNITO_USER_POOLS",
            "userPoolConfig": {
              "userPoolId": "authapp36xxx"
            }
          },
          "additionalAuthenticationProviders": [
            {
              "authenticationType": "AWS_IAM"
            }
          ]
        }
`

### Expected behavior

The Schema details in AppSync console should reflect the true nature of  the authentication schema - as defined in schema.graphql . 

@aws_iam directive should only be mentioned for those having @aws_iam in the schema.graphql and not for all the other entities/mutations.

### Reproduction steps

1. Have a schema.graphql with a combination of cognito user pool authentication and iam.
2. Git push the changes to Code commit - wait for amplify backend to build .
3. Upon successful build go to Appsync console and check the Schema of your respective api.
4.  You will notice a @aws_iam being tagged to all the entities/connections, inspite of not having explictly mapped to aws_iam authentication.

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amazon-linux-extras install python3.8
            - ln -fs /usr/bin/python3.8 /usr/bin/python3
            - pip3.8 install pipenv
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn install
      artifacts:
        baseDirectory: src
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
    appRoot: app
```

### Additional information

What we are seeing now:
![image](https://user-images.githubusercontent.com/12675696/135418210-ca498e67-0351-49e5-bfcd-116e2cb85bfd.png)

What we saw a few days back:
![image](https://user-images.githubusercontent.com/12675696/135418403-c486405e-3969-410a-b5da-0fbe1f047e66.png)
