### ISSUE TITLE
Instance failing on build but works fine on another app with the same branch setup

### ISSUE THREAD

**Issue by wklsh** [aws-amplify/amplify-console#2290]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d16duwernqkuew

### Region

ap-northeast-1

### Amplify Console feature

Build settings, Previews

### Describe the bug

We've encountered a build error during one of our test re-deploys (**APP_ID: d16duwernqkuew** — no new code was pushed). As the error did not seem to come from our codebase. We then proceeded to create another test app(**APP_ID: d1vcifaosm0mfw**) with the exact same setup and branch target. The test app deploys as per normal, while we do not have any resolution for the existing failed instance.

We've also tried reconnecting the branch with a new instance within the older app but that does not seem to be working either

**APP_ID: d16duwernqkuew:**
![image](https://user-images.githubusercontent.com/17349311/135448866-1367074b-a3dc-4257-ad87-26c1c21377f2.png)

**APP_ID: d1vcifaosm0mfw**
![image](https://user-images.githubusercontent.com/17349311/135448918-994f2726-a294-41ea-9162-f99bfec377de.png)

### Expected behavior

With a similar codebase and build .yml config, both should be deploying in similar states

### Reproduction steps

Deploying / redeploying the builds will lead to this error

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
        
  artifacts:
    baseDirectory: /build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
