### ISSUE TITLE
Option to disable PR preview GitHub App comments (nice job on them though!)

### ISSUE THREAD

**Issue by quinnturner** [aws-amplify/amplify-console#2293]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

Not relevant

### Region

us-east-1

### Amplify Console feature

Previews

### Describe the bug

I love the new GitHub integration to notify users about the PR preview! This was a huge issue for our developers because it's relatively inconvenient to have to sign in to AWS to access the info on the Amplify console.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/12538019/135631778-c7100c48-7562-4faa-9626-5db8896524da.png">

However, because our team needed this earlier, I wrote custom postBuild scripts that performed a superset of functionality including a link to the build console and build size diffs for Next.js (hit me up if you wanna learn how I did it 😄)

<img width="916" alt="image" src="https://user-images.githubusercontent.com/12538019/135631609-e27af2ea-0cc2-4b7f-857f-6fd159449e4c.png">

Because of this, the app is added noise since two comments get created per PR.

### Expected behavior

There should be a setting, per PR preview branch(?), that disable this GitHub App functionality.

### Reproduction steps

1. Link a GitHub repository
2. Set up PR previews
3. Create a PR

**Comment by ericclemmons** [comment]
@quinnturner I'd absolutely _love_ to know how you calculated the Next.js build differences.

In my testing with https://github.com/aws-amplify/amplify-js/tree/main/.github/actions/bundle-size-action/next, especially API routes were problematic due to how Next.js was splitting code.

**Comment by ippoippo** [comment]
I find it this message generation very spammy. It potentially litters your PR with comments that are all the same. It results in emails to folks who are involved with reviewing PRs. 
Opinion: It needs to be configurable. Also, the first time you push is a reasonable time to add the comment. After that, there is no need for repeated comments on each git commit.

**Comment by NathanGay** [comment]
I'd love to get this turned off. We're doing multiple app builds in the same repo and it's a flood of comments that don't even tell you which app it's referring to. If anyone has a suggestion on how to kill the comments entirely I'm all ears.

**Comment by dtinth** [comment]
It would be great if AWS Amplify switched to the [Deployments API](https://docs.github.com/en/rest/reference/repos#deployments). They now have support for “transient environments” which is useful for PR previews.

## Workaround to reduce noise

```yaml
# .github/workflows/delete-comments-from-aws-amplify.yml
name: Delete noisy AWS Amplify comments
on:
  issue_comment:
    types: [created]
jobs:
  poof:
    if: |
      github.event.comment.user.login == 'aws-amplify-ap-southeast-1[bot]' && contains(github.event.comment.body, 'This pull request is automatically being deployed by Amplify Hosting')
    runs-on: ubuntu-latest
    steps:
      - run: gh api -X DELETE '${{ github.event.comment.url }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

![image](https://user-images.githubusercontent.com/193136/145536930-37b754db-9394-457b-a828-babd373e0058.png)

![image](https://user-images.githubusercontent.com/193136/145534657-c82ffbd6-cc45-46fb-b685-a010194cb1dd.png)
