### ISSUE TITLE
Amplify frontend is stuck at "Generating" with no error before timeout

### ISSUE THREAD

**Issue by JosephVasse** [aws-amplify/amplify-console#2300]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d32kjr92bw8zhw

### Region

eu-west-1

### Amplify Console feature

Custom builds

### Describe the bug

Hello, 

We're experiencing an issue with frontend deployment. 
Our prod branch fails to build for no reasons (timing out). with no error message. 

We've tried to disconnect it and reconnect it. 
We've tried to delete the frontend branch and recreate it 
But nothing works. 

We have the same git repo on other frontend branches that is deploying perfectly. 

The "generation" step is stuck at :
``` [INFO]: [0mAmplify AppID found: d32kjr92bw8zhw. Amplify App name is: Villeo[0m ```

And then it timeouts. 
We've tried to increase the timeout duration from 30mins to 60 but it didn't change anything. (Normal build used to take around 5-6 mins) 

We havent done any changes to the git repo before the error occurs. 

### Expected behavior

We expect the console to build the frontend or at least to output any error or warning before timing out. 

### Reproduction steps

1. take our repo
2. Connect it to a frontend branch
3. Try to deploy it
4. fails

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run generate
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*


```
```


### Additional information

As I said, we've other branches that are working fine
The bug occurred without any modification from us.
