### ISSUE TITLE
Feature request: Use custom domain in PR comment for preview link

### ISSUE THREAD

**Issue by d-luk** [aws-amplify/amplify-console#2301]
**Is your feature request related to a problem? Please describe.**
When a PR is created, the AWS Amplify GitHub bot comments the preview URL, as added in #264. This is great, except that we are using a custom domain.

![image](https://user-images.githubusercontent.com/14964441/136014627-28835780-4383-41f9-bdce-097ce95fdf6d.png)

So the comment mentions `https://pr-{PR}.{APP_ID}.amplifyapp.com`, while it should be `https://pr-{PR}.example.com`.

This is important for us because our app does not work on the amplifyapp.com domain due to CORS restrictions, so we must use our custom domain.

**Describe the solution you'd like**
Please allow configuring the PR bot to use a custom domain.

**Comment by hloriana** [comment]
Hi Duncan! 👋🏽  Thanks for raising this, we will review this feature request further with the team.

**Comment by mbuffoQSR** [comment]
Any other news or updates? Or does anyone have a workaround that drags in the correct link each time?

**Comment by andreadeluisi-ryte** [comment]
> Hi Duncan! 👋🏽 Thanks for raising this feature request. Currently, the Web Previews feature is only available for Amplify apps connected to custom domains managed by Amazon Route 53. We will review this feature request further with the team. 🙂

Hi @hloriana , have you discussed this feature with the team? We also would love to use such a feature to avoid CORS restrictions.

**Comment by santiagoaguiar** [comment]
Same issue here. We were able to create previews under the custom domain (and the Preview URL in the AWS Console actually shows the right domain), but the comment is still sent with the amplify domain. This would be quite important for us to resolve, as it creates unnecessary friction and confusion with the dev team.

**Comment by sorokinvj** [comment]
@santiagoaguiar how do you guys set it up to use custom domain for previews? I connected our domain successfully, but pr previews are still created on *.amplifyapp.com which yeah due to CORS issues are not what we want at all.

**Comment by mbuffoQSR** [comment]
@sorokinvj if you have a domain registered in route 53 you can connect it in the domain management page from the amplify page on the AWS site. Then on gh I just wrote a bot that would post the correct link based on the branch name since our branches + prs are named predictably

**Comment by santiagoaguiar** [comment]
@sorokinvj we had to enable branch deployments for all the PRs (this was unexpected, I would have expected just enabling previews would be enough). 

That being said, we dropped this as we run into other issues:
1. (this issue) The comment was confusing for users, we attempted to hack it through GitHub actions to edit the message but amplify keep posting new ones. We opted to minimize Amplify comment and add ours which did the trick but was quite ugly.
2. Most of our PRs are created from branches with `/` in the name. For some reason, custom domains where not created for those PRs, which made the feature unusable for us. We did most of the setup on a branch without a `/` on it so we caught this a bit later in the process...

Honestly, this was something we expected to be simple and ended up spending more time that we wanted on it. We might do another pass at this later, or just move to something else.

**Comment by dranes** [comment]
Any update on this issue? We are experiencing the same problem

**Comment by alerojasv147** [comment]
Any updates on this issues? I was able to connect the PR Previews to my custom domain but in Github the bot added a message that is displaying the amplify domain.

<img width="937" alt="image" src="https://github.com/aws-amplify/amplify-hosting/assets/5098950/c31f0647-815e-48e7-bff4-0b7925d73b8a">

**Comment by nikki-quant** [comment]
+1 I would also prefer to have the domain name in the bot comment either configurable or default to using a custom domain if there is a custom domain present.

**Comment by OrenMe** [comment]
+1 as well, we have a use case where domains are allow listed for CORS headers and the comments are basically useless and confusing

**Comment by dranes** [comment]
We ended up using a GitHub action to try to fix the issue. 

```
on:
  issue_comment:
    types: [created]
jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request &&  contains(github.event.comment.user.login, 'aws-amplify-us-east-1[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo trying to edit comment on PR $NUMBER $USER_ID $COMMENT_ID
        env:
          USER_ID: ${{ github.event.comment.user.login }}
          COMMENT_ID: ${{ github.event.comment.id }}
          NUMBER: ${{ github.event.issue.number }}
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          edit-mode: replace
          comment-id: ${{github.event.comment.id}}
          body: |
            This pull request is automatically being deployed by Amplify Hosting ([learn more](https://aws.amazon.com/amplify/hosting/)).<br/><br/>Access this pull request here: https://pr-${{github.event.issue.number}}.example.com
```
