### ISSUE TITLE
Changes to repository trigger successful build stages but don't deploy

### ISSUE THREAD

**Issue by juliandm** [aws-amplify/amplify-console#2314]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

drsiatfi8euxy

### Region

eu-central-1

### Amplify Console feature

Build settings

### Describe the bug

I want to deploy changes to my frontend code to the s3 bucket that was created by the "hosting" cloudformation scripts of amplify.

However the build only seems to arrive in s3 when doing a manual `amplify publish`.
If i trigger the pipeline by a push to the repository only the backend changes are deployed, the frontend is built, but never deployed.

the build directory is called build in the project root.
The console output is:

```
2021-10-11T20:25:30 [INFO]: Beginning deployment for application xxxxxxxx, branch:dev, buildId 0000000019
2021-10-11T20:25:31 [INFO]: Got archive: 6648861 bytes
2021-10-11T20:25:32 [INFO]: Deployment complete

```
suggesting that it always takes some kind of cache but ignores the artifacts.

### Expected behavior

the deploy stage should actually deploy changes to the s3 bucket hosting the frontend

### Reproduction steps

1. make a change to index.html to the repository, commit & push
2. wait for all stages to finish successfully
3. validate in the s3 hostingbucket, that the change doesn't appear in index.html

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build

  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
