### ISSUE TITLE
Nextjs Github Build fails, deletes Amplify App

### ISSUE THREAD

**Issue by vivadel-vivek** [aws-amplify/amplify-console#2330]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d24emid7ho6933 

### Region

us-east-1

### Amplify Console feature

Custom builds

### Describe the bug

AWS Amplify deploy through the Amplify console does not build my app - rather deletes the app in Amplify.

I have attempted a few times to deploy with github integration on branch Main and to deploy manually with a zipped file, with the same behavior for both.

I am attempting to deploy a very simple next-js application. Just a landing page and an email api route.

On following the steps to create the app, I hit deploy and the site goes into pre-build steps. These appear to complete. It is then in the build steps that some error hangs - it gets stuck on collecting fresh packages, and on refreshing the page my entire app is gone. I have also tried this with manual deployment.

Dependencies and scripts for build are below:

  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@chakra-ui/icons": "^1.0.15",
    "@chakra-ui/react": "^1.6.7",
    "@emotion/react": "11",
    "@emotion/styled": "11",
    "@fontsource/inter": "^4.5.0",
    "@fontsource/oxygen": "^4.5.0",
    "axios": "^0.23.0",
    "framer-motion": "4",
    "next": "11.1.2",
    "nodemailer": "^6.7.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "^4.2.0",
    "sharp": "^0.29.1"
  },
  "devDependencies": {
    "@types/react": "^17.0.21",
    "typescript": "^4.4.3"
  }

### Expected behavior

On integrating with github and deploying, my app should be built successfully. It is not, and in fact deletes the app on Amplify altogether.

### Reproduction steps

1. Go to amplify console
2. Connect github
3. Choose application with next/chakra/nodemailer/etc packages as above
4. Deploy
5. Wait for deployment to hang in build steps
6. Refresh page to see your app gone

### Build Settings

```yaml
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@chakra-ui/icons": "^1.0.15",
    "@chakra-ui/react": "^1.6.7",
    "@emotion/react": "11",
    "@emotion/styled": "11",
    "@fontsource/inter": "^4.5.0",
    "@fontsource/oxygen": "^4.5.0",
    "axios": "^0.23.0",
    "framer-motion": "4",
    "next": "11.1.2",
    "nodemailer": "^6.7.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-icons": "^4.2.0",
    "sharp": "^0.29.1"
  },
  "devDependencies": {
    "@types/react": "^17.0.21",
    "typescript": "^4.4.3"
  }
```
