### ISSUE TITLE
NextJs + Cypress : CICD failing/timing out on Test stage

### ISSUE THREAD

**Issue by DiegoMcDipster** [aws-amplify/amplify-console#2358]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-central-1:292402550639:apps/d10ug9vks09yld

### Region

eu-central-1

### Amplify Console feature

E2E tests

### Describe the bug

My NextJs app is failing to deploy on the Test stage. It just seems to hang and then times out.  Though this is my speculation as I don't see that in the log. 

Clicking on the 'View Cypress Result' doesn't do anything.
Clicking on 'Download Artifacts' gives this html:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
d2sy3vb2cuv0oo/main/0000000002/TEST/artifacts/testArtifacts.zip
</Key>
<RequestId>KWKJHX5Y3A6092G2</RequestId>
<HostId>
10NsoZVmJX3g3+UZSTDrTDuePQwKjbASGYS33Dq/xyENQhB7jCfaoksFZkwSFaclvQhkYuVddoc=
</HostId>
</Error>
```

Here's the Test stage log:
                                 # Starting phase: preTest
                                 # Executing command: npm ci
2021-10-31T15:59:22.841Z [WARNING]: npm
2021-10-31T15:59:22.842Z [WARNING]: WARN prepare removing existing node_modules/ before installation
2021-10-31T15:59:29.275Z [INFO]: > cypress@8.7.0 postinstall /codebuild/output/src296374479/src/next-amp-cypress/node_modules/cypress
                                 > node index.js --exec install
2021-10-31T15:59:29.643Z [INFO]: 
2021-10-31T15:59:29.643Z [INFO]: Cypress 8.7.0 is installed in /root/.cache/Cypress/8.7.0
2021-10-31T15:59:29.791Z [INFO]: > core-js-pure@3.19.0 postinstall /codebuild/output/src296374479/src/next-amp-cypress/node_modules/core-js-pure
                                 > node -e "try{require('./postinstall')}catch(e){}"
2021-10-31T15:59:29.830Z [INFO]: [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
                                 [96mThe project needs your help! Please consider supporting of core-js:[0m
                                 [96m>[94m https://opencollective.com/core-js [0m
                                 [96m>[94m https://patreon.com/zloirock [0m
                                 [96m>[94m https://paypal.me/zloirock [0m
                                 [96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
                                 [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2021-10-31T15:59:29.912Z [INFO]: added 603 packages in 7.088s
2021-10-31T15:59:29.923Z [INFO]: # Executing command: npm install wait-on
2021-10-31T15:59:31.182Z [WARNING]: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2021-10-31T15:59:34.652Z [WARNING]: npm
2021-10-31T15:59:34.655Z [WARNING]: WARN @babel/plugin-syntax-jsx@7.14.5 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.656Z [WARNING]: npm
2021-10-31T15:59:34.656Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of react@0.0.0-experimental-3c4c1c470-20211021 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.663Z [WARNING]: npm
2021-10-31T15:59:34.663Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of react-dom@0.0.0-experimental-3c4c1c470-20211021 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.667Z [WARNING]: npm
2021-10-31T15:59:34.667Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of webpack@^4.43.0 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.673Z [WARNING]: npm
2021-10-31T15:59:34.673Z [WARNING]: WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.674Z [WARNING]: 
2021-10-31T15:59:34.674Z [INFO]: + wait-on@6.0.0
                                 added 10 packages from 12 contributors and audited 613 packages in 4.447s
2021-10-31T15:59:34.816Z [INFO]: 102 packages are looking for funding
                                 run `npm fund` for details
2021-10-31T15:59:34.816Z [INFO]: found 0 vulnerabilities
2021-10-31T15:59:34.828Z [INFO]: # Executing command: npm install pm2
2021-10-31T15:59:41.016Z [WARNING]: npm
2021-10-31T15:59:34.655Z [WARNING]: WARN @babel/plugin-syntax-jsx@7.14.5 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.656Z [WARNING]: npm
2021-10-31T15:59:34.656Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of react@0.0.0-experimental-3c4c1c470-20211021 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.663Z [WARNING]: npm
2021-10-31T15:59:34.663Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of react-dom@0.0.0-experimental-3c4c1c470-20211021 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.667Z [WARNING]: npm
2021-10-31T15:59:34.667Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of webpack@^4.43.0 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.673Z [WARNING]: npm
2021-10-31T15:59:34.673Z [WARNING]: WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:34.674Z [WARNING]: 
2021-10-31T15:59:34.674Z [INFO]: + wait-on@6.0.0
                                 added 10 packages from 12 contributors and audited 613 packages in 4.447s
2021-10-31T15:59:34.816Z [INFO]: 102 packages are looking for funding
                                 run `npm fund` for details
2021-10-31T15:59:34.816Z [INFO]: found 0 vulnerabilities
2021-10-31T15:59:34.828Z [INFO]: # Executing command: npm install pm2
2021-10-31T15:59:41.016Z [WARNING]: npm
2021-10-31T15:59:41.018Z [WARNING]: WARN @babel/plugin-syntax-jsx@7.14.5 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:41.022Z [WARNING]: npm WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of react@0.0.0-experimental-3c4c1c470-20211021 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:41.026Z [WARNING]: npm
2021-10-31T15:59:41.027Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of react-dom@0.0.0-experimental-3c4c1c470-20211021 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:41.031Z [WARNING]: npm
2021-10-31T15:59:41.031Z [WARNING]: WARN react-server-dom-webpack@0.0.0-experimental-3c4c1c470-20211021 requires a peer of webpack@^4.43.0 but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:41.037Z [WARNING]: npm
2021-10-31T15:59:41.037Z [WARNING]: WARN tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2021-10-31T15:59:41.037Z [WARNING]: 
2021-10-31T15:59:41.039Z [INFO]: + pm2@5.1.2
                                 added 165 packages from 144 contributors and audited 778 packages in 5.903s
2021-10-31T15:59:41.210Z [INFO]: 104 packages are looking for funding
                                 run `npm fund` for details
2021-10-31T15:59:41.210Z [INFO]: found 0 vulnerabilities
2021-10-31T15:59:41.241Z [INFO]: # Executing command: npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
2021-10-31T15:59:47.277Z [WARNING]: npm

### Expected behavior

The tests should be passed and the app deployed

### Reproduction steps

Follow the tutorial https://aws.amazon.com/blogs/mobile/run-end-to-end-cypress-tests-for-your-fullstack-ci-cd-deployment-with-amplify-console/

With these changes:
- use create-next-app
- during amplify init set: Distribution Directory Path: .next (note: I have tried 'out' too)
- don't add the auth
- create a test to find the heading on the homepage: NextJs and Cypress

```
describe("The homepage", () => {
  it("Has the heading NextJs and Cypress", () => {
    cy.visit("http://localhost:8080");  //note: I tried PORT:3000 too.  neither work
    cy.get("h1").should("contain", "NextJs and Cypress");
  });
});
```

- change index.js to have the heading 'NextJs and Cypress'
- use the default build settings

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:8080'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill
```

### Additional information

Because I couldn't get it to work with NextJs I tested it with create-react-app and it worked!  The deployment ran to completion and I was able to download and view the cypress video.  So this looks like it's specific to the way Amplify builds NextJs apps.

**Comment by DiegoMcDipster** [comment]
It's been almost two weeks... I would really appreciate it if someone could help me with this.

Thanks in advance!

**Comment by hloriana** [comment]
Hi @DiegoMcDipster 👋🏽  We've been working on getting the tests to run with Next apps and were able to do this successfully using this amplify.yaml file. Give this a try and see if you can get your tests to run.

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm install
        - npm install start-server-and-test cypress mocha mochawesome mochawesome-merge mochawesome-report-generator --save-dev
    test:
      commands:
        - npm run build
        - npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'

```
