### ISSUE TITLE
Angular Amplify Frontend Build fails when trying to deploy

### ISSUE THREAD

**Issue by pralivera** [aws-amplify/amplify-console#2368]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dx01a9f9736el

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

I setup amplify deployment with CI/CD for my angular application. amplify backend successfully deployed to amplify console, but frontend gives following error message.

/codebuild/output/src806740382/src/rov-web/amplify.sh: line 18: unexpected EOF while looking for matching `"'
/codebuild/output/src806740382/src/rov-web/amplify.sh: line 19: syntax error: unexpected end of file

Please find attached log file and the amplify.yml file I used for this deployment. 

I tried to fix this but still couldn't find anything. Please help me to fix this. Thank you 

[log (10).txt](https://github.com/aws-amplify/amplify-console/files/7488602/log.10.txt)

### Expected behavior

App should be able to deploy to amplify console. 

### Reproduction steps

1. install amplify with amplify init
2. Added host using amplify hosting add
3. configure CI/CD deployment
4. commit the code to AWS code commit

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    # IMPORTANT - Please verify your build commands
    build:
      - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist/ng-ace
    files:
      - '**/*'
  cache:
    paths: 
    - node_modules/**/*
```
