### ISSUE TITLE
myapp.amplifyapp.com/assets/NOTICES/ 403 or 404 error

### ISSUE THREAD

**Issue by two4zero** [aws-amplify/amplify-console#2374]
**Describe the bug**

- `myapp.amplifyapp.com/assets/NOTICES/`
- 'NOTICES' file error : 403 or 404

**To Reproduce**
1. `flutter create myapp`
2. 'push to github'
3. 'deploy to aws amplify from github repo'
4. `amplify.yml`
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
      - git clone https://github.com/flutter/flutter.git -b stable --depth 1
      - export PATH="$PATH:`pwd`/flutter/bin"
    # IMPORTANT - Please verify your build commands
    build:
      commands:
      - flutter build web
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: build/web/
    files:
      - '**/*'
  cache:
    paths: []
```
5. See error

**Expected behavior**

**Screenshots**

# 403
![403 화면 캡처 2021-11-11 100939](https://user-images.githubusercontent.com/7650492/141218962-2b2cf141-ba62-43f9-bbe6-e7beb4282226.png)

# 404
![chrome2](https://user-images.githubusercontent.com/7650492/141218724-6d7e794d-b05d-40fa-9f19-96e4647b4e36.png)

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[] iOS

<details>

  <summary>Output of <code>flutter doctor -v</code></summary>
  
  ```
>flutter doctor -v
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.282], locale ko-KR)
    • Flutter version 2.5.3 at D:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\test\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31702.278
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\test\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.28.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.282]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 95.0.1020.40

• No issues found!
```

</details>

<details>

  <summary>Dependencies (<code>pubspec.lock</code>)</summary>
  
  ```
  Paste the contents of your "pubspec.lock" file here
  ```

</details>

**Smartphone (please complete the following information):**

**Additional context**

- https://github.com/flutter/flutter/issues/92803

**Comment by Jordan-Nelson** [comment]
Hello @two4zero - I have transferred this issue to amplify-console since this is an issue with hosting a flutter web app, not the amplify-flutter libraries.

I was able to repro this issue with the steps you provided. It might be related to the lack of a file extension on the file. I manually changed `/NOTICES` to `/NOTICES.txt` and I no longer received a 404.

**Comment by two4zero** [comment]
thanks~ @Jordan-Nelson 

cc : @maheshmnj

**Comment by hloriana** [comment]
Hi @two4zero 👋🏽, were you able to resolve the 404 issue by adding the file extension?

**Comment by szymon-lab** [comment]
Hello 👋 
I think I've ran into the same issue recently while deploying react app with face-api-js. The AI model files referenced in `face_recognition_model-weights_manifest.json` have no extension, therefore accessing `/model/face_recognition_model-shard1`  (with Amplify hosting) causes 403 errors. The problem however did not happen with S3 CloudFront hosting.
The problem can be solved by providing extension to files. In my case I have renamed binary model data files adding .bin extension: `face_recognition_model-shard1.bin` and updated json manifect accordingly.

**Comment by Lorenzohidalgo** [comment]
Hey @two4zero, @hloriana,

I might have found a workaround/solution for this.

You need to follow the next two steps:

1. Update Build Settings to rename the `NOTICES` file and references:
```
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - git clone https://github.com/flutter/flutter.git -b stable --depth 1
            - export PATH="$PATH:`pwd`/flutter/bin"
        build:
          commands:
            - flutter build web
            - mv build/web/assets/NOTICES build/web/assets/NOTICES.txt
            - sed -i "s/NOTICES/NOTICES.txt/" build/web/flutter_service_worker.js
      artifacts:
        baseDirectory: build/web/
        files:
          - '**/*'
      cache:
        paths: []
```
3. Set Up the following redirects Redirects:
![image](https://user-images.githubusercontent.com/22448611/187026168-aabe1327-a39f-4a52-8d8e-65bf7f9c42a2.png)

Let me know if there is a better way to set up the redirects 😉

Hope this helps.
