### ISSUE TITLE
There is already a Construct with name 'adminGroupRole' in AmplifyUserPoolGroupStackOutputs

### ISSUE THREAD

**Issue by seunghwako** [aws-amplify/amplify-console#2383]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3u8gr5p05kbef

### Region

ap-northeast-2

### Amplify Console feature

Backend builds

### Describe the bug

This error occurs in the process of pushing and building a new source code in the amplify console. I don't know where the problem came from. I'd appreciate it if you could help me.

### Expected behavior

Backend build should be completed normally and frontend build should be started.

### Reproduction steps

1. push the new source code to github
2. Provisioning from the amplify console
3. Setup build completed.
4. Backend build error.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

![스크린샷 2021-11-16 오후 3 24 27](https://user-images.githubusercontent.com/52697089/141933010-8f651410-f04f-4167-ab42-6b197982687d.png)
