### ISSUE TITLE
Amplify Console deployment failure: Failed to get profile: Profile configuration is missing for: amplify-XXXXX

### ISSUE THREAD

**Issue by jonathanbravecredit** [aws-amplify/amplify-console#2390]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3vym5isdd5k4u 

### Region

us-east-2

### Amplify Console feature

Backend builds

### Describe the bug

I am no longer able to deploy updates to my app as the deployment is failing at the build step with error: ```Failed to get profile: Profile configuration is missing for: amplify-XXXX```. 

This appears to be caused by a conflict between a ```local-aws-info.json``` file that was inadvertently uploaded to our repository some months back. This now appears to cause a build error, as when deploying via the console, it is looking for that specific profile and cannot find it (it's on my local).

### Expected behavior

I would expect when deploying my application via the Amplify Console and through our CI/CD pipeline, that it would ignore the ```local-aws-info.json``` and instead use the backend service role (as normal) to deploy changes to my application.

### Reproduction steps

Merge code into repository synced up for CI/CD in Amplify Console, including the ```local-aws-info.json``` in to the repo and try to deploy via the Amplify Console.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/brave-app
    files:
      - '**/*'
  cache:
```
