### ISSUE TITLE
WebP conversion provided by Next.js image optimization feature seems not working

### ISSUE THREAD

**Issue by jaga810** [aws-amplify/amplify-console#2392]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

https://main.d3pdm8wpju4m0p.amplifyapp.com/

### Region

us-west-2

### Amplify Console feature

Not applicable

### Describe the bug

WebP conversion provided by Next.js image optimization feature [1] seems not working on Amplify Console.
Similar issue is also created in amplify-js repository [2].

[1] https://nextjs.org/docs/basic-features/image-optimization
[2] https://github.com/aws-amplify/amplify-js/issues/7547

### Expected behavior

WebP conversion provided by Next.js image optimization feature [1] works.

### Reproduction steps

1. `npx create-next-app --example image-component image-app`
2. `cd image-app``
3. `npm run dev`
4. Check images are served as WebP type using developer tool as below.
<img width="1466" alt="Screen Shot 2021-11-18 at 18 53 27" src="https://user-images.githubusercontent.com/13917206/142392504-f736a338-e488-46b1-82e1-808868f6bb5b.png">
5. Push image-app directory to your repository.
6. Deploy image-app using Amplify Console with default settings.
7. Check images are served as PNG type using developer tool as below.
<img width="1438" alt="Screen Shot 2021-11-18 at 18 54 58" src="https://user-images.githubusercontent.com/13917206/142392773-2a5251d3-2c96-4a50-8bfd-bcabcf0c5628.png">

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
