### ISSUE TITLE
Lambda triggers are not attached to the Cognito Userpool

### ISSUE THREAD

**Issue by sarahsga** [aws-amplify/amplify-console#2394]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ap-southeast-1

### Amplify Console feature

Backend builds, Build settings

### Describe the bug

I have used amplify-cli to add Cognito auth and attach lambda triggers. When I run `amplify push` locally, it is able to successfully attach those lambda triggers to the Userpool, and I am able to see those in the Userpools > Triggers in the AWS console.
<img width="1095" alt="Screenshot 2021-11-19 at 12 53 14 PM" src="https://user-images.githubusercontent.com/10798986/142586073-ac743af4-ec35-4700-aebf-9a088acf7474.png">

But when I push to git and let Amplify Console deploy a build, the CI passes successfully, but the triggers are not attached to the Userpool.
<img width="1082" alt="Screenshot 2021-11-19 at 12 38 14 PM" src="https://user-images.githubusercontent.com/10798986/142584105-47ca99c6-8b62-44da-912b-7a28cbe284e2.png">

### Expected behavior

`amplifyPush --simple` should be able to attach auth Lambda triggers to the Userpool

### Reproduction steps

1. amplify add auth
2. When it asks: "Do you want to configure Lambda Triggers for Cognito", select all available options
3. Run `amplify push`, let it complete. Then open the Userpool from AWS console > Triggers tab. You should see all the lambda triggers attached to their respective events (i.e. Pre-Signup etc)
4. Commit your changes and push to git, to trigger the Amplify Console CI. Let the CI complete
5. Open the Userpool from AWS console again > Triggers tab. This time, none of the auth events have any trigger attached

### Build Settings

```yaml
version: 1
backend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - amplifyPush --simple
  cache:
    paths:
      - node_modules/**/*
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
```


### Additional information

_No response_
