### ISSUE TITLE
Frontend build stuck with : Select the authentication method you want to use: 

### ISSUE THREAD

**Issue by tinni95** [aws-amplify/amplify-console#2407]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d20lfk4nk5h3ir

### Region

eu-central-1

### Describe the bug

Since a few days my front-end deployment is stuck on the build step, with the following text:

                                 # Starting phase: build
2021-11-23T18:29:44.116Z [INFO]: ? Select the authentication method you want to use: (Use arrow keys)
                                 ❯ Amplify Admin UI
                                 AWS profile
                                 AWS access keys

![Screenshot 2021-11-23 at 18 39 22](https://user-images.githubusercontent.com/25687643/143084419-7ecacdae-c6d7-415c-8655-f205fabe5a99.png)

### Expected behavior

I expect the app to build as previously

### Reproduction steps

Don't know how to reproduce this.

### Build Settings

```yaml
---(DEFAULT ONES)---

version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
