### ISSUE TITLE
Automatically tag Next.js SSR specific resources

### ISSUE THREAD

**Issue by Leejjon** [aws-amplify/amplify-console#2410]
**Is your feature request related to a problem? Please describe.**
Our security team wants all resources in AWS to be tagged with our team id, to make it clear who is responsible for what. We have a Next.js SSR app running on amplify and that generates a cloudfront distribution, s3 bucket and multiple lambda's. The names of these things are pretty random like:
2021-10-28T10:50:50 [INFO]: Deploying SSR Resources. Distribution ID: E3DLAQ9F20VOOO. This may take a few minutes...
2021-10-28T10:50:50 [INFO]: Deployed the following resources to your account:
2021-10-28T10:50:50 [INFO]: - CloudFront Domain ID: d7fyp0tgkdsy1
2021-10-28T10:50:50 [INFO]: - SSR Lambda@Edge: wpgm5ri-nntgrmi
2021-10-28T10:50:50 [INFO]: - API Lambda@Edge: wpgm5ri-6s2am77
2021-10-28T10:50:50 [INFO]: - Image Optimization Lambda@Edge: wpgm5ri-tmtk5dh
2021-10-28T10:50:50 [INFO]: - S3 Bucket: wpgm5ri-1toihsk

Everytime we create a branch in our git repository amplify creates an environment, this is all very handig but not so handy if we then need to manually tag it.

**Describe the solution you'd like**
That the tags I specify in the cloudformation of my amplify app are automatically put into the cloudfront, s3 and lambda resources of my Next.js SSR app. I'm not sure if it should copy it from the tags in the amplify app, in the definition of the amplify branch or  AutoBranchCreationConfig.

Example of cloudformation
```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      EnableBranchAutoDeletion: true
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn
      Name: amplify-cloudfront-basic-auth-bug
      Repository: "https://github.com/Leejjon/my-amplify-project"
      AccessToken: !Ref GitHubAccessToken
      Tags: 
        -  Key: Squad
            Value: our-team-name
```

**Additional context**
I work for a media company of 6000+ people and originally fired an support ticket on my aws account, but they replied:
2) Can I give them a better name or tag them so that my colleagues can identify that these buckets belong to my team? 
     ~ Unfortunately you cannot change the names. We will take this as a feature request though.
     ~ You can also open a public Feature Request here: https://github.com/aws-amplify/amplify-console/issues 

So here it is.
