### ISSUE TITLE
[build] Node 16 Frontend NextJS build fails with error: Starting SSR Build... Terminating logging...

### ISSUE THREAD

**Issue by opqpop** [aws-amplify/amplify-console#2412]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d187t7owzjiq4m

### Region

us-east-1

### Amplify Console feature

Backend builds, Build settings, Custom builds

### Describe the bug

Please help escalate this prod breaking bug for us that won't let us deploy prod fixes and new features.

I have a NextJS frontend build setup on Amplify that has been working for months up to 11/16/21 (Build 98: https://console.aws.amazon.com/amplify/home?region=us-east-1#/d187t7owzjiq4m/main/98). We then pushed on 11/24/21 some minor prod changes and couldn't deploy it due to build failing (Build 99: https://console.aws.amazon.com/amplify/home?region=us-east-1#/d187t7owzjiq4m/main/99). 

The error logs aren't useful, it just says "Terminating logging..." after "Starting SSR Build...", and we are stumped on how to debug what's causing the build to break all of a sudden. All our builds since then fail because of this issue.

Code changes are minor and mostly just javascript refactoring, so I think this this is some client upgrade / versioning / amplify issue that happened between 11/16 - 11/24.

- Code changes: 
![github com_opqpop_flueth_pull_447_files](https://user-images.githubusercontent.com/5566843/143505968-82302964-b94c-4b71-b9cf-36109768e044.png)

Unhelpful logs that just says "Terminating logging..." after "Starting SSR Build...

```
2021-11-25T05:41:09.928Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-11-25T05:41:10.136Z [INFO]: Starting SSR Build...
Terminating logging...
```

Full log: 
[log (5).txt](https://github.com/aws-amplify/amplify-console/files/7605455/log.5.txt)
 

### Expected behavior

Logging output should show exact error instead of "Terminating logging..."

### Reproduction steps

All our builds are now failing since the last successful 11/16/21. I think I just need to know what the error is at the build step and I can probably figure out the fix. Unfortunately the amplify console logging is not outputting the error.

### Build Settings

```yaml
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install && nvm use
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend
```

### Additional information

In the past, I've seen similar issues, and a fix for me was I forgot some env variables that was needed for building (such as FontAwesome env variables to download fontawesome pro package). I don't think this is relevant this time around though, since I haven't made any changes that would require new env variables during the build for installing new packages.

**Comment by ciceropablo** [comment]
I have the same problem.
Any news about it?

**Comment by wellguimaraes** [comment]
Same problem here 😢

**Comment by wellguimaraes** [comment]
Tried even a very basic Next app with SSR and the problem remains

**Comment by zibra** [comment]
+1

**Comment by wellguimaraes** [comment]
Apparently, the problem is **happening on a specific region** (`us-east-1` at least). I've just tried recreating the app on `us-west-1` and the build step succeeded.

**Comment by wellguimaraes** [comment]
Errrr, not anymore... Failing everywhere now...

**Comment by mahmoudmiz** [comment]
same problem as well!

**Comment by Rafcin** [comment]
@opqpop @wellguimaraes @che-ri @ciceropablo @zibra

Can you add your package json, amplify build yml, next config, and what type of repo you are using if you're allowed to? This seems to be a common issue. 

I'm currently deploying a NextJS monorepo with NX and according to the amplify team it's a problem with `npx serverless` just failing.

**Comment by Rafcin** [comment]
Also stay away from deploying NextJs versions 12.0.1, 12.0.2 and 12.0.3 due to rust compiler issues. 12.0.4 should be stable and 12.0.5-canary.0 is also stable.

**Comment by opqpop** [comment]
> @opqpop @wellguimaraes @che-ri @ciceropablo @zibra
> 
> Can you add your package json, amplify build yml, next config, and what type of repo you are using if you're allowed to? This seems to be a common issue.
> 

package.json: https://gist.github.com/opqpop/a53282aaab476d56ccd5589d25541c9e
package-lock.json: https://gist.github.com/opqpop/27fa75baf64723b41b46dfcc3668080b
next.config.js: https://gist.github.com/opqpop/333456b74f1daf639a0e38aaf0d8d509
type of repo: github connected on amplify

amplify.yml

```
version: 1
applications:
  - backend:
      phases:
        build:
          commands:
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - nvm install && nvm use
            - npm install
        build:
          commands:
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: frontend
```

npm list
```
(venv) winston@Winstons-MacBook-Pro ~/f/frontend (bowza11)> npm list                                                                                                                                                                                                  11:15:50
directory_react_theme@1.1.0 /Users/winston/flueth/frontend
+-- @babel/cli@7.15.7
+-- @babel/core@7.15.5
+-- @babel/polyfill@7.12.1
+-- @babel/preset-env@7.15.6
+-- @babel/preset-react@7.14.5
+-- @fortawesome/fontawesome-free@5.15.4
+-- @fortawesome/fontawesome-pro@5.15.4
+-- @fortawesome/fontawesome-svg-core@1.2.36
+-- @fortawesome/free-solid-svg-icons@5.15.4
+-- @fortawesome/react-fontawesome@0.1.15
+-- @types/google-maps@3.2.3
+-- aws-amplify@4.2.10
+-- babel-loader@8.2.2
+-- babel-plugin-macros@3.1.0
+-- babel-plugin-relay@12.0.0
+-- babel-preset-react-app@10.0.0
+-- detect-file@1.0.0
+-- google-maps-react@2.0.6
+-- graphql@15.6.0
+-- hsl-to-hex@1.0.0
+-- leaflet@1.7.1
+-- lodash.clonedeep@4.5.0
+-- moment-timezone@0.5.33
+-- next-compose-plugins@2.2.1
+-- next-google-fonts@1.2.1
+-- next-react-svg@1.1.3
+-- next@11.0.1
+-- nouislider@15.4.0
+-- nprogress@0.2.0
+-- object-fit-images@3.2.4
+-- prettier@2.4.1
+-- react-dates@21.8.0
+-- react-dom@17.0.2
+-- react-dropzone@11.4.0
+-- react-error-boundary@3.1.3
+-- react-ga@3.3.0
+-- react-hook-form@7.15.4
+-- react-id-swiper@4.0.0
+-- react-image-lightbox@5.1.4
+-- react-leaflet@3.2.1
+-- react-loading-overlay@1.0.1
+-- react-outside-click-handler@1.3.0
+-- react-places-autocomplete@7.3.0
+-- react-relay@12.0.0
+-- react-scroll@1.8.4
+-- react-select@4.3.1
+-- react-syntax-highlighter@15.4.4
+-- react@17.0.2
+-- reactstrap@8.10.0
+-- relay-compiler@12.0.0
+-- relay-config@12.0.0
+-- relay-runtime@12.0.0
+-- sass@1.42.0
+-- styled-components@5.3.1
+-- swiper@6.8.4
`-- wnumb@1.2.0
```

Note I've always used build settings NextJS version set to 10 and it always worked, but I've been using Next 11.0.1 so not sure why it worked. Anyways, I also tried setting NextJS version to latest and got same error.

Let me know if you need anything else. Thanks for the help!
