### ISSUE TITLE
Amplify build frontend phase not installing packages

### ISSUE THREAD

**Issue by hhemmati81** [aws-amplify/amplify-console#2418]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:us-west-2:817078499050:apps/d656n35c0hsyb

### Region

us-west-2

### Amplify Console feature

Build settings

### Describe the bug

Building frontend phase seems to be skipping the yarn install. I first noticed when I was pushing an update to our live site. It kept saying a package is missing. For a test, I built a new branch and deployed it from scratch, and noticed none of the yarn packages were installed.

I have even tried switching to npm install instead of yarn install and it's doing the same thing. Removing the cache setting from the build settings is not fixing this problem either.

### Expected behavior

It should be installing all the packages before building the site.

### Reproduction steps

push changes to the Git repo.

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by hhemmati81** [comment]
Here is a screenshot of the console.
![image](https://user-images.githubusercontent.com/67350345/144140587-bc5b06a4-46c5-4649-836c-b6705efd358d.png)

It starts the preBuild and then ends without installing packages.

Here is a screenshot of the previous build where it worked properly.
![image](https://user-images.githubusercontent.com/67350345/144140705-b2410034-67f6-4efb-a397-567d21a30fa9.png)

As you can see it executed the command yarn install.

**Comment by hloriana** [comment]
Hi @hhemmati81 It looks like you have a typo in your build settings, the `commands` is missing a colon:

```
frontend:
  phases:
    preBuild:
      commands
        - yarn install
```
