### ISSUE TITLE
Caching for `.next/` does not work properly

### ISSUE THREAD

**Issue by esplo** [aws-amplify/amplify-console#2436]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d21r43dw0zppd5

### Region

ap-northeast-1

### Amplify Console feature

Build settings

### Describe the bug

I have put `.next/cache/**/*` into `cache` section in `amplify.yml`, however, `Frontend` section in `Build` logs continuously shows `warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache`. This makes build time longer than expected.
![Screen Shot 2021-12-08 at 18 13 49](https://user-images.githubusercontent.com/1843532/145181406-b8312081-45de-482b-bb21-94476d75e441.png)

### Expected behavior

Caching for `.next/cache/` is effective, and build becomes faster.

### Reproduction steps

1. Connect a GitHub repository, which contains Next.js and SSR samples
2. Add `- .next/cache/**/*` into cache section in build setting (amplify.yml) in AWS Console
3. Trigger a build by pushing some modifications to GitHub
4. See the build progress
5. When the build is completed, inspect log messages in `Build` -> `Frontend`

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```
