### ISSUE TITLE
Next.js SSR monorepo: No ssrResources.json file

### ISSUE THREAD

**Issue by shishkin** [aws-amplify/amplify-console#2449]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify Console feature

Monorepo

### Describe the bug

I'm deploying a next.js app that resides in a folder `packages/myapp` of my repo. I've figured out hot to setup the build settings for `next` to compile the app and the build step succeeds. However, the deploy step fails with the following:

```
2021-12-13T18:06:34 [INFO]: Beginning deployment for application d1vauylx53grjf, branch:main, buildId 0000000005
2021-12-13T18:06:34 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2021-12-13T18:06:34 [ERROR]: {"code":"7","message":"No ssrResources.json file"}
``` 

Where is the missing `ssrResources.json` file suppose to be. Next.js doesn't seem to generate it.

### Expected behavior

Amplify Console detects the app to be Next.js SSR and the build succeeds, so I expect the deploy step to work.

### Reproduction steps

1. Create app via Console

### Build Settings

```yaml
version: 1
applications:
  - appRoot: packages/myapp
    frontend:
      phases:
        preBuild:
          commands:
            - '(cd ../.. && yarn install --immutable)'
        build:
          commands:
            - '(cd ../.. && yarn run build)'
            - pwd
      artifacts:
        baseDirectory: .next
        files:
          - '**/*'
```

### Additional information

I'm using yarn. I've also tried to override the version of `next` to `12.0.7` which I'm using locally, but it had no effect.
