### ISSUE TITLE
Cypress test integration fails

### ISSUE THREAD

**Issue by carlosbvz** [aws-amplify/amplify-console#2453]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1t8f7v7uqkz9e

### Region

us-east-1

### Amplify Console feature

E2E tests

### Describe the bug

I have a Next.js (v "12.0.3",) app, using cypress (v ^9.0.0) with some 2e2 tests.
The Test step during the pipeline process fails with the following logs:
```
One or more tests have failed
```
But no test was actually run.

### Expected behavior

The cypress test suite should be run, flagging those passing or failing tests.
Stop build if there are any failing tests.
Pass build if there are not any failing tests.

### Reproduction steps

Trigger a build by either, manually from the AWS console or by pushing a new feature branch (auto-deploy is set).

### Build Settings

```yaml
...
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - "npx wait-on http://localhost:3000"
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
      - "**/*.png"
      - "**/*.mp4"
```

**Comment by hloriana** [comment]
Hi @carlosbvz 👋🏽, thanks for raising this issue. Testing with SSR apps should work with the following test commands:
```
test:
  phases:
    preTest:
      commands:
        - npm install
        - npm install start-server-and-test cypress mocha mochawesome mochawesome-merge mochawesome-report-generator --save-dev
    test:
      commands:
        - npm run build
        - npx start-test 'npm start' 3000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
 ```
We are working on updating the documentation accordingly. Please let us know if this works for you!
