### ISSUE TITLE
Backend fails - amplify.sh: line 4: amplify: command not found

### ISSUE THREAD

**Issue by dylan-westbury** [aws-amplify/amplify-console#2463]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1wuh42i6cy93b

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

When pushing and amplify consosle triggers automated build, the backend is failing with error: 

# Starting phase: build
2021-12-16T03:12:24.377Z [WARNING]: /codebuild/output/src162106254/src/latertax-web/amplify.sh: line 4: amplify: command not found
2021-12-16T03:12:24.377Z [ERROR]: !!! Build failed
2021-12-16T03:12:24.377Z [ERROR]: !!! Non-Zero Exit Code detected
2021-12-16T03:12:24.378Z [INFO]: # Starting environment caching...
2021-12-16T03:12:24.378Z [INFO]: # Uploading environment cache artifact...
2021-12-16T03:12:24.470Z [INFO]: # Environment caching completed
Terminating logging...

### Expected behavior

Build should not fail

### Reproduction steps

1. push to branch that triggers build that was previously deploying

**Comment by dylan-westbury** [comment]
Errors with this build script: 

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

**Comment by dylan-westbury** [comment]
I tried disconnecting and reconnecting branch but still same error

**Comment by dylan-westbury** [comment]
Hmmm I disabled the backend build by commenting out `amplifyPush --simple`

There was then an error because I did not have environment variable when accessing github private package. I added that to amplify console and am using this build script: 

```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - npm install -g npm@latest
        - npm install
    build:
      commands:
        - nvm use $VERSION_NODE_12
        - node -v
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

Seems to be working now 🤷‍♂️
