### ISSUE TITLE
Amplify App completely missing

### ISSUE THREAD

**Issue by neoplastic** [aws-amplify/amplify-console#2472]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dt2na4z2tucrx (pasted from route53 records... Not sure this is the app id we can no longer access it)

### Region

us-east-1

### Amplify Console feature

Not applicable

### Describe the bug

After the power outage on the 22nd December 2021 our amplify app has disappeared, we can't get to the app using the url either.

We tried creating a new app (d1mkvohb1102nt) and it created, we updated the env variables, rebuilt and the site works but when changing the domain the error stated that the domain was already used by amplify (our previous build) and when navigating away from amplify, the new app also disappeared (but the site is still active) 

### Expected behavior

The Amplify app shows in the AWS Amplify console and the website is accessible via its cloudfront distribution

### Reproduction steps

1. Create a power surge in the AWS datacenter?

### Build Settings

```yaml
version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands:
            - cat .env.production
            - nvm install 14.17.6
            - nvm use 14.17.6
            - yarn install
        build:
          commands:
            - yarn run lint
            - echo $PWD
            - yarn run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
    appRoot: app
```

### Additional information

<img width="1365" alt="Screen Shot 2021-12-23 at 7 17 26 am" src="https://user-images.githubusercontent.com/1312607/147150439-5cf9af07-dd76-40f9-b05b-66aa17408b99.png">
