### ISSUE TITLE
503 response occured when page using react-three/processing on Next.js

### ISSUE THREAD

**Issue by fluixyz-unnatural** [aws-amplify/amplify-console#2477]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:ap-northeast-1:115531481070:apps/d3sjv73f449jem

### Region

ap-northeast-1

### Amplify Console feature

Not applicable

### Describe the bug

I'm trying to create a web page using Next.js, react-three/fiber, and react-three/processing, but I'm getting a 503 error when accessing the page using EffectComposer.

After a lot of testing, the following code is causing the problem.
`const a = <EffectComposer />`

In the build environment, I ran `ls -R . /.next` in the build environment and it built fine, but when I looked at the S3 bucket associated with Amplify, the HTML file was not generated under /static-pages only for the page with the corresponding code.
When I host the same repository on Vercel, it works fine, so I think the problem is in the deployment of Amplify.

### Expected behavior

The generated static file is placed in S3 and responds properly to requests without 503 errors.

### Reproduction steps

1. npx create-next-app <project_name>
2. npm install @react-three/fiber @react-three/processing
3. add`const a = <EffectComposer />` in index.js
4. Hosting with Amplify

### Build Settings

```yaml
## amplify.yml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

## Build image settings
Next.js version latest
Node.js version 12
```
