### ISSUE TITLE
Build fails with `Property 'api' does not exist on type 'AmplifyDependentResourcesAttributes'`

### ISSUE THREAD

**Issue by erikash** [aws-amplify/amplify-console#2478]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-west-1:334636241066:apps/d2wc0j9pvf76ob

### Region

eu-west-1

### Amplify Console feature

Backend builds

### Describe the bug

I've successfully added Amplify to my Create React App application and was able to deploy a backend with AppSync, Functions and Custom categories using `amplify push` from my computer.

I'm using the latest version of Amplify CLI: 7.6.5

I've setup fullstack continues deployment via the Amplify Console.

Unfortunately the build fails with `Property 'api' does not exist on type 'AmplifyDependentResourcesAttributes'`.

I've tried to redeploy a number of times and still get this error.

The `amplify-dependent-resources-ref.d` is stored in git and I've confirmed it contains:
```
export type AmplifyDependentResourcesAttributes = {
    "api": {
        "mukdam": {
            "GraphQLAPIIdOutput": "string",
            "GraphQLAPIEndpointOutput": "string"
        }
    },
    "function": {
        "newsletterSubscriptions": {
            "Name": "string",
            "Arn": "string",
            "Region": "string",
            "LambdaExecutionRole": "string"
        }
    }
}
```

I've also tried deleting it and running `amplify custom build` which regenerated the file with exactly the same data.

Please find the `cdk-stack.ts` and `amplify-dependent-resources-ref.d` attached files [project.zip](https://github.com/aws-amplify/amplify-console/files/7798266/project.zip)

### Expected behavior

The build should pass just like when I run `amplify push` and `amplify custom build` locally.

### Reproduction steps

1. Create an Api category
2. Create a Custom category
3. import the generated resource:
```
const dependencies: AmplifyDependentResourcesAttributes = AmplifyHelpers.addResourceDependency(this,
            amplifyResourceProps.category,
            amplifyResourceProps.resourceName,
            [
                {
                    category: "api",
                    resourceName: "mukdam"
                } /* add more dependencies as needed */]
        );
```
4. initialize a `cdk.Fn.ref`: `const apiGraphQLAPIIdOutput = cdk.Fn.ref(dependencies.api.mukdam.GraphQLAPIIdOutput)`
5. Enable full stack build from the Amplify Console.

### Build Settings

```yaml
aversion: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
