### ISSUE TITLE
In Build step, No further progress in the Git SSH Key acquired

### ISSUE THREAD

**Issue by yuhs0** [aws-amplify/amplify-console#2480]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dcfjuh6wgs4cy/feature-yarn-berry-migration/12?step=BUILD

### Region

ap-northeast-2

### Amplify Console feature

Custom builds

### Describe the bug

When Build phase repository clone, No further progress in the Git SSH Key acquired phase.

https://ap-northeast-2.console.aws.amazon.com/amplify/home?region=ap-northeast-2&code=81119665a63395e9080c#/dcfjuh6wgs4cy/feature-yarn-berry-migration/12?step=BUILD

### Expected behavior

Progress next step.
Then print result Error or Sucess.

### Reproduction steps

1. Push deploy button

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 16
        # - echo -e "@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}" > .npmrc
        # - yarn install
        - yarn set version berry
        # - yarn config set 'nodeLinker' node-modules
        - yarn config set 'npmScopes.fortawesome.npmRegistryServer' "https://npm.fontawesome.com/"
        - yarn config set 'npmScopes.fortawesome.npmAlwaysAuth' true
        - yarn config set 'npmScopes.fortawesome.npmAuthToken' "$FONTAWESOME_NPM_AUTH_TOKEN"
        - yarn config set 'packageExtensions.babel-preset-react-app@*.dependencies.@babel/plugin-proposal-private-property-in-object' "*"
        # - yarn install
        - YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
    build:
      commands:
        - echo "REACT_APP_GLOB_API_URL=$REACT_APP_GLOB_API_URL" >> .env.production
        - echo "REACT_APP_GLOB_API_URL_PREFIX=$REACT_APP_GLOB_API_URL_PREFIX" >> .env.production
        - echo "REACT_APP_MOLOCO_API_URL=$REACT_APP_MOLOCO_API_URL" >> .env.production
        - echo "REACT_APP_MOLOCO_API_URL_PREFIX=$REACT_APP_MOLOCO_API_URL_PREFIX" >> .env.production
        - echo "REACT_APP_GLOB_APP_TITLE=$REACT_APP_GLOB_APP_TITLE" >> .env.production
        - echo "REACT_APP_GLOB_APP_SHORT_NAME=$REACT_APP_GLOB_APP_SHORT_NAME" >> .env.production
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
    #   - node_modules/**/*
      - .yarn/cache/**/*
      - node_modules/**/*
```
