### ISSUE TITLE
auth headless is missing the following inputParams googleClientId, facebookAppId

### ISSUE THREAD

**Issue by hiteshtSociosquares** [aws-amplify/amplify-console#2482]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

db860g8ynuk5s

### Region

us-east-2

### Amplify Console feature

Not applicable

### Describe the bug

When we change redirect url and click on deploy that time failed the deployment, and get this error message.
"auth headless is missing the following inputParams googleClientId, facebookAppId"

=> also try using cli command like

- amplify add auth
- amplify push
while we use amplify push that time same thing happen again and return error 
"auth headless is missing the following inputParams googleClientId, facebookAppId"

### Expected behavior

i need to update my redirect url in section of authorization.

### Reproduction steps

1. change app id and redirect url in authorization section
2. write amplify push command or deploy using amplify studio authorization

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - chmod u+x ./myamplifypush.sh
        - ./myamplifypush.sh
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
