### ISSUE TITLE
Working directory not reset between build phases

### ISSUE THREAD

**Issue by SteeveGL** [aws-amplify/amplify-console#2485]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

ca-central-1

### Amplify Console feature

Build settings

### Describe the bug

Changing current directory in a phase's command affect the next phase.

### Expected behavior

Working directory reset to the root's project directory on every phase.

### Reproduction steps

1. Edit `amplify.yml` as following
```
version: 1

backend:
  phases:
    preBuild:
      commands:
        - echo "$PWD"
        - cd amplify

    build:
      commands:
        - echo "$PWD"

frontend:
  phases:
    preBuild:
      commands:
        - echo "$PWD"

    build:
      commands:
        - echo "$PWD"

```
2. Push to trigger the build
3. Notice the current path not in the project root directory
```
2022-01-04T15:05:07.500Z [INFO]: ## Starting Backend Build
                                 # Starting phase: preBuild
                                 # Executing command: echo "/codebuild/output/src027357002/src/REDEACTED"
                                 /codebuild/output/src027357002/src/REDEACTED
                                 # Executing command: cd amplify
2022-01-04T15:05:07.518Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
2022-01-04T15:05:07.518Z [INFO]: # Executing command: echo "/codebuild/output/src027357002/src/REDEACTED/amplify"
                                 /codebuild/output/src027357002/src/REDEACTED/amplify
2022-01-04T15:05:12.054Z [INFO]: # Completed phase: build
                                 ## Completed Backend Build
                                 ## Starting Frontend Build
                                 # Starting phase: preBuild
                                 # Executing command: echo "/codebuild/output/src027357002/src/REDEACTED/amplify"
                                 /codebuild/output/src027357002/src/REDEACTED/amplify
2022-01-04T15:05:12.056Z [INFO]: # Completed phase: preBuild
                                 # Starting phase: build
                                 # Executing command: echo "/codebuild/output/src027357002/src/REDEACTED/amplify"
                                 /codebuild/output/src027357002/src/REDEACTED/amplify
                                 # Completed phase: build
                                 ## Completed Frontend Build
```

### Build Settings

```yaml
version: 1

backend:
  phases:
    preBuild:
      commands:
        - echo "$PWD"
        - cd amplify

    build:
      commands:
        - echo "$PWD"

frontend:
  phases:
    preBuild:
      commands:
        - echo "$PWD"

    build:
      commands:
        - echo "$PWD"
```

### Additional information

My understanding is phases are useless and all commands are just executed in order. So the build design miss the point to have phases. They should be isolate from each sections to not be affected by unwanted behaviors. "Pre" phase should prepare the environment for the main phase. And main phases should not be affected by the previous main phase. It would be expected to have to install dependencies in `backend` and again in `frontend` as they should not be affected by each others.
