### ISSUE TITLE
How to get my simple ng test command running with chrome headless 

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-console#249]
** Which Category is your question related to? **
Deployment pipeline 

** Provide additional details e.g. code snippets **

in my package.json:
`    "test-ci": "ng test --no-watch --no-progress --browsers=ChromeHeadlessCI",
`
in my karma.conf:
```
browsers: ['Chrome', 'ChromeHeadless', 'ChromeHeadlessCI'],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }
    }
```

my test script is:
`ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
`
in my build settings file:
```
test:
  phases:
    preTest:
      commands:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - npm ci
    test:
      commands:
        - npm run test-ci
  artifacts:
    baseDirectory: dist/my-tests
    files:
      - '**/*'

```
ERROR MESSAGE:
ChromeHeadless have not captured in 60000 ms, killing

I guess the chrome install is not being found on the Linux Image/Machine?
do I need to set chrome_bin in the environment variables? if Yes, what is it?

Thanks for any help

**Comment by Joycehao19** [comment]
Hello @blomm , do you have a sample repo that we could test?

**Comment by blomm** [comment]
Hi @Joycehao19 , not a publicly available one, unfortunately.
All the documentation relates to end to end cypress testing, but I just want to run my unit tests, should be simple.

**Comment by Joycehao19** [comment]
Hi @blomm I can't reproduce this issue. I got `Tests successfully completed` when I tried.

1. Did you edit `files: ['dist/my-tests/**/*.js']` in `karma.conf.js` (or something related)?
2. For ` test script`:  Why did you put ` ng test --no-watch --no-progress --browsers=ChromeHeadless ` instead of `ng test --no-watch --no-progress --browsers=ChromeHeadlessCI` ? 

> There are configuration files for both the Karma JavaScript test runner and Protractor end-to-end testing tool, which you must adjust to start Chrome without sandboxing.
- https://angular.io/guide/testing)

**Comment by blomm** [comment]
Hi @Joycehao19 , 
You raise a good point, actually with this value for artifacts>baseDirectory in the build settings `['dist/my-tests/**/*.js'] `
it failed with folder does not exist, because it didn't, I was doing some experimenting.
I don't thing ng test has any build artifacts (unless I run with coverage reports), but I'm not able to leave this value empty in the build settings.

**Comment by Joycehao19** [comment]
@blomm , 

Q1: I put the folder which contains my test.js 
Q2: I didn't use Puppeteer.

I followed [this link](https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai). [You need to have Chrome 59+.]
In `karma.conf.js`:
```
    browsers: ['Chrome', 'ChromeHeadless', 'ChromeHeadlessCI'],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox']
      }
    },
    files: ['test/**/*.js'],
```
In `amplify.yml`
```
test:
  phases:
    preTest:
      commands:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - npm ci
    test:
      commands:
        - npm run test:ci
  artifacts:
    baseDirectory: test
    files:
      - '**/*'
```

When you test your app locally, could it work?
When I search `ChromeHeadless have not captured in 60000 ms, killing.` , I found some similar issues. You could also take a look and ask them for help: https://github.com/karma-runner/karma-chrome-launcher/issues

**Comment by blomm** [comment]
@Joycehao19 thanks for your continued support
Running the test locally, if I execute '_npm run test-ci_' the tests all pass, but I get
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exotics-client@0.0.0 test-ci: `ng test --no-watch --no-progress --browsers ChromeHeadlessCI`
npm ERR! Exit status 1
```
If instead I execute _ng test --no-watch --no-progress --browsers ChromeHeadlessCI_ the test will pass and not error.  This is very strange, that running through npm scripts causes an error.

So in my amplify build settings I chose to execute that base command _ng test --no-watch --no-progress --browsers ChromeHeadlessCI_  rather than _npm run test-ci_
I also set the test>artifacts>baseDirectory to be _src_ because this doc [](https://docs.aws.amazon.com/amplify/latest/userguide/amplify-console-ug.pdf ) says that:  _artifacts>baseDirectory - The directory from which tests are run._ and my tests are in many different folders, not just a test folder.
Somehow, the test stage passes.  logs show that the pretest steps ran, but no indication of tests actually running, the log file just ends abruptly
![image](https://user-images.githubusercontent.com/364940/69232316-bba49180-0b82-11ea-8303-8ad917c38ecd.png)
But now  the deploy stage fails, no indication of the problem. (Deploy works fine if I don't run tests)
![image](https://user-images.githubusercontent.com/364940/69232152-60729f00-0b82-11ea-8b0d-9f5f2c48f659.png)

**Comment by Joycehao19** [comment]
Hi @blomm , Can you send me you appID and region? Then I can check the build logs of your app. 

For `MaxListenersExceededWarning`, you could try something like eventEmitter.once().

**Comment by blomm** [comment]
Hi @Joycehao19 , thanks very much:
eu-west-1 
dbwksz5yaroo9

**Comment by Joycehao19** [comment]
@blomm Did your app deploy successfully? Build 089 seems like successfully deployed.

**Comment by blomm** [comment]
Hi @Joycehao19 , 
I have my build successfully running, but it's without the test section of the buildSettings. 
I've re-added the test section in build 94, chrome headless is not being found, test phase doesn't fail (but doesn't run any tests), but deploy does fail.
Question: What is the artifacts>baseDirectory for in the test section? does it define where the tests are located? or where the output from running tests will be dumped?

**Comment by blomm** [comment]
Update: so as I had been saying, the Linux build server does not find chrome.
adding this line in prebuild of test secion resolved that, and now I do not get the karma timeout, and my tests run:
`export CHROME_BIN=/usr/bin/google-chrome `

however, my deploy is still failing with the same 3 error lines, (unless I remove the test phase, then it deploys)
```
2019-11-24T16:02:04 [INFO]: Starting Deployment
2019-11-24T16:02:04 [ERROR]: Failed to deploy
2019-11-24T16:02:04 [INFO]: Deployment finished.
```

**Comment by Joycehao19** [comment]
@blomm 
Question: What is the artifacts>baseDirectory for in the test section? does it define where the tests are located? or where the output from running tests will be dumped?

It defines where the tests are located.

Could you please try re-connect the app and edit `amplify.yml` (something like)

```
test:
  artifacts:
    baseDirectory: tests
    files:
      - "**/*.png"
```
The “artifacts:” sub-config needs a baseDirectory, and at least one glob. It can be all - **/* - but that may have undesired effects, as it will attempt to upload the entire test directory, the above example just searches for any .png files, and if there are none, none will be uploaded.

**Comment by blomm** [comment]
Hi @Joycehao19, tests folder fails because this does not exist in my project. If I set src as the baseDirectory, the tests will pass and run, but my deploy fails with the 3 non-descript error messages. 

As an aside, setting src as the folder will also mean that on the console, when I click the 'download artifacts' button i will be able to download everything in src folder.

**Comment by nordinh** [comment]
I'm getting the same error as well when adding the test section to the build script:
`
test:
  phases:
    preTest:
      commands:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - export CHROME_BIN=/usr/bin/google-chrome
        - npm ci
    test:
      commands:
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --reporters=coverage-istanbul,html
        - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  artifacts:
    baseDirectory: test-results
    files:
      - '**/*'
`
Tests pass but deploy fails:
`
2020-04-03T19:39:27 [INFO]: Starting Deployment
2020-04-03T19:39:27 [ERROR]: Failed to deploy
2020-04-03T19:39:27 [INFO]: Deployment finished.
`

**Comment by Joycehao19** [comment]
Hi @nordinh , @david-wallace-croft , would you mind provide your appId and region? (App Setting => General => App ARN => arn:aws:amplify:${Region}:xxxxxxx:apps/${appId}).

**Comment by david-wallace-croft** [comment]
I created a new clean project:
ng new amplify-protractor

arn:aws:amplify:us-east-1:xxxxxxxxxxxx:apps/dd0x2t9ylfft9

**Comment by sintaro** [comment]
Any update?

**Comment by david-wallace-croft** [comment]
I figured it out.  The main problem was a missing configFilePath in the test artifacts section.  Excluding configFilePath causes the test phase to appear to succeed including generating successful test artifacts but with the deploy phase reported as failing for no apparent reason.  I am not sure why configFilePath is required or what it is used for in the context of Angular Protractor tests but it is described here:
https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html

Another lesser issue that I was having was that I needed to first create the directory where the test-results were stored.  My updated amplify.yml test section follows:
```yaml
test:
  phases:
    preTest:
      commands:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - npm ci
        - mkdir -p test-results/e2e
    test:
      commands:
        - npm run e2e
    postTest:
      commands:
        - echo postTest started on `date`
  artifacts:
    baseDirectory: .
    configFilePath: '**/result.json'
    files:
      - 'test-results/e2e/result.json'
```

**Comment by ddouras** [comment]
There is no need to create a test target to your amplify file if you just want to run unit tests. I got this working with following steps:

Set your amplify.yml to be :

frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - npm run test:ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

Add to your karma.conf.js options:

browsers: ['ChromeHeadless'],
customLaunchers: {
 ChromeHeadlessCI: {
   base: 'ChromeHeadless',
   flags: ['--no-sandbox'],
 },
},

Add this script to package.json:

"test:ci": "ng test --no-watch --no-progress --browsers ChromeHeadlessCI"

**Comment by kunalms** [comment]
I was able to get the ng test command working for my project, Thanks to @david-wallace-croft  and @ddouras for pointing me in the right direction.

Here are the steps to correctly configure the unit test to run during test phase of the build:
1. update the amplify.yml
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/ampify-tic-tac-toe
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

test:
  phases:
    preTest:
      commands:
        - npm ci
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
    test:
      commands:
        - npm run test:ci
  artifacts:
      baseDirectory: dist
      files:
        - '**/*'
      configFilePath: '**/jest.config.js'
  cache:
    paths:
      - node_modules/**/*
```

2. update the karma.json
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      jasmine: {
        // you can add configuration options for Jasmine here
        // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
        // for example, you can disable the random execution with `random: false`
        // or set a specific seed with `seed: 4321`
      },
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    jasmineHtmlReporter: {
      suppressAll: true // removes the duplicated traces
    },
    coverageReporter: {
      dir: require('path').join(__dirname, './coverage/tic-tac-toe-amplify'),
      subdir: '.',
      reporters: [
        { type: 'html' },
        { type: 'text-summary' }
      ]
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    customLaunchers: {
      ChromeHeadlessCI: {
        base: 'ChromeHeadless',
        flags: ['--no-sandbox'],
      },
    },
    singleRun: false,
    restartOnFileChange: true
  });
};
```
3. update the package.json and add a new script
```"test:ci": "ng test --no-watch --no-progress --browsers ChromeHeadlessCI",```


The advantage of setting up the project like this would be you separate out the test from build, which is much cleaner approach in my humble opinion.

Hope this helps anyone looking out to get there tests up and running in AWS amplify.
