### ISSUE TITLE
Getting userpool error with no changes to userpool (only graphql api)

### ISSUE THREAD

**Issue by isaac-rosterlab** [aws-amplify/amplify-console#2509]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dnbf8aqkmb1um

### Region

ap-southeast-2

### Amplify Console feature

Backend builds

### Describe the bug

I have not made any changes to my userpool at all. I slightly changed the graphql API, then rebuilt and got this error. Then I tried rebuilding a previous build which was successful and it gave me the same error.

`
2022-01-14T02:57:10.369Z [INFO]: UPDATE_FAILED               UserPool                                                                AWS::Cognito::UserPool     Fri Jan 14 2022 02:57:06 GMT+0000 (Coordinated Universal Time) Invalid AttributeDataType input, consider using the provided AttributeDataType enum. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID:_________________; Proxy: null)
`

### Expected behavior

I think the build should be successful when building previously successful builds. I think when only changing my API, I should not receive a user pool error.

### Reproduction steps

Since I'm not effectively changing the backend at all, I only know how I produced it.
1. run build 160 which was previously successful
2. it fails

### Build Settings

```yaml
I'm using the default build image.

backend:
  phases:
    build:
      commands:
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - amplifyPush --simple
```
