### ISSUE TITLE
Next SSR App was successfully built & deployed, but no resources were created

### ISSUE THREAD

**Issue by sohammondal** [aws-amplify/amplify-console#2523]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dosh7uig5h0qw

### Region

ap-south-1

### Amplify Console feature

Backend builds, Custom builds, Manual deploys

### Describe the bug

Deployment is successful but no resources are created. 

![image](https://user-images.githubusercontent.com/34343502/150170227-f3e0c318-e8ab-4136-87f1-9c7980d0e064.png)

Rebuilt the branch multiple times, even deleted the app & created a new one, but the same issue persists.  

### Expected behavior

Ideally, resources like Cloudfront, Lambda@Edge, S3 should be created and redirect rules to be added. An output log similar to the screenshot below is expected. 

![image](https://user-images.githubusercontent.com/34343502/150170762-9c5de7a5-eb8e-48d3-9852-a7711bff7c60.png)

### Reproduction steps

1. Create a new app
2. Connect with Gitlab
3. Select Repo
4. Select Branch
5. Configure build settings
6. Save & Deploy

### Build Settings

```yaml
// amplify.yml
version: 1
frontend:
    phases:
        preBuild:
            commands:
                - npm i
        build:
            commands:
                - if [ "${AWS_BRANCH}" = "master" ]; then npm run build:production; fi
                - if [ "${AWS_BRANCH}" = "staging" ]; then npm run build:staging; fi
    artifacts:
        baseDirectory: .next
        files:
            - '**/*'
    cache:
        paths:
            - node_modules/**/*
```

### Additional information

It's a Next.js SSR App having version `next:10.0.3`. The `staging` branch is integrated with Amplify. Service Role with `AdministratorAccess-Amplify` policy is also attached properly. 

![image](https://user-images.githubusercontent.com/34343502/150171977-7be941ca-46a4-45ea-817d-b5a6e247d7d2.png)
