### ISSUE TITLE
AWS amplify not reflecting changes in code

### ISSUE THREAD

**Issue by subaruMax** [aws-amplify/amplify-console#2529]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d6wuywv4fhj3t

### Region

us-east-2

### Describe the bug

Hello there, i'v got issues with AWS amplify, trying to update Next.js application, first of all normaly build and deploy takes 10-15 mins, but today it takes 52minutes or more, and finally when build is completed and deployed it doesnt reflect any commited changes, still showing the old app.

2022-01-20T16:58:47 [INFO]: The CloudFront distribution is taking longer than usual to propagate changes globally. The Verify step may not reflect your most recent changes.
2022-01-20T16:58:47 [INFO]: Deployment complete

### Expected behavior

Expected app to be deployed icluding changes from last PR.

### Reproduction steps

1. deploy nextjs app to aws 

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

2022-01-20T16:58:47 [INFO]: The CloudFront distribution is taking longer than usual to propagate changes globally. The Verify step may not reflect your most recent changes.
2022-01-20T16:58:47 [INFO]: Deployment complete
