### ISSUE TITLE
amplify console can't pull custom build image from ECR 

### ISSUE THREAD

**Issue by tomgreenwood1** [aws-amplify/amplify-console#254]
**Describe the bug**
Amplify console fails to pull custom build image from ECR 

**To Reproduce**
1. Push a build image to aws ECR
2. Add the image URI from ECR to amplify console's custom build entry
3. Add ECR permissions to amplify consoles IAM service role
4. Run a build
5. See error: [BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image. CannotPullContainerError: Error response from daemon: pull access denied for xxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/xxxxxx, repository does not exist or may require 'docker login']

**Expected behavior**
I expected it to pull the image and use it to run the build

**Additional context**
I have looked for documentation regarding this but there's nothing [here](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) about any additional steps other than the ones I've done. Why is the _CUSTOM_IMAGE environment variable created? Am I supposed to use it for something? I can find nothing about this in the documentation

My amplify.yaml looks like 
```yaml

version: 0.1
backend:
  phases:
    build:
      commands:
        - ./config-amplify.sh
        - cd app
        - amplifyPush --simple
frontend:
  phases:
    # IMPORTANT - Please verify your build commands
    build:
      commands: 
        - npm install 
        - ./edit_module.sh
        - npm run build

  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: app/dist
    files:
      - '**/*'
  cache:
    paths: []
```
I tried adding a docker login command in a preBuild phase but it made no difference.
