### ISSUE TITLE
Next js App - Deploy failed to complete successfully.

### ISSUE THREAD

**Issue by iqaldebaran** [aws-amplify/amplify-console#2547]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d318zybdqun45x

### Region

us-east-1

### Amplify Console feature

Custom builds, Manual deploys

### Describe the bug

The deployment are failing with the following error:

2022-01-28T00:03:59 [INFO]: Beginning deployment for application d318zybdqun45x, branch:feat/pdfReport, buildId 0000000002
2022-01-28T00:03:59 [INFO]: Cannot find any generated SSR resources to deploy. If you intend for your app to be SSR, please check your app Service Role permissions. Otherwise, please check out our docs on how to setup your app to be detected as SSG (https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#deploy-nextjs-app)
2022-01-28T00:03:59 [ERROR]: {"code":"7","message":"No ssrResources.json file"}

### Expected behavior

Deployment not fail - all green

### Reproduction steps

1.- Commit to github
2.- Start Automatic deployment
3.- Provision - OK
4.- Build - OK
5.- Deploy - FAIL

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

Last week it was working fine, I just made a few changes to the frontend.
Additional data: The master branch passes the deploy, but it does not update the changes in the frontend, it continues to show the previous version of the frontend, it is something very strange.
Clear browsers cache and have tried on other computers.
