### ISSUE TITLE
customHttp.yml Cache-Control directive not applied anymore

### ISSUE THREAD

**Issue by marcolucio** [aws-amplify/amplify-console#2556]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d33tomgegl6zji

### Region

eu-central-1

### Amplify Console feature

Custom headers

### Describe the bug

Hello, 
We found that our custom `Cache-Control` headers are no more applied resulting in `Cache-Control: public, max-age=0, s-maxage=2` for all files. This is very critical for our app performance.
Other headers seems to be applied correctly, or at least the one with '**/*' pattern is applied to all files properly.

Our customHttp.yml is structured like:
```
  - pattern: '**/*.html'
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=120, must-revalidate'

  - pattern: '**/*'
    headers:
      - key: X-Version
        value: '_VERSION_'
```
If I ask by `wget` / `curl` for a single html file our custom `X-Version` header is correctly served, but not the `Cache-Control`  one. It worked properly until last week.

### Expected behavior

Cache-Control headers (or others) should be properly applied by pattern matching.

### Reproduction steps

1. Create a project with a customHttp.yml containing:
```
  - pattern: '**/*.html'
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=120, must-revalidate'

  - pattern: '**/*'
    headers:
      - key: X-Version
        value: '_VERSION_'
```
and a simple test.html file
2. Deploy it using amplify console
3. Ask for http://<domain>/prova.html, the response should contain custom `X-Version: _VERSION_`  + `Cache-Control: public, max-age=0, s-maxage=120, must-revalidate` headers

**Comment by biller-aivy** [comment]
Same for 

```
customHeaders:
  - pattern: '**/*'
    headers:
      - key: Access-Control-Allow-Origin
        value: '*'

```

**Comment by iceye** [comment]
here I'm experiencing the same issue

**Comment by hloriana** [comment]
Hi @marcolucio 👋🏽, thanks for raising this issue. I was able to reproduce this behavior with the `'**/*.html' ` pattern. We are currently investigating this.

**Comment by marcolucio** [comment]
Thank you @hloriana.
Let me know asap, we are heavily relying on caching so this issue is really critical for us. If it could help: our traffic pattern on CDN changed  the 21th of January. Any temporary workaround while waiting for fix is welcome.

**Comment by hloriana** [comment]
@marcolucio I was able to get this to work; have you tried to re-deploy your app to make sure the headers are being picked up?

**Comment by marcolucio** [comment]
@hloriana our last deploy ended at 6.20 CET.

I performed some tests and the `**/*.html` seems to work properly now (it reports `Cache-Control: public, max-age=0, s-maxage=120, must-revalidate`)

Hovever other paths are still reporting the wrong `Cache-Control: public, max-age=0, s-maxage=2`.

If you have a look at our `customHttp.yml` we have also a bunch of paths like:
```
  - pattern: /version.txt
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=300, must-revalidate'

  - pattern: /client/**/*
    headers:
      - key: Cache-Control
        value: 'public, max-age=7200, s-maxage=14400, must-revalidate'
```

They are all reporting the wrong `Cache-Control`.
Let me know if I have to perform more tests or deploys, thank you.

**Comment by ryomtoob** [comment]
I am also experiencing the problem with the `Access-Control-Allow-Origin` header. We didn't make any changes, and it stopped serving the header sometime over last weekend.

**Comment by hloriana** [comment]
@biller-aivy @iceye @ryomtoob can you share your App ID and the region they're deployed in?

**Comment by biller-aivy** [comment]
> @biller-aivy @iceye @ryomtoob can you share your App ID and the region they're deployed in? 

d1fc4aexqs2mpi

eu-central-1

**Comment by ryomtoob** [comment]
dx4a6kvkkrewc
us-east-1

**Comment by marcolucio** [comment]
@hloriana, If it cloud help the problem for us is starting on 26th of Jan at 6.00 AM CET, immediately after the first deploy of the day, thank you

**Comment by iceye** [comment]
@biller-aivy the appid/region is in the first comment from @marcolucio, I try to create a new app with the same code and the issue is still there.

**Comment by biller-aivy** [comment]
reDeplyod the Produktion Branch and now it is working again.

**Comment by ryomtoob** [comment]
I am still having the issue. I tried redeploying, but the header still isn't showing up.

**Comment by iceye** [comment]
Our app App Id d33tomgegl6zji - Region eu-central-1 (is the first comment one from @marcolucio ) too, it's flushing every ~1h but no changes yes

**Comment by hloriana** [comment]
@marcolucio can you please try this pattern:

```
- pattern: version.txt
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=300, must-revalidate'

  - pattern: client/**/*
    headers:
      - key: Cache-Control
        value: 'public, max-age=7200, s-maxage=14400, must-revalidate'

```

If you make this change in the customHttp.yml file please make sure you re-deploy.
