### ISSUE TITLE
Using ruby 2.6+ with jekyll/bundler

### ISSUE THREAD

**Issue by daxenberger** [aws-amplify/amplify-console#2565]
**Please describe which feature you have a question about?**

I am building a static website with a jekyll version that requires ruby 2.5+, but I haven't found a way to do so using the (default) linux:2 build image. Even though I explicitly specified the ruby version in the `Gemfile`, I only see
```
[WARNING]: Your Ruby version is 2.4.6, but your Gemfile specified 2.6.3
[ERROR]: !!! Build failed
[ERROR]: !!! Non-Zero Exit Code detected
```

I also tried setting `VERSION_RUBY_DEFAULT` in the pre-build settings without effect.

**Provide additional details**

The only way I managed to make it work was to set a custom build image. However, using a `jekyll/builder` image doesn't work at all (deployment fails at the Build step without any logs available), so I have to use the plain `ruby` image with a suitable version and `gem install bundler jekyll` in the pre-build settings at every build. This works, but significantly increases build time, so not really a satisfying solution.

**What AWS Services are you utilizing?**

Only working on the Amplify console. 

**Provide additional details e.g. code snippets**

See above.

**Comment by hloriana** [comment]
Hi @daxenberger 👋🏽 thank you for raising this issue. We are investigating this and I will report back with an update.

**Comment by daxenberger** [comment]
Any updates on this one? The issue persists ...

**Comment by RockManJoe64** [comment]
Any updates? I'm also going down this road where I need Ruby 2.7.x to support Jekyll 4.x.

I tried using a custom build image based on Ubuntu.

I was able to successfully build my site in a local docker container running my custom image.

```bash
root@d1a946cccbe6:/working/mysite_repo# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users
on this machine.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching public_suffix 5.0.0
Installing public_suffix 5.0.0
Fetching addressable 2.8.1
Installing addressable 2.8.1
Using bundler 2.1.4
...
Bundle complete! 8 Gemfile dependencies, 35 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

But when I run it in AWS Amplify, it fails with this message:

```bash
                                 # Starting phase: preBuild
2022-10-14T03:47:37.362Z [INFO]: # Executing command: bundle install
2022-10-14T03:47:37.362Z [WARNING]: /codebuild/output/src390886491/src/mysite_repo/amplify.sh: line 13: bundle: command not found
2022-10-14T03:47:37.362Z [ERROR]: !!! Build failed
2022-10-14T03:47:37.362Z [ERROR]: !!! Non-Zero Exit Code detected
2022-10-14T03:47:37.363Z [INFO]: # Starting environment caching...
2022-10-14T03:47:37.363Z [INFO]: # Environment caching completed
Terminating logging...
```

Any ideas why?

**Comment by RockManJoe64** [comment]
I may have found an answer. I modified my build's `amplify.yaml` to the following. Seems that adding the actual rbenv init command helped.

```yaml
version: 1
env:
  variables:
    JEKYLL_ENV: production
frontend:
  phases:
    preBuild:
      commands:
        - eval "$(/root/.rbenv/bin/rbenv init - bash)"
        - rbenv global 2.7.1
        - gem install bundler
        - bundle install
    build:
      commands:
        - bundle exec jekyll build
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```

**Comment by EdjeElectronics** [comment]
Hi @hloriana , I am having the same issue trying to build my Jekyll website with AWS Amplify. It seems the build container is set up to use Ruby v2.6.3, but I need Ruby version 2.7.x or higher. I tried using @RockManJoe64 's solution, but the build log gives me a `/root/.rbenv/bin/rbenv: No such file or directory` error.

How can I set up the build environment to use a more recent version of Ruby?

**Comment by RockManJoe64** [comment]
> Hi @hloriana , I am having the same issue trying to build my Jekyll website with AWS Amplify. It seems the build container is set up to use Ruby v2.6.3, but I need Ruby version 2.7.x or higher. I tried using @RockManJoe64 's solution, but the build log gives me a `/root/.rbenv/bin/rbenv: No such file or directory` error.
> 
> How can I set up the build environment to use a more recent version of Ruby?

Hey @EdjeElectronics so the yaml prebuild commands in my post only work with a custom build image I made. If you're using the base Amplify image then it won't work 😁

**Comment by EdjeElectronics** [comment]
Got it, thanks @RockManJoe64 ! I got the build to work by adding `rvm install 3.1.3` and `rvm use 3.1.3` to the build config:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - rvm install 3.1.3
        - rvm use 3.1.3
        - bundle install
    build:
      commands:
        - bundle exec jekyll build
  artifacts:
    baseDirectory: _site
    files:
      - '**/*'
  cache:
    paths: []
```
