### ISSUE TITLE
Build timed out in preTest phase: Cypress CI Angular project

### ISSUE THREAD

**Issue by ssokl601** [aws-amplify/amplify-console#2587]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3366d4vrmahxd

### Region

us-west-2

### Amplify Console feature

Build settings, E2E tests

### Describe the bug

The build times out during the preTest phase, not always in the same place. It was stalling on the pm2 installation, so I tried without installing pm2 and it made it as far as starting the server on port 4200, but never started the test phase. Build timeout is set to 30 minutes with the last build log entry around 6 minutes in. Repo is using CodeCommit

### Expected behavior

preTest phase should complete and the next phase should begin.

### Reproduction steps

Run CI testing

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/project
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:4200'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

### Additional information

UPDATE: I realized I was waiting on http://localhost:4200 instead of https://localhost:4200 since we start the server with ssl enabled. I changed it to https and now it ran properly! yay!
