### ISSUE TITLE
Build succeeds but backend changes are not deployed

### ISSUE THREAD

**Issue by luiskcs89** [aws-amplify/amplify-console#2589]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1pynf4s98mcr3

### Region

us-east-1

### Amplify Console feature

Backend builds, Build settings, Custom builds

### Describe the bug

The build goes trough all the steps and there are no errors, the Backend section of the Build tab seems to detect the changes like new storage and so on. But the changes are not deployed to the actual backend, I don't see my new tables on dynamo or new code on lambda. etc.

### Expected behavior

Build succeeds and we see all the changes we did to the code and on amplify reflected on the backend and aws services.

### Reproduction steps

1. Just trigger a build with any change in the backend.

### Build Settings

```yaml
version: 0.1
backend:
  phases:
    build:
      commands:
        - "# Execute Amplify CLI with the helper script"
        - chmod u+x ./vertrun-amplifypush.sh
        - ./vertrun-amplifypush.sh
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 12
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

This is happening on all environments. It was working and now all of a sudden it stopped working on all builds.
