### ISSUE TITLE
Amplify Console Build fails - Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by nickeyvee** [aws-amplify/amplify-console#26]
**Describe the bug**
Cannot get my project to build using the amplify console. No obvious causes for the build to fail.

**To Reproduce**
1. Create a new project using `amplify init`
2. Run `amplify add api` to create a new graphQL API. In my case I provided my own schema from another AWS AppSync project.
2. `amplify push` your project to the amplify-console service.
3. Click "redeploy this version" from the amplify console.

Amplify console backend Logs:
![build_fails](https://user-images.githubusercontent.com/20284107/62235470-0b283d00-b39b-11e9-8bc7-5db49378e1a4.PNG)

**Expected behavior**
I expect the app to build without errors.

**Additional context**
I found someone with a [similar issue](https://forums.aws.amazon.com/thread.jspa?threadID=301405) and they mentioned that specifying the npm version in the build script could alleviate the problem along with uninstalling and re-installing the amplify-cli. This hasn't worked for me.

**Sample code**
amplify.yml
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - nvm use 10
        - npm uninstall -g @aws-amplify/cli 
        - rm -rf node_modules/@aws-amplify/
        - npm install -g @aws-amplify/cli@1.8.5
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
