### ISSUE TITLE
angular 13 build error

### ISSUE THREAD

**Issue by afsalcodehack** [aws-amplify/amplify-console#2613]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

arn:aws:amplify:eu-central-1:804891409512:apps/d2pdamscvk6mqh

### Region

frankfurt

### Amplify Console feature

Build settings

### Describe the bug

I am trying to deploy latest angular version app , created just simple app with ng new command still im getting build error like deps not resolved please check build settings yaml

### Expected behavior

should build success

### Reproduction steps

1 create new angular app with ng new command anguarl version 13
2 deploy with amplify
3 getting build error

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/app
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
