### ISSUE TITLE
Additional app created after upgrading amplify-cli to 4.x

### ISSUE THREAD

**Issue by heitorlessa** [aws-amplify/amplify-console#279]
**Describe the bug**
Duplicated App in Amplify Console after upgrading Amplify-CLI to 4.x (4.2 as of now). 

![image](https://user-images.githubusercontent.com/3340292/69883722-48f78c80-12cd-11ea-97f3-8f087a56da02.png)

**To Reproduce**
1. Create a new App within Amplify Console
2. Install Amplify-CLI older than 4, upgrade it and push
3. You should see a duplicated app

**Expected behavior**
Single App

**Additional context**

**Sample code**
Include additional sample code or a sample repository to help us reproduce the issue. (Be sure to remove any sensitive data)

**Comment by heitorlessa** [comment]
I just discovered why it ended up creating a duplicate one.

After upgrading to Amplify-CLI and running **`amplify push`** it created an Amplify App ID which is different from the Amplify App ID it got auto-generated for my existing App.

My existing App sees the front-end but back-end. My new App sees back-end but front-end.

**Comment by swaminator** [comment]
@heitorlessa for apps that are using both console and CLI, you need to upgrade through the console by clicking redeploy this version. This will give you a backed env in the tab. After doing so, run the amplify pull command from your local terminal to get the correct appid.

**Comment by heitorlessa** [comment]
> @heitorlessa for apps that are using both console and CLI, you need to upgrade through the console by clicking redeploy this version. This will give you a backed env in the tab. After doing so, run the amplify pull command from your local terminal to get the correct appid.

I've tried both redeploying and pushing a new commit - No effect. Either way, I've tried `amplify pull` with the AppId from Amplify Console, all green but no changes in the Console itself.

**Comment by ChristopheBougere** [comment]
I'm having the same issue.

I have various environments:
- `staging` and `prod`, which are configured in Amplify Console in an app created a while ago
- `christophe`, a dev env which isn't configured in Amplify Console and that I only deploy via the CLI

I recently upgraded to 4.2 and when I push from `christophe`, it creates a new Amplify app in the console. I tried to redeploy the `staging` env from the Console, but it doesn't make the backend section appear anywhere.

What am I supposed to do?

**Comment by swaminator** [comment]
@ChristopheBougere can you share your appid? Also your build settings would be helpful

**Comment by ChristopheBougere** [comment]
@swaminator thanks for taking a look.
The original amplify app id is `d2kr6iz2hgzrdy` (eu-west-1). A new app has been generated with this id: `d3p8otsv7y21zu`.
Here is my amplify.yml:
```yaml
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - (cd commons && npm ci)
        - (cd cli && npm link)
        - cd web
    build:
      commands:
        - amplifyPush --simple
        - (cd ../services/cleanup && npx serverless deploy --stage $USER_BRANCH --region $AWS_REGION)
        - (cd ../services/images && npx serverless deploy --stage $USER_BRANCH --region $AWS_REGION)
        - (cd ../services/uploader && npx serverless deploy --stage $USER_BRANCH --region $AWS_REGION)
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
    postBuild:
      commands:
        - claptime setup-env --yes
  artifacts:
    baseDirectory: web/build
    files:
      - '**/*'
  cache:
    paths:
      - web/node_modules/**/*
```
