### ISSUE TITLE
Too many redirects

### ISSUE THREAD

**Issue by yfaney** [aws-amplify/amplify-console#28]
**Describe the bug**
I deployed my simple react.js/babel/webpack application to amplify and cannot connect to the app due to "too many redirects"

**To Reproduce**
1. Go to https://stable.d2i4qqadma0z0i.amplifyapp.com

**Expected behavior**
You will see ERR_TOO_MANY_REDIRECTS on Chrome or Safari. It doesn't work on Edge or IE either.

**Sample code**
URL to the Github with the branch: https://github.com/yfaney/github-review-dashboard/tree/stable

**Additional Context**
Cleaning up cookies didn't help.

**Screenshot**
![Screen Shot 2019-08-01 at 9 07 44 AM](https://user-images.githubusercontent.com/5394800/62300848-1d5ab780-b43d-11e9-8cb7-60cda9b70f18.png)
![Screen Shot 2019-08-01 at 9 07 58 AM](https://user-images.githubusercontent.com/5394800/62300853-1fbd1180-b43d-11e9-832b-5303e1f9d9a0.png)

**Comment by yfaney** [comment]
NVM, adding host 0.0.0.0 and disableHostCheck fixed this issue.

**Comment by yfaney** [comment]
Actually I have found the root cause. I needed to set the correct baseDirectory to point to babel output in build settings.

**Comment by phyzixmusic** [comment]
can you share your build settings on amplify please

**Comment by yfaney** [comment]
There was nothing special:
```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
I set baseDirectiry to **dist** because I used babel to compile jsx.
