### ISSUE TITLE
Deploy fails when tests are present

### ISSUE THREAD

**Issue by jkar32** [aws-amplify/amplify-console#283]
**Abbreviated problem**
Angular app builds and tests successfully, but deploy fails with. 
```
2019-12-02T11:26:22 [INFO]: Starting Deployment
2019-12-02T11:26:22 [ERROR]: Failed to deploy
2019-12-02T11:26:22 [INFO]: Deployment finished.
```

**Details**
I created a new angular project, not in the base directory but such that the file structure was so:
```
.
+-- amplify.yml
+-- amplify
|   +-- ...
+-- frontend
|   +-- angular.json
|   +-- package.json
|   +-- ...
```
And with amplify.yml contents
```
version: 1.0

frontend:
  phases:
    preBuild:
      commands:
        - cd frontend
        - npm ci
    build:
      commands:
        - npm run build-prod
  artifacts:
    baseDirectory: frontend/dist
    files:
      - '**/*'
  cache:
    paths:
      - frontend/node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - cd frontend
        - npm ci
    test:
      commands:
        - npm run test-ci
  artifacts:
    baseDirectory: frontend/coverage
    files:
      - '**/*'
```

In the amplify console the build and tests complete successfully but the deploy fails (error seen above) without any description. If I remove the test section in the `amplify.yml` then the app successfully deploys

**To Reproduce**
1. Set up a new repo with angular in a subfolder
2. Create  amplify.yml as stated above
3. connect to amplify
4. See an error in the deploy part of the pipeline

**Expected behavior**
The app too successfully deploy
