### ISSUE TITLE
What does the test>artifacts section of build settings represent for an Angular project?

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-console#284]
```
test:
  phases:
    preTest:
      commands:
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        - yum install -y ./google-chrome-stable_current_*.rpm
        - npm ci
    test:
      commands:
        - npm run test:ci
  artifacts:
    baseDirectory: ???
    files:
      - '**/*'
```
`"test:ci": "ng test --no-watch --no-progress --browsers ChromeHeadlessCI", 
`

Is it meant to define where all your tests are located? Or is it meant to define where the output artifacts will go after your tests are run? What if my tests don't have an output artifacts (as is the case above), what should I put here?
