### ISSUE TITLE
Deployment stuck at provision step

### ISSUE THREAD

**Issue by steverandy** [aws-amplify/amplify-console#296]
**Describe the bug**
Sometimes deployment stuck at the provision step and does not progress.
There is no additional information displayed or an error message.

![Screenshot 2019-12-09 at 12 32 26 PM](https://user-images.githubusercontent.com/525332/70408169-1e05f900-1a82-11ea-90ce-7a9684d745c7.png)

**Comment by swaminator** [comment]
Can you share your appid please? (Found in `App settings > General`)

**Comment by steverandy** [comment]
@swaminator d347fpgoiyxpzr

**Comment by steverandy** [comment]
@swaminator build status is showing `Pending` and any subsequent webhook triggers appeared to be not processed.

**Comment by kahdojay** [comment]
@steverandy I see all the builds for d347fpgoiyxpzr in that region for 12/8 as being successful. Can you share the specific build number we should look at? Also if you have a way we can reproduce the issue, please let us know.

**Comment by steverandy** [comment]
Sure. Please check build no 367, 357, 355.

It usually happens for deployment triggered by webhook. Manually triggered deployment usually always successful.

**Comment by abouroubi** [comment]
Same but here, Webhook started builds always hangs on provisionning

**Comment by swaminator** [comment]
@abouroubi can you share your appid, build settings, and the build IDs that fail.

**Comment by abouroubi** [comment]
AppID : d3egu8kdaurpmi
Build Settings : 
```YAML
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

Build ID that hangs: Build #10
