### ISSUE TITLE
Amplify not recognizing my artifact directory during deployment.

### ISSUE THREAD

**Issue by slhernandez** [aws-amplify/amplify-console#313]
appId: d1ms7jt11oekyc
region: us-east-1

Hello,

I think I have my build settings incorrect.  I am having trouble getting my build (baseDirectory) recognized by the deploy step.  I am deploying a vanilla react.js app with a typical "npm run build" script that creates a "build" folder.  For some reason, Amplify can't locate the build folder even though it's been generated.  I even inserted some postBuild commands to ls la the directory contents and confirm the build directory is there.  

Below is my log file.  

[amplify_output_slh.txt](https://github.com/aws-amplify/amplify-console/files/3962741/amplify_output_slh.txt)

Any insight to this is greatly appreciated.

**Comment by kahdojay** [comment]
hi @slhernandez can you share your buildspec?

**Comment by slhernandez** [comment]
Hi @kahdojay.  I am no longer using Amplify.  Decided to go in a different direction with my deployment.  I am going to close this issue.  Thanks!

**Comment by swaminator** [comment]
@slhernandez sorry to see you go. Any particular reason why you moved away?

**Comment by gvnttdata** [comment]
I am having this exact issue, I am trying to host a Nuxt project and for some reason I see the build script being run but not being able to be found right after.

this is what I'm getting in my logs:

```
# Starting phase: build
# Executing command: npm run build
xxxxx@1.0.0 build /codebuild/output/xxx/src/xxxx
nuxt build
Completed phase: build
## Build completed successfully
...
!!! Error: Artifact directory doesn't exist: dist
```

and this is my build instructions
```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths: []
```

Any idea where this is going wrong? This is just a basic nuxt project, I did not think starting with Amplify would be such an investment.
