### ISSUE TITLE
Usage with CloudFormation and CodeCommit

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/amplify-console#34]
I've created a CodeCommit repository with CFN and committed my Expo/Amplify project into it.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a CodeCommit repository'

Parameters: 
  UserNameParam: 
    Type: String

Resources:
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryName: xyz

  Group:
    Type: AWS::IAM::Group
    Properties : 
      GroupName : xyz-devs
      Policies:
        - PolicyName: xyz-repository-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: !GetAtt Repository.Arn
                Action:
                  - "codecommit:*"

  UserToGroupAddition:
    Type: AWS::IAM::UserToGroupAddition
    Properties: 
      GroupName: !Ref Group
      Users: 
        - !Ref UserNameParam

Outputs:
  CloneUrl:
    Description: The URL where the created repository is available.
    Value: !GetAtt Repository.CloneUrlSsh
``` 

Then I wanted to connect the Amplify Console to this repository, also with CFN.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Connects a CodeCommit repository to the Amplify Console'

Resources:

  DevBranch:
    Type: AWS::Amplify::Branch
    Properties: 
      BranchName: master
      AppId: !GetAtt App.AppId
      EnableAutoBuild: yes
      EnvironmentVariables:
        - Name: USER_BRANCH
          Value: dev

  App:
    Type: AWS::Amplify::App
    Properties:
      Name: Xyz
      Repository: https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/xyz
      BuildSpec: |
        version: 0.1
        backend:
          phases:
            build:
              commands:
                - amplifyPush --simple
        frontend:
          phases:
            preBuild:
              commands:
                - nvm use 10
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: web-build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
              - $(npm root --global)/**/*
```

But when I run a deploy I get the following error:

    2019-08-06T12:21:20.686Z [INFO]: fatal: unable to access 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/xyz/': The requested URL returned error: 403
    2019-08-06T12:21:20.692Z [ERROR]: !!! Unable to clone repository.

I guess the Amplify backend service role that was created for me is used to do the checkout?
But it has Admin rights, so it should be able to access the repository, right?
