### ISSUE TITLE
How to run functional tests in build script?

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-console#39]
** Please describe which feature you have a question about? **
I'm trying to run functional tests with TestCafe when building. Here are my build settings:

```yml
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
        - yarn validate
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

And here is how the `"validate"` script looks like:

```json
"validate": "yarn -s unit-tests && yarn -s lint && yarn -s functional-tests",
"functional-tests": "testcafe 'chrome:headless' src/functional-tests/",
```

But this throws the error:

```
2019-08-08T15:36:17.385Z [WARNING]: ERROR Unable to find the browser. "chrome:headless" is not a browser alias or path to an executable file.
```

How can I add Chrome to the Amplify console, or run functional tests with it?

** Provide additional details**
