### ISSUE TITLE
Access Denied error after deploying Vue.js application

### ISSUE THREAD

**Issue by faizanbashir** [aws-amplify/amplify-console#436]
I am trying to deploy a vue.js application, once the deploy completes I am getting the below error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>69F14474972D101F</RequestId>
<HostId>
OUeLFCflVlOsrmr9dklT/JzhiMYpr49zIW7X9WflA0XpMrHeTI9rO7P4DasivogoEw2AVCzLTT8=
</HostId>
</Error>
```

**Comment by prasaddattu478** [comment]
We got a similar issue. in our case, index.html was under /xyz/xyz/ subdirectory path instead of being at root level. To fix it we went inside the directory where index.html is present & did a zip. deployed the zip file and we are able to access it.

**Comment by Joycehao19** [comment]
Hi @faizanbashir , sorry that you have this issue. Which amplify cli version did you use? Can you provide you appId and region? Thanks.

**Comment by faizanbashir** [comment]
@Joycehao19 I deployed it from the amplify console for continuous deployment, there is no amplify cli involved. Also when I deploy the same vue.js app using amplify cli it works perfectly but using the amplify console it is giving me the aforementioned error. No amplify backend services are used in this application.

**Comment by ganipcanot** [comment]
@faizanbashir Can you share your build settings?  There might be something wrong with how you are generating your output/artifacts folder/directory.

**Comment by fsthomas** [comment]
I'm having a similar issue with a React app's images directory. They're all coming through as `AccessDenied`.

**Comment by jonkelling** [comment]
I am also having trouble with this. index.html works but bundle.js comes through as AccessDenied.

**Comment by faizanbashir** [comment]
@ganipcanot here is the `amplify.yml` build file:

```
version: 0.1
env:
  variables:
    NODE_ENV: production
    SOME_VAR_FOO: bar 
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
        - npm install -g @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint @vue/cli-plugin-pwa babel-eslint eslint eslint-plugin-vue node-sass sass-loader vue-template-compiler webpack webpack-cli webpack-dev-server
    build:
      commands:
        - export $(cat .env.staging)
        - npm install
        - vue-cli-service build --mode production
    postBuild:
      commands: 
  artifacts:
    baseDirectory: .
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
Even after installing using both npm and yarn `vue-cli-service` is not found, so I manually tried to install the package and its dependencies and that also does not work and `npx vue-cli-service` also does not seem to work.
