### ISSUE TITLE
Deploy Failed (Build Backend and Build Frontend never run)

### ISSUE THREAD

**Issue by MaximilianFranke** [aws-amplify/amplify-console#442]
The deploy step failed with this log:
```
2020-02-17T11:55:42 [INFO]: Starting Deployment
2020-02-17T11:55:42 [ERROR]: Failed to deploy
2020-02-17T11:55:42 [INFO]: Deployment finished.
```
This happens, since 2h before everthing works fine.
In the Build step is just "Cloning Repositiory" available. The  "Build Backend" and "Build Frontend" Tab is complete missing.  I also tried to build without the cache path in the build settings. Like the descriped workaround of my other issue  #409 

AppID: 
`App ARN arn:aws:amplify:eu-central-1:064480943479:apps/d3s4jihdbyzh2`

Build settings:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build:$USER_BRANCH
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
*Also tried it without  `- node_modules/**/*`      

Affected builds
Dev Build #526 - Build #529
Master Build 18

Thank you for your help in advance!
