### ISSUE TITLE
amplify.sh Killed

### ISSUE THREAD

**Issue by deybhayden** [aws-amplify/amplify-console#451]
**App Id**: d3bpomoo30yiqc
**Region**: us-east-1
**Step**: Build
**Status**: Failed

**Issue/question**
About 10 minutes into our Vuepress site Build process, the build abruptly dies, and there is no context as to why.

**Error message**
```
2020-02-20T20:26:33.254Z [INFO]: [2K[1GRendering page: /products/ducks.html
2020-02-20T20:26:53.200Z [WARNING]: /codebuild/output/src840799846/src/DocSite/amplify.sh: line 10:  1967 Killed                  npm run docs:build
2020-02-20T20:26:53.231Z [ERROR]: !!! Build failed
2020-02-20T20:26:53.403Z [ERROR]: !!! Non-Zero Exit Code detected
2020-02-20T20:26:53.403Z [INFO]: # Starting environment caching...
2020-02-20T20:26:53.410Z [INFO]: # Environment caching completed
Terminating logging...
```

**Additional information**
The docs build locally without issue. Not sure how to move on, as we've tried all of the following:

* increasing the timeout limit
* changing node js version
* changing the build docker image
* rolling back to a previous state where the app was working
* changing node max-old-space-size parameter 
* removed caching

**Comment by Joycehao19** [comment]
@deybhayden Hi, sorry that you are facing this issue. Would you mind provide the branch name and build id?

**Comment by z3by** [comment]
Hey @Joycehao19 the Branch is master, and the latest build id is 79.

**Comment by Joycehao19** [comment]
@z3by Can you share your amplify.sh file?

**Comment by z3by** [comment]
sorry, where can I find it? given in mind we are using Amplify with Vuepress without Amplify CLI.

**Comment by Joycehao19** [comment]
@z3by Sorry... I mean amplify.yml file

**Comment by z3by** [comment]
@Joycehao19 It is the default build specifications file:

```yml
version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - 'npm run docs:build'
  artifacts:
    baseDirectory: docs/.vuepress/dist
    files:
      - '**/*'
```
