### ISSUE TITLE
Cross account CI/CD for ampify-cli project

### ISSUE THREAD

**Issue by vchaddha** [aws-amplify/amplify-console#496]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
amplifyPush script to be used cross account, using CodeBuild.

**Amplify CLI Version** 
amplify --version
4.14.1
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**
amplify-cli, codepipeline, codebuild. Cross account CI/CD.
Note: I am not directly using Amplify console, but taking help from the idea that it works on. Since I need to use a single code repository to deploy to multiple envs in multiple accounts

**Provide additional details e.g. code snippets**
* **Problem statement:**
I am trying to setup cross account CI/CD pipeline using Codepipeline with 2 stages for Codebuild and there are two issues that I am trying to resolve, which I need help with.
* **Issue 1**
I am using something similar that amplify console does, wherein I use the helper script amplifyPush.sh
https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh

I use a docker image for my build environment in CodeBuild, which is defined as follows:
```
# Use the standard Amazon Linux base, provided by ECR/KaOS
# It points to the standard shared Amazon Linux image, with a versioned tag.
FROM amazonlinux:2
MAINTAINER Amazon AWS

# Framework Versions
ENV VERSION_NODE=10.16.3

# UTF-8 Environment
ENV LANGUAGE en_US:en
ENV LANG=en_US.UTF-8
ENV LC_ALL en_US.UTF-8

## Install OS packages
RUN touch ~/.bashrc
RUN yum -y install \
      jq \
      tar \
      zip \
      gzip \
      python3 \
      python3-devel \
    yum clean all && \
    rm -rf /var/cache/yum


## Install Node 10
#RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
RUN /bin/bash -c ". ~/.nvm/nvm.sh && \
	nvm install $VERSION_NODE && nvm use $VERSION_NODE && \
	nvm alias default node && nvm cache clear"

ENV PATH /root/.nvm/versions/node/v${VERSION_NODE}/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

## Install AWS Amplify CLI for VERSION_NODE
RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE} && \
    npm install -g @aws-amplify/cli"

RUN /bin/bash -c ". ~/.nvm/nvm.sh && nvm use ${VERSION_NODE} && \
    npm install -g typescript && \
    npm install -g @angular/cli && \
    npm install -g @angular-devkit/build-angular" 

## Environment Setup
RUN echo "nvm use ${VERSION_NODE} 1> /dev/null" >> ~/.bashrc

## Install awscli
RUN /bin/bash -c "pip3 install awscli && rm -rf /var/cache/apk/*"

COPY envCache /usr/local/bin
RUN chmod +x /usr/local/bin/envCache
COPY amplifyPush /usr/local/bin
RUN chmod +x /usr/local/bin/amplifyPush

RUN source ~/.bashrc

ENTRYPOINT [ "bash", "-c" ]
```

When I use the below build file:
```
version: 0.2

phases:
  build:
    commands:
      - assumes_role=`aws sts assume-role --role-arn <cross account role arn> --role-session-name int`
      - AWS_ACCESS_KEY_ID=`echo $assumes_role | jq -r .Credentials.AccessKeyId`
      - AWS_SECRET_ACCESS_KEY=`echo $assumes_role | jq -r .Credentials.SecretAccessKey`
      - AWS_SESSION_TOKEN=`echo $assumes_role | jq -r .Credentials.SessionToken`
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_session_token $AWS_SESSION_TOKEN
      - aws configure set default.region us-east-1
      - chmod u+x ./amplifyPush.sh
      - ./amplifyPush.sh
      - amplify publish
    finally:
      - echo Build completed

artifacts:
  files:
    - '**/*'
```
It just gives the message: 
```
usage: amplify-push <--environment|-e <name>> <--simple|-s>
--environment  The name of the Amplify environment to use
--simple  Optional simple flag auto-includes stack info from env cache
```
which makes me think that it does not auto initiate an environment.

When I use 
```
- chmod u+x ./amplifyPush.sh
- ./amplifyPush.sh -s -e dev
```

It does initiate the environment and creates resources in the other account, though, this is only for the first time. When I trigger this build using a change in codecommit repository, it fails saying that the s3 bucket already exists, which makes me understand that the script does not get the existing environment in the re-spun container for codebuild, and thus tries to initiate the environment again which includes creating the hosting s3 bucket again, on which it fails. Please let me know if you need complete logs.

I read a couple of other resources and issues, on which it was mentioned that amplify pull env can be used to pull the environment into the current-backend files, and then the push can be done. Though this did not help.

**My question** is, how can I make sure that on each CodeBuild build, the same environment can be used, or is there any other better way to setup cross account CI/CD pipeline. I am stuck at this point for a long time now.

* **Issue 2**
when building the project, the output Directory (outDir) is set to ./dist/<application name> in which <build files> are created. 
I have added hosting by using `amplify add hosting`
and when I use `amplify push` (using the helper script), it does not copy any dist file to S3 bucket with the default project configuration.

```
{
    "projectName": "Angular-app",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "angular",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm start"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```

though when I change this to the following:
```
{
    "projectName": "Angular-app",
    "version": "3.0",
    "frontend": "javascript",
    "javascript": {
        "framework": "angular",
        "config": {
            "SourceDir": "src",
            "DistributionDir": "dist/Angular-app",
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm start"
        }
    },
    "providers": [
        "awscloudformation"
    ]
}
```
it works fine locally. 

This is what I am trying to replicate in the cross account build.
In the amplifyPush file(https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh), below is what I have tried, but to no use:
```
AWSCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":true,\ 
\"profileName\":\"default\",\
\"SourceDir\": \"src\",\
\"DistributionDir\": \"dist/Angular-app\",\
\"BuildCommand\": \"npm run-script build\",\
\"StartCommand\": \"npm start\"\
}"
```
I also tried this:
```
AMPLIFY="{\
\"projectName\":\"dxcapp\",\
\"envName\":\"${ENV}\",\
\"javascript\": {\
\"framework\": \"angular\",\
\"config\": {\
\"SourceDir\": \"src\",\
\"DistributionDir\": \"dist/Angular-app\",\
\"BuildCommand\": \"npm run-script build\",\
\"StartCommand\": \"npm start\"\
}\
}\
}"
```

When using amplify publish, it still does not use these configuration items. Rather just uses ng build with dist as the distribution directory, and so, when I check the S3 bucket, it is empty, even after successful completion of the build stage.

**My question** is, how can I make sure that the project settings in the amplify/.config/project-config.json can be replicated by the amplifyPush script on the codebuild container?

Please let me know if you have any questions on what I am trying to do.

**Comment by vchaddha** [comment]
Update: I was able to figure out the solution for Issue 2, so Issue 2 stands resolved. Been working towards a solution for Issue 1. Below is what I tried:

Understanding that the container that is spun up for Codebuild build, does not have any reference for the environment, I tried using amplify pull command from the amplify console app that is created from the build.
So, my buildspec file now looks as follows:
```
version: 0.2

phases:
  build:
    commands:
      - assumes_role=`aws sts assume-role --role-arn <cross account role> --role-session-name int`
      - AWS_ACCESS_KEY_ID=`echo $assumes_role | jq -r .Credentials.AccessKeyId`
      - AWS_SECRET_ACCESS_KEY=`echo $assumes_role | jq -r .Credentials.SecretAccessKey`
      - AWS_SESSION_TOKEN=`echo $assumes_role | jq -r .Credentials.SessionToken`
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set aws_session_token $AWS_SESSION_TOKEN
      - aws configure set default.region us-east-1
      **- chmod u+x ./amplifyPull.sh**
      **- ./amplifyPull.sh --appId d392fdpba3rmua --envName dxcl --useProfile true --ProfileName default**
      - chmod u+x ./amplifyPush.sh
      - ./amplifyPush.sh -s 
      - npm install @angular-devkit/build-angular
      - amplify publish
    finally:
      - echo Build completed

artifacts:
  files:
    - '**/*'

```
Below is my amplifyPull.sh file:
```
#!/bin/bash
set -e
IFS='|'
args=("$@")

appId=""
envName=""
useProfile="false"
profileName="default"
for ((argPos=0; argPos <= ${#args}; argPos++))
do
  if [ "${args[$argPos]}" == "--appid" ]; then
    appId="${args[(($argPos+1))]}"
    argPos=$((argPos+1))
  elif [ "${args[$argPos]}" == "--envName" ]; then
    envName="${args[(($argPos+1))]}"
    argPos=$((argPos+1))
  elif [ "${args[$argPos]}" == "--useProfile" ]; then
    useProfile="true"
  elif [ "${args[$argPos]}" == "--profileName" ]; then
    profileName="${args[(($argPos+1))]}"
    argPos=$((argPos+1))
  fi
done

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":${useProfile},\
\"profileName\":\"${profileName}\"\
}"
AMPLIFY="'{\
\"appId\":\"${appId}\",\
\"envName\":\"${envName}\"\
}'"
PROVIDERS="'{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}'"

cmd="amplify pull --providers ${PROVIDERS} --amplify ${AMPLIFY} --yes"
echo $cmd
eval $cmd
```

My understanding is that amplify pull with the appid and environment name will pull the current-backend and aws-exports.js file from the cloud and initialize the amplify environment in the build container. Upon that, I can do amplify push / publish with the changes I made in the backend, and this should appear in the cloud and be deployed using the hosting provider.

Please let me know if my understanding is wrong.

Though, my actual findings are as follows (I get the following error)
```
Failed to pull the backend.
{ Error: Prompts can not be meaningfully rendered in non-TTY environments
    at PromptUI.fetchAnswer (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/inquirer/lib/ui/prompt.js:87:27)
    at MergeMapSubscriber._tryNext (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/operators/mergeMap.js:95:26)
    at InnerSubscriber._next (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/root/.nvm/versions/node/v10.16.3/lib/node_modules/@aws-amplify/cli/node_modules/rxjs/internal/Observable.js:30:22) isTtyError: true }
```
