### ISSUE TITLE
Bring your own ACM Certificate

### ISSUE THREAD

**Issue by mbarneyjr** [aws-amplify/amplify-console#535]
I'd like to be able to pass an ACM certificate ARN to my `AWS::Amplify::Domain` resource to tell Amplify to use that instead of trying to create its own. My use case is that there is a separate account for managing DNS, but an ACM certificate is already provisioned in the deployment account I want to deploy my Amplify Console app to. I want to keep things automated (in CloudFormation), so that I don't have to manually configure the DNS whenever I want to create an `AWS::Amplify::App` with an `AWS::Amplify::Domain`.

I'd like there to be a `CertificateArn` option when creating an `AWS::Amplify::Domain`:

```yml
  AWSAmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      CertificateArn: String
```

Where when the property is provided, that is the cert that will be used, otherwise the current functionality is kept where Amplify Console tries to create it's own.
