### ISSUE TITLE
Access Denied after deploy frontend.

### ISSUE THREAD

**Issue by 2manoj1** [aws-amplify/amplify-console#549]
After Build and deploy got access denied issue. Please help

amplify -v
4.17.1

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BCE70BB688B50E63</RequestId>
<HostId>
lVjnhXblaLjJ1t3COi0imqlBclAh7SUx4+7Ddsoth+th9EuTJwtU1bgwdMyVeEgFk7xWteOM24Y=
</HostId>
</Error>
```

**Comment by swaminator** [comment]
@2manoj1 please check your build output directory in the build settings: (App Settings > Build settings). It could be incorrect which is why your files are not deploying.

**Comment by 2manoj1** [comment]
@swaminator With below setup always getting error. Tryied with out dir no luck yet.
# Build Settings

```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

# package.json Script
```
"dev": "next",
"build": "next build",
"start": "next start"
```

# amplify config

```
            "BuildCommand": "npm run-script build",
            "StartCommand": "npm run-script start"
```
