### ISSUE TITLE
Artifacts baseDirectory needs hardcoded path

### ISSUE THREAD

**Issue by goldmont** [aws-amplify/amplify-console#582]
** Please describe which feature you have a question about? **
Hi,

Frontend path: `frontend/client/v1`
Frontend build path: `frontend/client/v1/build`
Frontend node_modules path: `frontend/client/v1/node_modules`

Since there can be multiple versions of my frontend, I need to compose the path by concatenating environment variables. I can't get the deploy work because Amplify cannot find neither the **baseDirectory** nor the cache path (**node_modules**). It only works if I hardcode the whole path by hand. So, instead of having `/$_FRONTEND/$_FRONTEND_VERSION/build`, I write `/frontend/client/v1/build`, it works. I want to believe that this is not a lack of Amplify but a mistake of mine.

** Provide additional details**
**amplify.yml**
```yaml
version: 1.0

env:
  variables:
    _BACKEND: backend
    _BACKEND_VERSION: v1
    _FRONTEND: frontend/client
    _FRONTEND_VERSION: v1
backend:
  phases:
    preBuild:
      commands: []
    build:
      commands: []
    postBuild:
      commands: []
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - cd $_FRONTEND/$_FRONTEND_VERSION
        - yarn install --production=false #--ignore-optional #--verbose
    build:
      commands:
        - yarn run build
    postBuild:
      commands:
        - rm -rf node_modules
        - yarn install --production #--ignore-optional #--verbose
  artifacts:
    baseDirectory: /$_FRONTEND/$_FRONTEND_VERSION/build
    files:
      - '**/*'
  cache:
    paths:
      - /$_FRONTEND/$_FRONTEND_VERSION/node_modules/**/*
```

**Comment by adriencg** [comment]
@goldmont Thanks for your question. I'll try to repro this today, and should get back to you shortly about what the issue could be.

**Comment by goldmont** [comment]
@adriencg Thank you man.

**Comment by adriencg** [comment]
@goldmont So currently environment variables are only accessible to commands; this is a feature we're aware customers want, however cannot comment/commit to any specific timeline.

The best workaround I can think of is defining some static destination directory e.g. `/deploy` and then `mv`'ing the artifacts there as the last step in the postBuild i.e. something like:
```
    postBuild:
      commands:
        - rm -rf node_modules
        - yarn install --production #--ignore-optional #--verbose
        - mv /$_FRONTEND/$_FRONTEND_VERSION/build /deploy # stage files for deployment
  artifacts:
    baseDirectory: /deploy
    files:
      - '**/*'
```

You'd also wanna delete the cache-paths. 

Full disclosure: I didn't test the above out...so let me know how it goes, and I'd be more than happy to keep finding a better solution. If it does work, please reply back here and I can close the issue out.

**Comment by adriencg** [comment]
@goldmont I'm gonna close this for now if you don't mind, but feel free to reopen if you've any more q's or this doesn't work as expected.

**Comment by goldmont** [comment]
Hi,

I've solved...

This is the `amplify.yml` I use:
```yaml
version: 1.0

env:
  variables:
    _BACKEND_VERSION: v1
    _FRONTEND_VERSION: v1
    _CLIENT_DIR: client
    _CLIENT_BUILD: build/client
    _DEPLOY_DIR: deploy/build
backend:
  phases:
    preBuild:
      commands: []
    build:
      commands: []
    postBuild:
      commands: []
frontend:
  phases:
    preBuild:
      commands:
        - _CWD="$(pwd)"
        - nvm use $VERSION_NODE_12
        - cd frontend/$_FRONTEND_VERSION
        - yarn install
    build:
      commands:
        - yarn run build:client:pre
    postBuild:
      commands:
        - mkdir -p $_CWD/$_DEPLOY_DIR
        - mv -v ${_CLIENT_BUILD}/* $_CWD/$_DEPLOY_DIR
        - cd $_CWD
        - shopt -s extglob dotglob
        - rm -rf !(amplify.yml|deploy)
        - shopt -u extglob dotglob
  artifacts:
    baseDirectory: /deploy/build
    files:
      - '**/*'
  cache:
    paths:
      - /deploy/build/**/*
```

Unlike `phases`, it seems that `artifacts` and `cache` sections are chrooted to the project root directory. 

Furthermore, I can't remove `cache` section because the following error is raised:
`TypeError: Cannot read property 'paths' of undefined.`

By the way, my configuration leaves only `amplify.yml` file and `deploy` directory once the project has built successfully.
