### ISSUE TITLE
Test step stays "pending or cancelled" after build completes.

### ISSUE THREAD

**Issue by BigTom** [aws-amplify/amplify-console#594]
Following on from issue: [583](https://github.com/aws-amplify/amplify-console/issues/583)

Thanks @adriencg for getting the build working again.

The build now runs to completion and has deployed.  

The Test step, however, remains as a "grey clock" rather than a "green tick" and reports `Test is still pending or has been canceled for this build`.  I cannot find any additional logging or monitoring output about it.

Thanks

Tom

**Comment by adriencg** [comment]
If you wouldn't mind providing me with just your appId and region that'd let me investigate what might be happening:

You can find your APP-ID and REGION by looking at the amplify console:

App Settings --> General --> AppArn: It will look something like this:

arn:aws:amplify:REGION:accountId:apps/APP-ID

Note: I do not need your AWS account ID; just the appId + region.

**Comment by BigTom** [comment]
Hi,

Here you go.

Region: eu-west-1
AppID: d3vle8i2wz8y9o
App ARN: arn:aws:amplify:eu-west-1:633213239760:apps/d3vle8i2wz8y9o

Thanks

Tom

**Comment by adriencg** [comment]
Hey @BigTom,

Looks like the indentation got screwed up when you copy/pasted. Make sure that the phases block of the yaml is indented relative to the top-level `test` block (just above artifacts). Pasting the entire "Build settings" this time for convenience

```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - pm2 kill
```
