### ISSUE TITLE
AWS Amplify Build Settings for React Application 

### ISSUE THREAD

**Issue by travelerr** [aws-amplify/amplify-console#667]
** Please describe which feature you have a question about? **
Using Amplify I'm having difficulty deploying a React application which I believe is due to the build settings.

** Provide additional details**
When trying to deploy the default build settings provided are shown below:
![Screen Shot 2020-05-13 at 7 59 55 PM](https://user-images.githubusercontent.com/30609733/81877918-78851300-9554-11ea-8170-d500192eceba.png)
I know this is incorrect and the error I find in the build logs is:
` 2020-05-14T00:02:22.327Z [WARNING]: !! No index.html detected in deploy folder: /codebuild/output/src568504829/src/chatterfield/`
The deploy is successful expect when I launch the application I receive an ERR_TOO_MANY_REDIRECTS. After I changed the basedirectory in build settings to /client/public to point to index.html. The app appears to launch without the REDIRECT error, but nothing loads. I'm guessing this is because I am not running an npm run build command, or not loading a prebuild command. Any help would be greatly appreciated. Thank you 
Here is the repo this app is linked to:
https://github.com/travelerr/chatterfield

**Comment by kahdojay** [comment]
@travelerr correct, you will need to provide the build commands that builds your app. Can you try:

```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - cd client
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: client/public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
