### ISSUE TITLE
Using redirects with CloudFormation

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/amplify-console#67]
**Please describe which feature you have a question about?**

I created a `AWS::Amplify::Domain` with CloudFormation, but I can't find the config to set a redirect from the root domain to a subdomain as the UI  allows me to do. 

**Provide additional details**

```yaml
  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: example.com
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - Prefix: www
          BranchName: !GetAtt AmplifyMasterBranch.BranchName
        - Prefix: test
          BranchName: !GetAtt AmplifyTestBranch.BranchName
```
