### ISSUE TITLE
Test phase hangs on even if the cypress tests successfully pass

### ISSUE THREAD

**Issue by blerand123** [aws-amplify/amplify-console#671]
When I try to deploy my application to amplify it passes the build phase but then it hangs on in the test phase even though I get the message:  `# Completed phase: test, ## Tests completed successfully`. First i tried with the cypress version 4.4.1, and after this I tried with 3.8.1 but still hangs on.
amplify.yml file it is like this:
![amplify44](https://user-images.githubusercontent.com/16356021/81951464-762ec180-9605-11ea-8772-de3b6d21b5b1.png)
Amplify console:
![succes](https://user-images.githubusercontent.com/16356021/81951764-db82b280-9605-11ea-82bd-70a879cb2069.png)

**Comment by swaminator** [comment]
@blerand123  can you try this https://github.com/aws-amplify/amplify-console/issues/583#issuecomment-614385089

**Comment by blerand123** [comment]
> @blerand123 can you try this [#583 (comment)](https://github.com/aws-amplify/amplify-console/issues/583#issuecomment-614385089)
After i updated my amplify.yml now it passess the test phase but it does not run the tests:
![image](https://user-images.githubusercontent.com/16356021/82047415-1393ff00-96b3-11ea-9db7-6664389a6e91.png)
My amplify.yml:
![image](https://user-images.githubusercontent.com/16356021/82047501-358d8180-96b3-11ea-8238-5aeba3ef8c09.png)

**Comment by Athena96** [comment]
Hello, sorry you're facing this issue.

1. Can you please share what commands you're running in `e2e-tests`
2. Also, can you please try updating your amplify.yml to be the following
 
```
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:3000'
    test:
      commands:
        - 'npx cypress run'
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: cypress
    files:
      - '**/*.png'
      - '**/*.mp4'
```
