### ISSUE TITLE
Inconsistent backend deployment with amplify push

### ISSUE THREAD

**Issue by tomyitav** [aws-amplify/amplify-console#704]
Hi, I set-up an appsync backend environment with the following simple build settings:

<img width="591" alt="Screen Shot 2020-05-24 at 19 28 57" src="https://user-images.githubusercontent.com/16193919/82762506-1789f480-9e0a-11ea-9086-383617ed2c14.png">

When my Frontend environment accesses the backend, I get the following error:
```
validation error of type FieldUndefined: Field 'createdAt'
```

After I do ```amplify push```, the query to appsync works perfectly.
Has anyone encountered this problem?

**Comment by swaminator** [comment]
@tomyitav you need to update your backend before your frontend.  Can you update your buildspec to add the backend phase before hte frontend phase?

**Comment by tomyitav** [comment]
Hey @swaminator, changed the order as suggested but the problem persists. Any other ideas?

**Comment by Athena96** [comment]
Hi @tomyitav are you still facing this issue?
If so, did you try the following build settings:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
