### ISSUE TITLE
Serving apple-app-site-association as json

### ISSUE THREAD

**Issue by dhaveman** [aws-amplify/amplify-console#713]
I need to host the apple-app-site-association file from an amplify hosted project.  I see two solutions to help that:

- custom rewrites: this lets me map apple-app-site-association.json -> apple-app-site-association
- custom headers ( in the build settings ): 

```
customHeaders:
    - pattern: 'apple-app-site-verification'
      headers:
        - key: 'Content-Type'
          value: 'application/json; charset=utf-8'
    - pattern: 'apple-app-site-verification.json'
      headers:
        - key: 'Content-Type'
          value: 'application/json; charset=utf-8'

```

Whenever i download the file howerver the content type is just `application/octet-stream`

Any guidance would be appreciated

angular.json snippet:

```
"assets": [
              "apps/desktop/src/favicon.ico",
              "apps/desktop/src/assets",
              "apps/desktop/src/apple-app-site-verification.json",
```
