### ISSUE TITLE
Node.js build fails due to unneccessarily low default values on memory limit

### ISSUE THREAD

**Issue by UnSciPreneur** [aws-amplify/amplify-console#730]
I am developing an Angular project using CodeCommit integration. The project builds locally on my Node.js 12 environment but fails to build with a warning "`An unhandled exception occurred: Call retries were exceeded`" in AWS Amplify.

After fiddling around on an EC2 instance with Node.js 10 I have found that (on the EC2 instance)
a) the build process fails with the above warning but
b) succeeds if I artificially increase node’s memory, e.g. via `node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build`

Turns out that Node.js 10 has the default for `max_old_space_size` set to 1400MB. But Node.js 12 has removed that limit. ([medium.com](https://medium.com/the-node-js-collection/node-js-memory-management-in-container-environments-7eb8409a74e8))
As the default Node version in the build system is 10 this results in an unnecessarily low memory limit given that Amplify uses build instances with 7GB ram.
 
Replacing 
```
- npm run build
```
in the (default) build config (`frontend/build/phases/commands`) with either one of the following two options should solve the problem:
```
- nvm use $VERSION_NODE_12
- npm run build
``` 
or 
```
- node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build
```
Or, preferably, make Node.js version 12 the default for the build.

**Comment by Joycehao19** [comment]
@UnSciPreneur , Thank you for reporting this issue!

**Comment by andre-scheffer** [comment]
> I am developing an Angular project using CodeCommit integration. The project builds locally on my Node.js 12 environment but fails to build with a warning "`An unhandled exception occurred: Call retries were exceeded`" in AWS Amplify.

@UnSciPreneur I was at the exact same point. This is most likely no issue of the assigned RAM but of your "Building Settings" in the AWS Amplify Console. My solution to this looks like this:

In the AWS Amplify Console you can go to the menu item "App Settings -> Build Settings". There you can see the section "Build image settings". There you need to provide the exact version of your local node that you are developing with (e.g. node:14.15.0). You also have to specify the version of @angular/cli you are using locally (e.g. 10.2.0). Here ist a screenshot of my "Build image settings":

![image](https://user-images.githubusercontent.com/48789566/98989689-bb3a9e80-2529-11eb-92c3-af7ec448b6a4.png)

Alternatively (or in addition), you can also edit the existing amplify.yml in the AWS Amplify Console as follows:

```
version: 1
frontend:
    phases:
        preBuild:
          commands:
            - nvm install 14.15.0
            - nvm use 14.15.0
            - npm ci
        build:
          commands:
            - nvm install 14.15.0
            - nvm use 14.15.0
            - node -v
            - npm run-script build
    artifacts:
        baseDirectory: dist
        files:
            - '**/*'
    cache:
        paths:
            - 'node_modules/**/*'
```
