### ISSUE TITLE
Amplify eventually strips headers from proxied requests

### ISSUE THREAD

**Issue by dereklucas** [aws-amplify/amplify-console#736]
We've been using Amplify to serve the front end of our react app and Lambda to handle our API. To avoid CORS issues, our Amplify is set up to proxy requests to `/api` to the Lambda function. We had this configuration working for a few weeks before it broke: Login requests directly to the lambda function continued to work perfectly, returning 200, proper JSON body, and setting the `set-cookie` header. Login requests through the Amplify app proxied to the lambda returned 200 and the proper JSON body, but with no `set-cookie` header. We tried adding other custom headers and they were stripped as well.

The only way we were able to fix this problem was to delete the Amplify app and set it up again. (We use cloudformation, so we know the new app was identical to the old app.)

We also set up a cloudwatch alarm with a check for a custom header in our health endpoint.

Exactly one week later, and the amplify app has broken again. Deleting and recreating was the only fix. Even more suspectly, our staging amplify app (a near identical cloudfront stack set up in a different profile) has broken in the same way.

Any ideas where to start debugging?

**Comment by swaminator** [comment]
@dereklucas can you share your appID? found in app settings > general?

**Comment by swaminator** [comment]
Sounds like what you're running to is strange behavior so anything you can provide (sample code, steps to repro) would help us.

**Comment by dereklucas** [comment]
@swaminator Yeah, it's definitely pretty odd! I don't think there's anything out of the ordinary for our usage. The production ARN is `arn:aws:amplify:us-west-2:693079194339:apps/d176snxxwt8519` and the staging ARN is `arn:aws:amplify:eu-west-1:463424886012:apps/db9m4urvmq6ju`.
Both of these apps are identical recreations of the previous instances that have seen this problem. (Production three times now, staging once.)

Below is the cloudformation YAML, and if there's a useful test case I can create for it let me know, but the steps to reproduce seem to be:
- Set up an Amplify APP that proxies requests with headers
- Wait a week

The API behind the proxy always worked consistently, it was only requests proxied through the amplify app that were missing headers.

Here's the relevant portions of the cloudformation YAML:

```
  App:
    Type: AWS::Amplify::App
    Properties:
      Name: Arcivr Live
      Repository: !Ref Repo
      OauthToken: !Ref GitHubToken
      EnvironmentVariables:
        - Name: WEBSOCKET_HOST
          Value: !Sub wss://ws.${DomainName}
        - Name: ASSET_HOST
          Value: !Sub https://media.${DomainName}/
      CustomRules:
        - Source: /api/<*> # Proxy API requests
          Target: !Sub https://api.${DomainName}/<*>
          Status: "200"
        - Source: </^[^.]+$/> # Anything else without a . should serve index
          Target: /index.html
          Status: "200"
      BuildSpec: |
        verision: 1.0
        frontend:
          phases:
            preBuild:
              commands:
                - cd web
                - yarn install
            build:
              commands:
                - yarn build
          artifacts:
            baseDirectory: web/dist
            files:
              - "**/*"
          cache:
            paths:
              - web/node_modules
```
