### ISSUE TITLE
Feature branch deploys access denied, but main branch is fine

### ISSUE THREAD

**Issue by chris** [aws-amplify/amplify-console#740]
I have a Nuxt/Vue app where I have feature branch auto-deploys configured. My main branch deploys just fine, site works, etc. However, the feature branches all result in an AccessDenied error. This may be related to #436 or #75 or #526 or #591, however I tried adding the SPA redirect rule and that did not fix it. Further, it seems (maybe) this is specific to feature branches since the main branch deploy works fine. And also, I'm doing Nuxt generate, so it should be a fully static site, with no routing aspects, etc.

Here is may amplify.yml:
```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run generate
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

As an example of the error page I get, it is:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>87410EAC7CEC7C13</RequestId>
<HostId>
JK1Elswet0Laks3CW0U8aZWZa78DMMWLpTfY9CuLL4aNTqpheyJ+uW7Xz5uCG2rGPWAE6lKb8WQ=
</HostId>
</Error>
```
