### ISSUE TITLE
Adding the `--minify` flag to the amplifyPush helper script

### ISSUE THREAD

**Issue by blazinaj** [aws-amplify/amplify-console#742]
** Please describe which feature you have a question about? **
Our CloudFormation stack is now too large, so we have to use the `--minify` flag when we run `amplify push` from the CLI. 

See: [#3520](https://github.com/aws-amplify/amplify-cli/pull/3520)

The [amplifyPush](https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh) script does not allow me to add the `--minify` flag, how can I work around this?

**Comment by ganipcanot** [comment]
Looks like you want to run `amplify push --minify` using the [amplifyPush](https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh) script.

Could you clarify how you're currently using the [amplifyPush](https://github.com/aws-amplify/amplify-console/blob/master/scripts/amplifyPush.sh) script?

Also if you feel it could be improved or have suggestions we are open to pull requests!

**Comment by blazinaj** [comment]
I'm using the default amplify.yaml in the Amplify Console, 
```
version: 0.7
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        #- npm test --watchAll=false
    build:
      commands:
        - npm run build
```
Is there any way that I can add `--minify` using this .yaml directly? Or could you point me in the right direction on the `amplifyPush` script? I'm not sure where I would put the `--minify` flag.
