### ISSUE TITLE
Cache invalidation with gatsby apps

### ISSUE THREAD

**Issue by ohlr** [aws-amplify/amplify-console#771]
** Please describe which feature you have a question about? **
[Delta Deployments](https://aws.amazon.com/blogs/mobile/aws-amplify-console-supports-instant-cache-invalidation-and-delta-deployments/)

** Provide additional details**

I have a gatsby-amplify app. If I remove pages, aka paths from my gatsby app and access them afterwards they are not accessible on my local builds but on AWS the CDN serves the old version of the app when accessing these routes. As soon I access a valid route, it switches to the new version of the app.

My build settings:
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

where yarn build references "gatsby build",
