### ISSUE TITLE
Custom Headers & Build Settings Options for Manual deployment amplify CRA project

### ISSUE THREAD

**Issue by nickchauhan** [aws-amplify/amplify-console#777]
**Please describe which feature you have a question about?**

Custom Headers & Build Settings for Manual deployment project

**Provide additional details**
I have deployed a project using a CRA-based app, with Amplify CLI. I selected manual hosting as per the tutorial [here](https://docs.amplify.aws/start/getting-started/hosting/q/integration/react).
 
I wanted to add custom headers for the project. 
Looking into the [docs](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html) I found that for manual hosting Build Settings option is not visible on AWS amplify Console.

After some research, I found that I have to add amplify.yml file in the project in order to make it work.

So I tried adding the amplify.yml file in the root folder of the project, but it didn't work.

I also tried adding the amplify.yml file in the public folder so that when the app is built it is present in the build folder, but it didn't work.
![aws-amplify-deploy-screenshot](https://user-images.githubusercontent.com/32258248/85112160-d92dfc80-b232-11ea-86ed-26207ccc7ea5.png)

Following the screenshot of my AWS amplify console.

![amplify-console-screenshot](https://user-images.githubusercontent.com/32258248/85110527-aedb3f80-b230-11ea-811a-7bfb75783c59.png)

Following is amplify.yml file content

```yaml
version: 0.1
frontend:
  phases:
    preBuild:
      commands: ['yarn install']
    build:
      commands: ['yarn run build']
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - 'node_modules/**/*'
  customHeaders:
    - pattern: '**/*'
      headers:
        - key: 'Strict-Transport-Security'
          value: 'max-age=31536000; includeSubDomains'
        - key: 'X-Frame-Options'
          value: 'SAMEORIGIN'
        - key: 'X-XSS-Protection'
          value: '1; mode=block'
        - key: 'X-Content-Type-Options'
          value: 'nosniff'
        - key: 'Content-Security-Policy'
          value: 'default-src self'
```
