### ISSUE TITLE
Monorepo test phase does not run

### ISSUE THREAD

**Issue by lukehedger** [aws-amplify/amplify-console#786]
I have configured a monorepo build, as [described in the docs](https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html#monorepo-configuration). The `amplify.yml` file looks like this:

```yaml
version: 1
applications:
  - appRoot: app
    frontend:
      artifacts:
        baseDirectory: public
        files:
          - '**/*'
      phases:
        preBuild:
          commands:
            - npm install --no-audit --no-package-lock --no-progress --silent
        build:
          commands:
            - npm run build
    test:
      artifacts:
        baseDirectory: cypress
        files:
          - '**/*.mp4'
          - '**/*.png'
      phases:
        preTest:
          commands:
            - npm install
        test:
          commands:
            - npx cypress run
```

The provision, build, deploy and verify steps all complete successfully. **But the test phase does not appear to run at all and just displays the "Test is still pending or has been canceled for this build." message**.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/1913316/85394114-f8d06800-b545-11ea-802b-dcc7bbad4385.png">
