### ISSUE TITLE
JS YAMLException crashes amplify console

### ISSUE THREAD

**Issue by davidmatter** [aws-amplify/amplify-console#793]
**Issue Description**
A JS exception related to the amplify.yml file prevents me from seeing the detail view of my amplify console. Modifying the yaml file in my repo doesn't seem to change that behavior.

**Detailed Steps To Reproduce**
Not sure how to reproduce. 

**Copy and Paste Logs + Error Messages (remove sensitive data)**
`main.js:35 uncaught at o YAMLException: duplicated mapping key at line 37, column 1:
    version: 1
    ^
    at m (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:187427)
    at g (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:187525)
    at N (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:188606)
    at D (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:195585)
    at x (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:198146)
    at V (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:200254)
    at j (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:201001)
    at Z (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:201206)
    at Object.O [as safeLoad] (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:102:201463)
    at t.n.generateTabs (https://dqryvwaesjl1l.cloudfront.net/5d82503d58eaefe3954b453be1d2d57823dd518e/main.js:81:148187)`

**Expected behavior**
Even if the amplify.yml file contains errors I should be able to remove the app or modify its build configuration.

**Application Details**
I can't get to my app ID because of the exception.

**The contents of amplify.yml**
```
version: 1
applications:
  - appRoot: frontend
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - BUILD_MODE=$BUILD_MODE make build-frontend
      artifacts:
        baseDirectory: dist
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      customHeaders:
        - pattern: '**/*.js'
          headers:
            - key: 'Cache-Control'
              value: 'public,max-age=31536000,immutable'
        - pattern: '**/*.css'
          headers:
            - key: 'Cache-Control'
              value: 'public,max-age=31536000,immutable'
        - pattern: '**/*.png'
          headers:
            - key: 'Cache-Control'
              value: 'public,max-age=31536000,immutable'
        - pattern: '**/*.jpg'
          headers:
            - key: 'Cache-Control'
              value: 'public,max-age=31536000,immutable'
```
