### ISSUE TITLE
Deployment keeps failing without any log

### ISSUE THREAD

**Issue by mathew-ferry13** [aws-amplify/amplify-console#859]
I am attempting to deploy a static web application for the first time and after a couple attempts I was able to get the build and test steps to complete successfully but the deploy fails with only the following in the log:

```
2020-07-15T11:32:53 [INFO]: Starting Deployment
2020-07-15T11:32:53 [ERROR]: Failed to deploy
2020-07-15T11:32:53 [INFO]: Deployment finished.
```

This is my first time using the amplify-console or AWS at all for that matter so I could be missing something obvious.

I am building a Vue+Vuetify app and attempting to deploy to us-east-2

Possibly related to [115](https://github.com/aws-amplify/amplify-console/issues/115), but unsure

**Comment by abhi7cr** [comment]
Hi @mathew-ferry13,

Could you share your appId?

**Comment by mathew-ferry13** [comment]
Sorry, still new to this - where would I find the app Id?

**Comment by abhi7cr** [comment]
Hi @mathew-ferry13, no problem. You can look at your URL, and it should be the last part of it. Something like this:

https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/<**your_app_id**>

**Comment by mathew-ferry13** [comment]
Thanks @abhi7cr! It is `d35ay78mmhnswg`

**Comment by abhi7cr** [comment]
Hi @mathew-ferry13, It looks like the `configFilePath` property is missing under the `artifacts` section (under the `test` section). It's used to get the test output report. An example of using `configFilePath` in a build spec ([more info on setting up tests](https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html)):
```
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - 'npm start & npx wait-on http://localhost:8080'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

in the above example it's using `mochawesome` to generate the test report. Could you try adding the property, and see if it deploys?
