### ISSUE TITLE
Amplify console does not load anymore because it cannot parse the build yml

### ISSUE THREAD

**Issue by H34D** [aws-amplify/amplify-console#865]
** Please describe which feature you have a question about? **

When i try to load the page:

https://us-east-2.console.aws.amazon.com/amplify/home?region=us-east-2#/'amplify id'

I get the error:

```
“duplicated mapping key at line 27, column 1:
    version: 1
    ^”
2:59
“version: 1
backend:
  phases:
    build:
      commands:
        - ‘# Execute Amplify CLI with the helper script’
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - export NODE_ENV=$STAGE
        - amplify codegen
        - yarn codegen
        - yarn build
        - yarn export
  artifacts:
    baseDirectory: out
    files:
      - ‘**/*’
  cache:
    paths:
      - node_modules/**/*
version: 1
backend:
  phases:
    build:
      commands:
        - ‘# Execute Amplify CLI with the helper script’
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - export NODE_ENV=$STAGE
        - amplify codegen
        - yarn run codegen
        - yarn run build
        - yarn run export
  artifacts:
    baseDirectory: out
    files:
      - ‘**/*’
  cache:
    paths:
      - node_modules/**/*
version: 1
backend:
  phases:
    build:
      commands:
        - ‘# Execute Amplify CLI with the helper script’
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - NODE_ENV = $STAGE
        - amplify codegen
        - yarn run codegen
        - yarn run build
        - yarn run export
  artifacts:
    baseDirectory: out
    files:
      - ‘**/*’
  cache:
    paths:
      - node_modules/**/*
version: 1
backend:
  phases:
    build:
      commands:
        - ‘# Execute Amplify CLI with the helper script’
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - BLOCKSCOUT_URL = $BLOCKSCOUT_URL
        - RPC_URL = $RPC_URL
        - amplify codegen
        - yarn run codegen
        - yarn run build
  artifacts:
    baseDirectory: out
    files:
      - ‘**/*’
  cache:
    paths:
      - node_modules/**/*
”
```

in the javascript console and the website will just stay blank

** Provide additional details**
