### ISSUE TITLE
Cannot deploy NX monorepo app :: !!! Error: Artifact directory doesn't exist: /dist/apps/console

### ISSUE THREAD

**Issue by tengoal** [aws-amplify/amplify-console#892]
My monorepo is build on [nx](https://nx.dev/angular).  I am able to build my app, but I get the following error.  How do I set the artifacts folder?  It is outside of the app's folder.

!!! Error: Artifact directory doesn't exist: /dist/apps/console

![Screen Shot 2020-07-23 at 5 39 12 PM](https://user-images.githubusercontent.com/50420924/88341364-789b4f00-cd0b-11ea-8374-633e8df6cf5d.png)

**Buildspec.yml**

```
version: 1
applications:
    - appRoot: './apps/console'
      frontend:
        phases:
          preBuild:
            commands:
              - npm i -g @angular/cli
              - npm i -g @nrwl/cli
              - npm install
          build:
            commands:
              - nx build console --prod --aot
        artifacts:
          baseDirectory: /dist/apps/console
          files:
             - '**/*'
        cache:
            paths: []
```

**Folder structure:**
![Screen Shot 2020-07-23 at 5 41 40 PM](https://user-images.githubusercontent.com/50420924/88341562-c748e900-cd0b-11ea-9388-0c2b07e41ab2.png)

**Comment by tengoal** [comment]
**Update:** I need to make the directories in preBuild.  Now the error is...

![Screen Shot 2020-07-24 at 12 49 58 PM](https://user-images.githubusercontent.com/50420924/88415268-31b16600-cdac-11ea-932d-0b061c1294da.png)

```
version: 1
applications:
    - appRoot: './apps/console'
      frontend:
        phases:
          preBuild:
            commands:
              - mkdir dist
              - mkdir dist/apps
              - mkdir dist/apps/console
              - npm i -g @angular/cli
              - npm i -g @nrwl/cli
              - npm install
          build:
            commands:
              - nx build console --prod --aot
        artifacts:
          baseDirectory: dist/apps/console
          files:
             - '**/*'
        cache:
            paths:
              - './dist/apps/console/**/*'
```
