### ISSUE TITLE
BUG - Amplify is not serving correct build

### ISSUE THREAD

**Issue by gargshantnu** [aws-amplify/amplify-console#893]
1. **Issue Description**
We have multiple branches connected to the Amplify app. This is our Test Environment app having a custom domain mapping for our test URL, most of the time `master` branch is deployed there. But today we shifted branch to `release-7.1` but the bundle getting served is of `master` branch.

1. **Expected behavior**

We have multiple branched connected with amplify:
![Screenshot 2020-07-24 at 7 37 10 PM](https://user-images.githubusercontent.com/23008972/88399811-131b9100-cde5-11ea-88bb-081b4dc950b8.png)

Selected branch in the custom domain is `release-7.1`
![Screenshot 2020-07-24 at 7 40 40 PM](https://user-images.githubusercontent.com/23008972/88402019-2714c200-cde8-11ea-9939-b5299576d39e.png)

**Expected**: The bundle of the branch selected in the custom domain should be served. 

**How am I sure that bundle served is wrong**:
We are deploying React webpack build, and in our build files, there are few files having timestamps in their names. So by checking the time stamp from files served and files generated in amplify console I can tell which bundle is getting served.
Data gathered from the amplify console.
```
Branch - release-7.1
Timestamp - 1595417150595

Branch - master
Timestamp - 1595509707799
```
Now when I hit my custom domain URL
The expected timestamp is of `release-7.1` branch ( 1595417150595 )
but what I am getting is of `master` branch ( 1595509707799 )

NOTE: If I hit amplify generated URL, they are working correctly.

3. **App configuration**:
a. Amplify Console AppID: `d392v2bx7rclk2`
b. Headers Policy we are using:
```yml
  customHeaders:
    - pattern: '**/*'
      headers:
      - key: 'Cache-Control'
      # 15 day
        value: 'public, must-revalidate, max-age=1296000'
    # dont cache index.html
    - pattern: '**/*.html'
      headers:
      - key: 'Cache-Control'
        value: 'no-cache, no-store, must-revalidate'
```
