### ISSUE TITLE
Possible bug when selecting monorepo directory.

### ISSUE THREAD

**Issue by ernestostifano** [aws-amplify/amplify-console#898]
I have a monorepo with two packages, lets say `package-a` and `package-b` under `./packages`.

When connecting the repository in the Amplify console I check the monorepo checkbox and specify `packages/package-b` as the app directory. However, `package-a` is connected!

I have an `amplify.yml` file in the root of my monorepo.

Here it is:

```yml
version: 1
applications:
  - appRoot: ./packages/package-a
    env:
    variables:
      key: value
    backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      customHeaders:
           - pattern: '**/*'
             headers:
             - key: 'Cache-Control'
               value: 'max-age=86400'
  - appRoot: ./packages/package-b
    env:
    variables:
      key: value
    backend:
      phases:
        build:
          commands:
            - '# Execute Amplify CLI with the helper script'
            - amplifyPush --simple
    frontend:
      phases:
        preBuild:
          commands:
            - yarn install
        build:
          commands:
            - yarn run build
      artifacts:
        baseDirectory: build
        files:
          - '**/*'
      cache:
        paths:
          - node_modules/**/*
      customHeaders:
        - pattern: '**/*'
          headers:
            - key: 'Cache-Control'
              value: 'max-age=86400'
```
