### ISSUE TITLE
Gray screen on main app page after updating build settings

### ISSUE THREAD

**Issue by aware-ravi-bhankharia** [aws-amplify/amplify-console#908]
Hello,

I recently added hosting for a new amplify project. The build fails due to this issue: https://github.com/aws-amplify/amplify-console/issues/595

However, after updating my amplify.yml build settings, I'm no longer able to access the main page for my app - it just shows a gray screen.

Steps to reproduce:

1. Create a new amplify project
2. Add a new lambda function in Python
3. amplify add hosting -> connect branch
4. Attempt to build -> build fails
5. Update amplify.yml to

```
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - export BASE_PATH=$(pwd)
        - yum install -y gcc openssl-devel bzip2-devel libffi-devel python3.8-pip
        - cd /opt && wget https://www.python.org/ftp/python/3.8.2/Python-3.8.2.tgz
        - cd /opt && tar xzf Python-3.8.2.tgz 
        - cd /opt/Python-3.8.2 && ./configure --enable-optimizations
        - cd /opt/Python-3.8.2 && make altinstall
        - pip3.8 install --user pipenv
        - ln -fs /usr/local/bin/python3.8 /usr/bin/python3
        - ln -fs /usr/local/bin/pip3.8 /usr/bin/pip3
        - cd $BASE_PATH
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

6. Gray screen of death

I have another amplify project using the same amplify.yml from 2 weeks ago that is working perfectly fine with the same setup.

I'm currently blocked from updating my new amplify app entirely due to this issue. I can re-create the app, but I can't build with the default settings due to the linked issue or update my amplify.yml without getting a gray screen.
