### ISSUE TITLE
Cloudfront cache is deleted every 1 second

### ISSUE THREAD

**Issue by thedgbrt** [aws-amplify/amplify-console#92]
**Describe the bug**
All assets return `x-cache: Miss from Cloudfront`, even after multiple refreshes. It only returns a cached version when a request is made less than one second after the previous one.

**Environment**
Default Gatsby app. The amplify console sets the infrastructure to `Infrastructure: Gatsby-Amplify`

**Proof**
Request the same asset with 2000ms interval, we always get a MISS:
```
while true; do curl -X HEAD -i https://master.dsvk1bi06ng1b.amplifyapp.com/ -s | grep -Fi x-cache; sleep 2; done
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
x-cache: Miss from cloudfront
```

Request the same asset with 100ms interval, we only get a MISS every ~1second:
```
while true; do curl -X HEAD -i https://master.dsvk1bi06ng1b.amplifyapp.com/ -s | grep -Fi x-cache; sleep 0.1; done
x-cache: Miss from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Miss from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
x-cache: Miss from cloudfront
x-cache: Hit from cloudfront
x-cache: Hit from cloudfront
```

**To Reproduce**
use this command from the terminal:
```while true; do curl -X HEAD -i https://master.dsvk1bi06ng1b.amplifyapp.com/ -s | grep -Fi x-cache; sleep 2; done```

Alternatively, you can go to the [deploy url](https://master.dsvk1bi06ng1b.amplifyapp.com/) and refresh the page with the network inspector open.

**Expected behavior**
Cloudfront should only invalidate cache when a new deployment is made. For every request after the first one, it should return the cached version from the CDN, [as mentioned here](https://aws.amazon.com/fr/blogs/mobile/aws-amplify-console-supports-instant-cache-invalidation-and-delta-deployments/).

![Picture1](https://user-images.githubusercontent.com/1362558/64035704-c20e0900-cb51-11e9-96e6-b905fac26653.png)

**Sample code**
I've created a demo repo to view the issue.
- [repo url](https://github.com/thedgbrt/gatsby-site)
- [deployed link](https://master.dsvk1bi06ng1b.amplifyapp.com/)

**Comment by thedgbrt** [comment]
I could also reproduce with a standard create-react-app.

https://master.d1qu22wwco4729.amplifyapp.com
https://github.com/thedgbrt/create-react-app

**Comment by swaminator** [comment]
@thedgbrt The diagram in the blog post doesn't fully explain how our 'CDN' works - we have dual layer CDN distributions so what happens is that you're seeing the miss from the CDN Edge vs the CDN Origin. We have an issue reporting information correctly in the header responses which has led to confusion from other customers before as well. We will prioritize a fix for this soon. Hope that helps - thanks for the detailed explanation.

**Comment by thedgbrt** [comment]
@swaminator thanks for the quick answer.
What I'm concerned about is response time. When I manage to hit the CloudFront cache, I get a response in 10-30ms, which is what I'm used to when using a CDN.

However when I don't hit it (that is, 99% of the time right now), it's in the 50-200ms range, and can go up to 500ms. For an SPA with code split between 10-20 files each page, this has a dramatic impact on user experience. I routinely have to wait 1-2 seconds for a simple page change that could be almost instant.

I don't know how much if that has to do with proper cache headers being set, or with the way amplify console fundamentally manages CDN responses. Is the fix that is being prioritized going to lower response times to expected CloudFront levels?

**Comment by cslogan-red** [comment]
Trying to provide a little more clarity until we've got a further solution. As @swaminator mentioned, your content is being cached and returned by our origin CDN, however you're seeing the response header from the closest edge CDN as a miss (which is by design), which is understandably confusing. The design is a bit more complex than alluded to, but in order to facilitate instant deployment changes (including invalidation of cached resources) and have as performant hosting as possible for all of our customers, we've implemented a dual layer CDN structure with an edge layer in-between. The response times you're seeing come from the brief edge layer invocation, before the content is then retrieved from the origin CDN (if it exists there, otherwise it is retrieved all the way from actual origin, which takes much longer). This round-trip time is several times faster than if we went straight to origin, and is still giving you the benefit of cached content (read; not re-serving from hosting origin if the file hasn't changed). We understand that certain customers (like in the example provided, with heavy code splitting) may want to optimize their edge CDN performance even further, and we are looking at a number of ways to provide this.

That said, your unmodified content _**is**_ being cached and served from our origin CDN, the edge CDN response header just makes this confusing.

**Comment by mrcoles** [comment]
@cslogan-red what about being able to respond with 304 “not modified” for assets (for example my site.webmanifest file gets requested with a 200 status every time, despite the request header and response header etags matching) and also what if the instant deployment optimizations were bypassed if the cache headers are aggressive enough (e.g., "Cache-Control: public,max-age=31536000,immutable")?

**Comment by cslogan-red** [comment]
@mrcoles we're considering a number of solutions for both the confusing initial response header from the edge CDN as well as tuning the edge CDN's performance that just need prioritization, we'll respond to this thread once we've implemented an update!

**Comment by arelaxend** [comment]
I can also see the following parameter in the request "public, must-revalidate, max-age=0". Is there any advancement or temporary solution for this ? Thank you for the good work

**Comment by arelaxend** [comment]
Hm, do you agree that is not the expected behavior that Chrome or any browser can not cache to disk any files provided by cloudfront, JS, CSS files and so on ?

**Comment by isi-gach** [comment]
have you tried something like this?
`amplify.yml`
```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn
    build:
      commands:
        - yarn build
  customHeaders:
    - pattern: '/*.chunk.js'
      headers:
      - key: 'Cache-Control'
        value: 'public, max-age=31536000, immutable'
```

**Comment by arelaxend** [comment]
> have you tried something like this?
> `amplify.yml`
 ```

It works. 🥇  I have used `pattern: '**/*'` instead for more generality.

**Comment by supersetapp** [comment]
@arelaxend setting those Cache-Control headers can be super useful, but be careful you’re not caching content that you want to update at some later time. Doing `pattern: '**/*'` would set that Cache-Control header on your HTML files and other things that usually don’t want such extreme caching (usually you only want aggressive caching on just images, JS, CSS—especially if they have a content hash in their filename).

This doesn’t address the issue of how the CDN is not returning 304 not modified when request and response etag headers match (https://github.com/aws-amplify/amplify-console/issues/92#issuecomment-545609647)

**Comment by masterofkfit** [comment]
Any update on this?

This should be fixed ASAP as cloudfront is considered broken

**Comment by litwicki** [comment]
@masterofkfit @thedgbrt can you please let us know if you're still experiencing this as it should be resolved.

**Comment by robbie-thompson** [comment]
@swaminator why was this closed? I can still replicate this on a standard setup.

**Comment by marco910** [comment]
@robbie-thompson I had the same issue a few weeks ago and found a solution that works for me. I don't know if this is the "right" way, but it works. To cache the assets in the CloudFront cache I did the following:

1. Added these custom header to my `customHttp.yml`:
```
customHeaders:
- pattern: '**/*.html'
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=60'
      - key: x-frame-options
        value: DENY
      - key: x-xss-protection
        value: 1; mode=block
  - pattern: '**/*[!.html]'
    headers:
      - key: Cache-Control
        value: 'public,max-age=31536000,immutable'
      - key: x-frame-options
        value: DENY
      - key: x-xss-protection
        value: 1; mode=block
```

2. Enable performance mode in the app settings in the Amplify console.
3. Redeploy the last version to create a new build with the custom headers and performance mode.

**Comment by cslogan-red** [comment]
@robbie-thompson see [performance mode docs](https://docs.aws.amazon.com/amplify/latest/userguide/ttl.html#Performance-mode) for more info. We launched our redesigned hosting and deployment modules around the time this issue was closed, which removes the CDN sandwich I described earlier in this thread for a more standard and fine tuneable setup. By default, in "development mode", we expire the CDN cache every second to facilitate instantly showing deployed changes in origin, once you're in steady state, on say your Production branch that doesn't see deployed changes as regularly, enabling performance mode for that branch reconfigures the CDN timeout to be biased towards app performance at the sake of a delay between deployed changes appearing. Further, you can fine tune the behavior in addition by providing your own custom header overrides for specific paths, as @marco910 example shows.

**Comment by mathan-xflowpay** [comment]
@marco910 Thanks for this. But I have tried different this and multiple other variations also. But irrespective of the pattern always the last the cache-control gets applied to all the requests css, js and index. In the example which you provided its always applying the cache-control of the pattern `'**/*[.html]'` for everything. I am thinking that definitely something is wrong with amplify which is causing this. My live website is [here](https://beta.xflowpay.com/)

**Comment by marco910** [comment]
@mathan-xflowpay I'm facing currently a very similar issue that the cache is not being cleared after redeploying a new version of the site. If you change the content on a page and redeploy the site, do you see the changes on the page?

**Comment by Reselence** [comment]
@marco910 I've tried adding your suggested customHttp.yml but I'm also not seeing any differences. When you say that your output directory was incorrect, what was it and what did you change it to? Maybe I'm doing something wrong too?

My files are as follows:

amplify.yml

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 16.10.0
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```


customHttp.yml
```
customHeaders:
  - pattern: /_next/static/**/*
    headers:
      - key: Cache-Control
        value: 'public, max-age=31536000, immutable'
      - key: x-frame-options
        value: DENY
      - key: x-xss-protection
        value: 1; mode=block
  - pattern: /_next/data/**/*
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=0, must-revalidate'
      - key: x-frame-options
        value: DENY
      - key: x-xss-protection
        value: 1; mode=block
  - pattern: '**/*[.html]'
    headers:
      - key: Cache-Control
        value: 'public, max-age=0, s-maxage=0, must-revalidate'
      - key: x-frame-options
        value: DENY
      - key: x-xss-protection
        value: 1; mode=block
```

**Comment by marco910** [comment]
@Reselence When deploying a static generated (SSG) site to Amplify you need to apply a different output directory than for sites with server-rendering (SSR) or Incremental Site Regeneration (ISR). For SSG you need to use `out` and for sites with SSR and ISR `.next`.

These are my build settings for an SSG site:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - npm run export
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
Please note that you have to change the build command to the command you specified in your `package.json` file. In my case, `npm run export` will run `next build && next export`. This will only work for SSG sites. For SSR and ISR sites you have to use `next build` so that Amplify detects this as sites with SSR/ISR.

**Comment by leo-stefan** [comment]
@marco910 Ah that's an issue. I use an API route for a contact form, but API routes do not work with export. When building my site however, all pages except the API route are marked as static so I would have assumed that I could still control the cache properties.

Performance mode seems to work without a customHttp file, but I want to cache images etc for as long as possible since I will only update this site a couple times a year.

Is there no way to have control of the cache properties this way?

**Comment by Reselence** [comment]
Ah that's an issue. I use an API route for a contact form, but API routes do not work with export. When building my site however, all pages except the API route are marked as static so I would have assumed that I could still control the cache properties.

Performance mode seems to work without a customHttp file, but I want to cache images etc for as long as possible since I will only update this site a couple times a year.

Is there no way to have control of the cache properties this way?

**Comment by Reselence** [comment]
@marco910 Ah that's an issue. I use an API route for a contact form, but API routes do not work with export. When building my site however, all pages except the API route are marked as static so I would have assumed that I could still control the cache properties.

Performance mode seems to work without a customHttp file, but I want to cache images etc for as long as possible since I will only update this site a couple times a year.

Is there no way to have control of the cache properties this way?

**Comment by marco910** [comment]
@Reselence You can try to add the headers already in Next.js. Also can try using this in customHttp.yml:
```
customHeaders:
  - pattern: '**/*.{jpg|jpeg|png|svg|bmp|tiff|webp|avif|ico}'
    headers:
      - key: Cache-Control
        value: 'public, max-age=31536000, immutable'
```
Maybe you have to edit the pattern depending on the file types you're using on your site.
