### ISSUE TITLE
updated build config, successful build, but new artifacts not in domain

### ISSUE THREAD

**Issue by zoosissoos** [aws-amplify/amplify-console#963]
Hi. I recently updated my build config to use Gatsby + Cypress testing, but now am unable to see the uploaded artifacts in my app domain. It seems as if none of the build artifacts are actually being uploaded in the deployment phase, yet in the logs it says they successfully were.

Build settings:
```
version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yarn install
        - yarn add mocha mochawesome mochawesome-merge mochawesome-report-generator
    test:
      commands:
        - npx start-test 'yarn start' 8000 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

Log is attached
[log (11).txt](https://github.com/aws-amplify/amplify-console/files/5070932/log.11.txt)

**Comment by zoosissoos** [comment]
After further researching this, It seems the branch preview link within the AWS console is not correctly pointing to the app correctly.

For example, If I click on the link within the console I get a blank page, but if I go to "https://master.appnumber.amplifyapp.com/page-2" it correctly appears.
I am able to go back to "https://master.appnumber.amplifyapp.com/" from this page and it correctly appears but it does not work when I click on the aws console link. The page does not also appear when I manually enter "https://master.appnumber.amplifyapp.com/" into the browser. Only from "https://master.appnumber.amplifyapp.com/page-2" will it show.

**Comment by hsspain** [comment]
@zoosissoos 

Can you provide us the AppID and region you are hosting your Amplify app in?

**Comment by zoosissoos** [comment]
Not to be rude, but is there a way I can privately send you these things?

**Comment by hsspain** [comment]
No worries, please use aws-amplify-customer@amazon.com to send us the information.

**Comment by zoosissoos** [comment]
Sent the information to the email provided.

**Comment by liamegan** [comment]
Was there ever a resolution to this? I seem to be running into a similar issue but can't seem to break the cache in any way.

**Comment by Gowiem** [comment]
@hsspain Yeah, running into the same @liamegan. Is this a pervasive issue?

**Comment by hspain** [comment]
@Gowiem @liamegan Can you provide your region and App ID? We will take a look.

**Comment by liamegan** [comment]
Sent.

**Comment by hsspain** [comment]
This issue has been resolved and a redeployment of any affected apps should clear up the improper routing.  Please let us know if there are any further issues.

**Comment by zoosissoos** [comment]
I was able to find a resolution to this through AWS support:

====================================================================

The issue seems to be that running cypress overwrites the production build. In the yml build config, you must make a new directory:

Hi,

I really appreciate your patience.

After deep diving the weird behavior of current build and test with Cypress, I was able to identity the root cause and resolve it.

Below is what happened from your previous build yaml file:

1. During Build Phase,  'yarn run build'  will build and place production code in 'public' folder

2. Later on, from the  'Pretest' phase, when following command is executed, it will actual run  'gatsby develop' as configured from your 'package.json' and eventually override 'public' folder. As a result, the final build artifact for your website was modified during Cypress test which cause  the blank home page 
 
     -  yarn start & npx wait-on http://127.0.0.1:8000  

In order to resolve the issue, you can rename the 'build' folder to other name such as 'dist' and set this 'dist' folder for build artifact as below. By doing so, Cypress test will not override the production build folder (dist folder)
 
1.Changing name of public folder
    build:
      commands:
        - gatsby clean
        - yarn run build
        - mv public dist # changing name of public folder 

2. Changing build folder to 'dist' instead of 'public'

  artifacts:
    baseDirectory: dist #New folder to avoid being overridden by cypress
    files:
      - '**/*'

Below is my build yaml in my replication environment which gets my app built successfully with proper output from homepage. 
============================================================
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - gatsby clean
        - yarn run build
        - mv public dist # changing name
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yarn install
        - yarn add wait-on
        - yarn add mocha mochawesome mochawesome-merge mochawesome-report-generator
        - "yarn start & npx wait-on http://127.0.0.1:8000 "
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge@4 cypress/report/mochawesome-report/*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
        - "**/*.png"
        - "**/*.mp4"

**Comment by zoosissoos** [comment]
So I was able to find a resolution to this through AWS support. It seems that running cypress was overwriting the folder containing the artifacts needed, so that the development was overwriting production. I was provided with a yml that fixed my problem. 

```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - gatsby clean
        - yarn run build
        - mv public dist # changing name
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - yarn install
        - yarn add wait-on
        - yarn add mocha mochawesome mochawesome-merge mochawesome-report-generator
        - "yarn start & npx wait-on http://127.0.0.1:8000 "
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge@4 cypress/report/mochawesome-report/*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
        - "**/*.png"
        - "**/*.mp4"
```
