### ISSUE TITLE
Cypress test integration fails

### ISSUE THREAD

**Issue by hamidgh** [aws-amplify/amplify-console#964]
I have a React app and I want to integrate Cypress but it fails on test pipeline. Not sure what is going on
When I run the test locally it passes!

![image](https://user-images.githubusercontent.com/2271701/90185557-85e0b200-dd7c-11ea-8c81-f91ebb0ea1e1.png)

**Comment by behrooziAWS** [comment]
What does your artifacts portion of your amplify.yml look like? Currently every element in the [artifacts section](https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html#add-tests-to-your-existing-amplify-app) is required.

i.e:
```
artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```
