### ISSUE TITLE
cancelled - no diff detected from previous commit

### ISSUE THREAD

**Issue by CurtisHumphrey** [aws-amplify/amplify-console#973]
** Please describe which feature you have a question about? **
When doing automatic branch building from a GitHub repo sometimes we get this message "cancelled - no diff detected from previous commit"

** Provide additional details**
We think it is related to our mono repo structure.  Sometimes we do not change anything directly in the AppSync package folder but the related lambda's that are in other package folders that we also build via Amplify's CD pipeline.

amplify.yml
```
version: 1
applications:
  - appRoot: packages/hr_api
    backend:
      phases:
        preBuild:
          commands:
            - COMMIT_MESSAGE=$(git log -1 --pretty=%B | cat)
            - if [ "${AWS_BRANCH}" = "master" ] && [[ $COMMIT_MESSAGE != chore\(release\):* ]]; then echo "a non release commit on master" && exit 1; fi;
            - yarn install
        build:
          commands:
            - yarn run use_real_graphql
            - amplifyPush --simple
            - export sls_stage=$(echo $AWS_BACKEND_ENVIRONMENT_ARN | cut -d '/' -f 4)
            - export sls_version=$(yarn run sls --version | grep 'Framework Core' | cut -d ' ' -f 3)
            - if [ "${AWS_BRANCH}" = "master" ]; then export sls_logRetentionInDays=400; else export sls_logRetentionInDays=14; fi;
            - export appsync_graphqlEndpoint=$(cat src/aws-exports.js | grep aws_appsync_graphqlEndpoint | cut -d \" -f 4)
            - export appsync_user_pools_id=$(cat src/aws-exports.js | grep aws_user_pools_id | cut -d \" -f 4)
            - export appsync_user_pools_web_client_id=$(cat src/aws-exports.js | grep aws_user_pools_web_client_id | cut -d \" -f 4)
            - yarn workspace ceridian_functions run deploy
            - yarn workspace qualtrics_functions run deploy
        cache:
          paths:
            - ../../node_modules/**/*
            - ~/.cache/yarn/**/*
    frontend:
      phases:
        preBuild:
          commands: []
        build:
          commands: []
      artifacts:
        baseDirectory: /publish
        files:
          - '**/*'
      cache:
        paths: []
```
