### ISSUE TITLE
!!! Error: Artifact directory doesn't exist: build

### ISSUE THREAD

**Issue by mbast100** [aws-amplify/amplify-console#987]
I use to deploy my react app on S3 Buckets, but the UI has been broken on it. And decided to give it a try with Amplify and i get the following error:

!!! Error: Artifact directory doesn't exist: build

![image](https://user-images.githubusercontent.com/44484872/90839783-5276c800-e326-11ea-8bf8-b71a33958154.png)

**Comment by mathvbarone** [comment]
I am having the same issue...when I trigger the pipeline without the test stage all works as expected, however, if I add the test stage I get the exact same error. The baseDirectory is the same in both cases.

**Comment by mathvbarone** [comment]
Here is my `amplify.yml`:

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 12.18.3
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: dist
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm install
        - npm install wait-on
        - npm install mocha@5.2.0 mochawesome mochawesome-merge mochawesome-report-generator
        - "npm start & npx wait-on http://localhost:3001"
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
  artifacts:
    baseDirectory: cypress
    configFilePath: "**/mochawesome.json"
    files:
      - "**/*.png"
      - "**/*.mp4"


```
